src/BootstrapBlazor/Components/Logout/LogoutLink.razor

`<LogoutLink  Text="Log Out" />`
This Text parameter is not reflected to the UI. 
With this fix, Text parameter is shown in the component

logout link text fix

---

src/BootstrapBlazor/Components/Upload/InputUpload.razor

Summary:
InputUpload has remove and add buttons. When render this component thats buttons have several classes like:
`btn btn-primary btn btn-danger` and `btn btn-primary btn btn-browser btn-primary`.
Thats happend because buttons (`ButtonBase`) generate `ClassName` from `Color` with default value `Color.Primary`.
I think that fix may repair it, because `RemoveButtonClassString` from `InputUpload` use value from `DeleteButtonClass` with `btn-danger`, `BrowserButtonClassString` works same.

fix: multiply class for upload input buttons

---

src/BootstrapBlazor/Components/Table/Table.razor
test/UnitTest/Components/TableFilterTest.cs

Eliminated bug in Table Component:
The TableFilter was Rendered twice when ShowFilterHeader and TableColumn.Filterable were set. 
Fix tested on Blazor Server und new UnitTest.

fix: The TableFilter was rendered twice 

---

src/BootstrapBlazor/Components/Filters/BoolFilter.razor.cs
src/BootstrapBlazor/Components/Filters/DateTimeFilter.razor.cs
src/BootstrapBlazor/Components/Filters/EnumFilter.razor.cs
src/BootstrapBlazor/Components/Filters/IFilterAction.cs
src/BootstrapBlazor/Components/Filters/LookupFilter.razor.cs
src/BootstrapBlazor/Components/Filters/NumberFilter.razor.cs
src/BootstrapBlazor/Components/Filters/StringFilter.razor.cs
src/BootstrapBlazor/Components/Table/Table.razor
src/BootstrapBlazor/Components/Table/Table.razor.cs
test/UnitTest/Components/TableBoolFilterTest.cs
test/UnitTest/Components/TableDateTimeFilterTest.cs
test/UnitTest/Components/TableEnumFilterTest.cs
test/UnitTest/Components/TableFilterTest.cs
test/UnitTest/Components/TableLookupFilterTest.cs
test/UnitTest/Components/TableNumberFilterTest.cs
test/UnitTest/Components/TableStringFilterTest.cs
test/UnitTest/Components/TableTest.cs

New table functions:
1) Added Table.ResetAllColumnsFilter() method.
You can use this method to reset all filters.
It needs the fix for the TableFilter I pulled earlier.
2) Added the IFilterAction.SetFilterConditions(IEnumerable<FilterKeyValueAction> conditions) method, extending the existing filters.
This allows you to overwrite the existing conditions.
Also, I added unit tests for all new methods.

feat: Added Table.ResetAllColumnsFilter() and IFilterAction.SetFilterConditions method

---

src/BootstrapBlazor/Components/ValidateForm/BootstrapBlazorEditContextDataAnnotationsExtensions.cs
src/BootstrapBlazor/Components/ValidateForm/ValidateForm.razor.cs
test/UnitTest/Components/ValidateFormTest.cs

When `ValidateForm` validate, make the service available in a custom `ValidationAttribute` as follows,
https://github.com/dotnetcore/BootstrapBlazor/blob/da52e122f91ad511de6220ac6beb88b72f376442/test/UnitTest/Components/ValidateFormTest.cs#L408-L410

feat: ValidationContext implements IServiceProvider interface

---

src/BootstrapBlazor/Components/Calendar/Calendar.razor.cs

Fix bug that navigation buttons in Calendar don't trigger ValueChanged event.
Functions OnChangeYear, OnChangeMonth and OnChangeWeek in Calendar component changes only Value and don't trigger event ValueChanged. This Pull Request is going to fix that problem.
Tested on working solution.

Fix bug that navigation buttons in Calendar don't trigger ValueChanged event.

---

src/BootstrapBlazor.Shared/Samples/Uploads.razor.cs
src/BootstrapBlazor/Extensions/UploadFileExtensions.cs
test/UnitTest/Components/UploadTest.cs

refactor UploadFile use extensions method

---

src/Extensions/Components/BootstrapBlazor.BaiduOcr/BootstrapBlazor.BaiduOcr.csproj
src/Extensions/Components/BootstrapBlazor.BaiduOcr/Models/BaiduOcrResult.cs
src/Extensions/Components/BootstrapBlazor.BaiduOcr/Services/BaiduOcr.cs
src/Extensions/Components/BootstrapBlazor.BaiduOcr/Services/IBaiduOcr.cs

feat: IBarduOcr support get json raw string

---

src/Extensions/Components/BootstrapBlazor.BaiduOcr/BootstrapBlazor.BaiduOcr.csproj
src/Extensions/Components/BootstrapBlazor.BaiduOcr/Services/BaiduOcr.cs
src/Extensions/Components/BootstrapBlazor.BaiduOcr/Services/IBaiduOcr.cs

feat: add CancellationToken parameter on CheckVatInvoiceJsonAsync method

---

src/BootstrapBlazor.Shared/Demos/BaiduOcr/BaiduOcrNormal.razor

add asynchronous operation function to the VAT invoice upload button

---

src/BootstrapBlazor/Components/Table/Table.razor.Toolbar.cs
test/UnitTest/Components/TableDialogTest.cs

add unit test for table on tracking mode

---

src/Extensions/Components/BootstrapBlazor.BaiduOcr/BootstrapBlazor.BaiduOcr.csproj
src/Extensions/Components/BootstrapBlazor.BaiduOcr/Models/InvoiceEntity.cs
src/Extensions/Components/BootstrapBlazor.BaiduOcr/Models/InvoiceVerifyResult.cs
src/Extensions/Components/BootstrapBlazor.BaiduOcr/Services/BaiduOcr.cs
src/Extensions/Components/BootstrapBlazor.BaiduOcr/Services/IBaiduOcr.cs

feat: add verify vat invoice component

---

src/BootstrapBlazor.Shared/Demos/BaiduOcr/BaiduOcrNormal.razor
src/BootstrapBlazor.Shared/Demos/BaiduOcr/BaiduOcrVerifyVatInvoice.razor
src/BootstrapBlazor.Shared/Locales/en.json
src/BootstrapBlazor.Shared/Locales/zh.json
src/BootstrapBlazor.Shared/Samples/BaiduOcr.razor
src/Extensions/Components/BootstrapBlazor.BaiduOcr/BootstrapBlazor.BaiduOcr.csproj

doc: add verify vat invoice sample code

---

src/BootstrapBlazor.Shared/Demos/BaiduOcr/BaiduOcrVerifyVatInvoice.razor

doc: update verify vat invoice sample code

---

src/BootstrapBlazor/wwwroot/modules/modal.js

fix: can not drag Dialog/Model when set IsScrolling to true

---

src/BootstrapBlazor.Shared/Samples/SweetAlerts.razor
src/BootstrapBlazor.Shared/Samples/SweetAlerts.razor.cs
src/BootstrapBlazor/Components/Dialog/Dialog.razor
src/BootstrapBlazor/Components/Dialog/Dialog.razor.cs
src/BootstrapBlazor/Components/SweetAlert/SwalOption.cs
src/BootstrapBlazor/Components/SweetAlert/SwalService.cs
src/BootstrapBlazor/Components/SweetAlert/SweetAlert.razor.cs
src/BootstrapBlazor/Components/SweetAlert/SweetAlertBody.razor.cs
src/BootstrapBlazor/Extensions/SwalExtensions.cs
src/BootstrapBlazor/wwwroot/modules/modal.js
test/UnitTest/Components/SwalTest.cs

feat: add OnCloseAsync/OnConfirmAsync callback on SwalAlert component

---

src/BootstrapBlazor.Shared/Demos/Dialog/DialogCloseDialogByCode.razor
src/BootstrapBlazor.Shared/Demos/Dialog/DialogDisableHeaderCloseButton.razor
src/BootstrapBlazor/Components/Dialog/DialogOption.cs
src/BootstrapBlazor/Components/Dialog/EditDialogOption.cs
src/BootstrapBlazor/Components/Validate/ValidateBase.cs
src/BootstrapBlazor/Extensions/DialogServiceExtensions.cs

feat: add CloseDialogAsync method on DialogOption

---

src/BootstrapBlazor/Components/Dialog/Dialog.razor
src/BootstrapBlazor/Components/Dialog/Dialog.razor.cs
src/BootstrapBlazor/Components/Dialog/DialogOption.cs
src/BootstrapBlazor/Components/Modal/ModalDialog.razor.cs
src/BootstrapBlazor/wwwroot/modules/modal.js

fix: modal backdrop HTML tag value is inconsistent with background data

---

src/BootstrapBlazor.Server/Program.cs
src/BootstrapBlazor.Shared/Samples/LayoutDemo.razor
src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Tab/Tab.razor.cs
src/BootstrapBlazor/Extensions/BootstrapBlazorServiceCollectionExtensions.cs
src/BootstrapBlazor/Options/TabItemMenuBindOption.cs
src/BootstrapBlazor/Options/TabItemMenuBindOptions.cs
test/UnitTest/Components/TabTest.cs
test/UnitTest/Core/TabTestBase.cs
test/UnitTest/Pages/Binder.cs

feat: add AddTabItemBindOptions service

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/RibbonTab/RibbonTab.razor
src/BootstrapBlazor/Components/RibbonTab/RibbonTab.razor.cs
src/BootstrapBlazor/Components/Tab/Tab.razor
src/BootstrapBlazor/Components/Tab/Tab.razor.cs
test/UnitTest/Components/TabTest.cs

feat: add OnClickTabItemAsync method

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Switch/Switch.razor.cs

fix(Switch): missing await keyword on OnValueChanged callback

---

src/BootstrapBlazor/Components/Anchor/AnchorLink.razor.cs
src/BootstrapBlazor/Components/AutoComplete/AutoComplete.razor.cs
src/BootstrapBlazor/Components/AutoFill/AutoFill.razor.cs
src/BootstrapBlazor/Components/Avatar/Avatar.razor.cs
src/BootstrapBlazor/Components/Button/ButtonBase.cs
src/BootstrapBlazor/Enums/ComponentIcons.cs
src/BootstrapBlazor/Options/Constants.cs
test/UnitTest/Components/ButtonTest.cs

feat(Button): support config Icon

---

src/BootstrapBlazor/Components/Toast/Toast.razor.cs
test/UnitTest/Components/ToastTest.cs

update Toast IconOptions code
close #869

fix(Toast): missing Icon on ToastOption

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Table/Table.razor

fix(Table): should not resize the fixed column

---

src/BootstrapBlazor.Shared/Demos/Logouts/LogoutLinkTemplate.razor
src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Logout/LogoutLink.razor
src/BootstrapBlazor/Components/Logout/LogoutLink.razor.cs
src/Extensions/Components/BootstrapBlazor.Chart/BootstrapBlazor.Chart.csproj
test/UnitTest/Components/LogoutLinkTest.cs

feat(LogoutLink): remove OnClick callback

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Select/SelectTree.razor.cs

fix(SelectTree): do not show the Text when value is not null in first render

---

src/BootstrapBlazor/Components/Layout/Layout.razor.cs
test/UnitTest/Components/LayoutTest.cs

fix(Layout): check authorization at first render

---

src/BootstrapBlazor/Components/Circle/CircleBase.cs
src/BootstrapBlazor/Components/Timer/Timer.razor.cs
src/BootstrapBlazor/Components/Timer/Timer.razor.js

feat(Timer): use JavaScript isolation

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Button/ButtonBase.cs
src/BootstrapBlazor/Components/Table/TableExtensionButton.razor

feat(TableCellButton): support ChildContent/BodyTemplate parameter

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Redirect/Redirect.cs
test/UnitTest/Components/RedirectTest.cs

feat(Redirect): add ForceLoad parameter

---

src/BootstrapBlazor/Components/Dialog/DialogCloseButton.cs
src/BootstrapBlazor/Components/Dialog/DialogSaveButton.cs

fix(DialogButton): no restore button icon if set IsAsync to true

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Tab/Tab.razor.cs
test/UnitTest/Components/LayoutTest.cs
test/UnitTest/Options/BootstrapBlazorOptionsTest.cs

feat(Tab): add Resource value

---

src/BootstrapBlazor/Attributes/JSModuleNotInheritedAttribute.cs
src/BootstrapBlazor/Components/BaseComponents/BootstrapModuleComponentBase.cs

feat(BootstrapDynamicComponent): add new overload method for CreateComponent

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Select/Select.razor.cs
src/BootstrapBlazor/Components/Select/Select.razor.js
test/UnitTest/Components/SelectTest.cs

refactor(Select): not trigger SelectedItemChanged callback when click Empty item

---

src/BootstrapBlazor/Components/SweetAlert/SwalOption.cs

IsConfirm must be public. When try to use confirm button it's not visible
close #1508

feat(SwalOption): update IsConfirm to public

---

src/BootstrapBlazor/Components/Step/Steps.razor.cs

在`OnParametersSet`初始化Items时，使用`??=`代替`=`。
close #1543

fix(Steps): items always empty

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Table/Table.razor.cs
src/BootstrapBlazor/Components/Table/Table.razor.js
test/UnitTest/Components/TableTest.cs

feat(Table): add OnResizeColumnCallback parameter

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/GoTop/GoTop.razor.cs
src/BootstrapBlazor/Components/GoTop/GoTop.razor.js

fix(GoTop): should not throw exception when Target is null or empty

---

src/BootstrapBlazor/Components/ImageViewer/ImageViewer.razor.cs
test/UnitTest/Components/ImageTest.cs
test/UnitTest/Components/SwalTest.cs

fix(ImageViewer): can't reload imager after occur error

---

src/BootstrapBlazor/wwwroot/modules/viewer.js

Fix the bug that the image does not follow the mouse when dragging (Implement Image Moving by setting margin must be set up, down, left and right simultaneously).
Original behavior: When drag the mouse (or touch) from the upper left to the lower right,  the image only moves half the distance.
Principle of bug : use Margin to move an image, need to set both left and right, up and down at the same time, for example: margin-left:100px;margin-right:-100px. Move 100px to the right, if only set one it will only move 50px.
After revision: Set the upper left and lower right simultaneously.
close #2172

fix(ImageViewer): drag image not smooth

---

src/BootstrapBlazor/Components/Menu/MenuLink.razor.cs

Solutions as per https://github.com/dotnet/aspnetcore/issues/9156 <NavLink href="/" Match=NavLinkMatch.All>Home</NavLink>
close #2207

fix(MenuLink): always active if href equal "/"

---

src/Extensions/Components/BootstrapBlazor.Dock/Components/DockView/DockView.razor.cs
src/Extensions/Components/BootstrapBlazor.Dock/Components/DockView/DockView.razor.js

feat(DockView): add Reset instance method

---

src/BootstrapBlazor.Shared/BootstrapBlazor.Shared.csproj
src/BootstrapBlazor.Shared/Locales/en.json
src/BootstrapBlazor.Shared/Locales/zh.json
src/BootstrapBlazor.Shared/Samples/Table/Tables.razor.cs
src/BootstrapBlazor.Shared/Samples/Table/TablesEdit.razor
src/BootstrapBlazor.Shared/docs.json
src/BootstrapBlazor/Components/EditorForm/EditorForm.razor
src/BootstrapBlazor/Components/EditorForm/EditorForm.razor.cs
src/BootstrapBlazor/Components/Table/Table.razor.cs
src/BootstrapBlazor/Utils/Utility.cs
src/Extensions/Components/BootstrapBlazor.Dock/Components/DockView/DockView.razor.js
test/UnitTest/Components/EditorFormTest.cs
test/UnitTest/Components/TableTest.cs
test/UnitTest/Utils/GroupTest.cs

feat(Table): order of edit pop-up consisitent with table column

---

src/BootstrapBlazor/Components/Layout/Layout.razor
src/BootstrapBlazor/Components/Layout/Layout.razor.cs
test/UnitTest/Components/LayoutTest.cs

feat(Layout): add AllowDragTab on Layout component

---

src/BootstrapBlazor.Shared/Samples/CountUps.razor
src/BootstrapBlazor.Shared/Samples/CountUps.razor.cs
src/BootstrapBlazor/Components/CountUp/CountUp.razor
src/BootstrapBlazor/Components/CountUp/CountUp.razor.cs

fix(CountUp): not show the Value when set value to 0

---

src/BootstrapBlazor.Shared/Samples/Table/TablesDynamic.razor
src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Table/Table.razor.Toolbar.cs

fix(Table): can't edit when table data source is DynamicContext

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/ValidateForm/ValidateForm.razor.cs
test/UnitTest/Validators/ValidatorAsyncTest.cs

fix(ValidateForm): OnValidSubmit runs before ValidateAsync

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Table/Table.razor.js

fix(Table): not trigger OnResizeColumnAsync callback

---

src/BootstrapBlazor.Server/Components/Samples/Charts/Line.razor.cs
src/BootstrapBlazor.Server/Components/Samples/Charts/Line.razor.js
src/BootstrapBlazor/BootstrapBlazor.csproj

doc(Chart): update Chart line type sample code

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Table/ColumnWidth.cs
src/BootstrapBlazor/Components/Table/Table.razor
src/BootstrapBlazor/Components/Table/Table.razor.cs
src/BootstrapBlazor/Components/Table/Table.razor.js

feat(Table): use localstorage keep table column width

---

src/BootstrapBlazor.Server/Components/Samples/Table/TablesColumnResizing.razor
src/BootstrapBlazor.Server/Locales/zh.json
src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Table/Table.razor.cs
src/BootstrapBlazor/Components/Table/Table.razor.js

doc(Table): update sample code

---

src/BootstrapBlazor.Server/Extensions/ServicesExtensions.cs
src/BootstrapBlazor/Extensions/LocalizationOptionsExtensions.cs
src/BootstrapBlazor/Localization/Json/JsonLocalizationOptions.cs
test/UnitTest/Core/BootstrapBlazorTestBase.cs
test/UnitTest/Core/DialogTestBase.cs
test/UnitTest/Core/MessageTestBase.cs
test/UnitTest/Core/PopoverTestBase.cs
test/UnitTest/Core/SwalTestBase.cs
test/UnitTest/Core/TabTestBase.cs
test/UnitTest/Core/TableDialogTestBase.cs
test/UnitTest/Core/TablePopConfirmTestBase.cs
test/UnitTest/Core/TableSortDialogTestBase.cs
test/UnitTest/Core/TableTestBase.cs
test/UnitTest/Core/ValidateFormTestBase.cs
test/UnitTest/Localization/JsonStringLocalizerTest.cs
test/UnitTestDocs/MenuTest.cs

fix(Localizer): can't find json stream when inconsistent namespace and assembly name

---

src/BootstrapBlazor/Components/Select/MultiSelect.razor
src/BootstrapBlazor/Components/Select/Select.razor
src/BootstrapBlazor/Components/Select/SelectBase.cs
test/UnitTest/Components/MultiSelectTest.cs
test/UnitTest/Components/SelectTest.cs

feat(Select): add IsMarkupString parameter

---

src/BootstrapBlazor/Components/Upload/ButtonUpload.razor
src/BootstrapBlazor/Components/Upload/ButtonUpload.razor.cs
src/BootstrapBlazor/Components/Upload/ButtonUploadBase.cs
src/BootstrapBlazor/Components/Upload/CardUpload.razor
src/BootstrapBlazor/Components/Upload/CardUpload.razor.cs
src/BootstrapBlazor/Components/Upload/UploadBase.cs
src/BootstrapBlazor/Components/Upload/UploadBase.razor.scss
src/BootstrapBlazor/Enums/ComponentIcons.cs
src/BootstrapBlazor/Options/IconThemeOptions.cs
src/Extensions/Components/BootstrapBlazor.MaterialDesign.Extensions/DefaultIcon.cs
test/UnitTest/Components/DateTimePickerTest.cs
test/UnitTest/Components/UploadTest.cs

feat(Upload): add OnCancel callback

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Extensions/DirectoryInfoExtensions.cs
test/UnitTest/Extensions/DirectoryInfoExtensionsTest.cs

feat(Utility): add Copy extension method

---

src/BootstrapBlazor.Server/Components/Samples/Sliders.razor
src/BootstrapBlazor.Server/Components/Samples/Sliders.razor.cs
src/BootstrapBlazor.Server/Locales/en.json
src/BootstrapBlazor.Server/Locales/zh.json
src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Slider/Slider.razor.cs
src/BootstrapBlazor/Extensions/FieldIdentifierExtensions.cs
src/BootstrapBlazor/Services/CacheManager.cs
src/BootstrapBlazor/Utils/Utility.cs
test/UnitTest/Components/SliderTest.cs
test/UnitTest/Utils/UtilityTest.cs

feat(Slider): support Range attribute

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Utils/Utility.cs
test/UnitTest/Utils/UtilityTest.cs

fix(Table): render cell missing parameters when readonly

---

exclusion.dic
src/BootstrapBlazor.Server/Components/Samples/Timelines.razor
src/BootstrapBlazor.Server/Locales/en.json
src/BootstrapBlazor.Server/Locales/zh.json
src/BootstrapBlazor/Components/Timeline/Timeline.razor.scss
src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss

refactor(Tag): update sass file use variable

---

src/BootstrapBlazor/Components/Table/Table.razor.Toolbar.cs

fix(Table): wrong TableExportType in ExportCsvAsync method

---

src/BootstrapBlazor.Server/Components/Layout/MainLayout.razor.css
src/BootstrapBlazor.Server/Components/Layout/PracticeLayout.razor.css
src/BootstrapBlazor.Server/Components/Samples/Dispatches.razor
src/BootstrapBlazor/Components/IPLocator/DefaultIPLocator.cs

refactor(IIPLocator): add JsonSerializerOptions Encoder config

---

src/BootstrapBlazor.Server/Components/Samples/Responsives.razor
src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/ResizeNotification/ResizeNotificationService.cs
src/BootstrapBlazor/Components/ResizeNotification/Responsive.cs

fix(Responsive): break point no value at first render

---

src/BootstrapBlazor/Components/Textarea/Textarea.razor.js

fix(Textarea): throw exception when js invoke

---

src/.config/dotnet-tools.json
src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Localization/Json/JsonStringLocalizer.cs
src/BootstrapBlazor/Localization/Json/JsonStringLocalizerFactory.cs
src/BootstrapBlazor/Services/CacheManager.cs

refactor(Localizer): remove MissingLocalizerCache use CacheManager

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Input/BootstrapInput.razor
src/BootstrapBlazor/Components/Input/BootstrapInput.razor.cs
src/BootstrapBlazor/Components/Input/BootstrapInputEventBase.cs
src/BootstrapBlazor/Components/InputNumber/BootstrapInputNumber.razor
src/BootstrapBlazor/Components/InputNumber/BootstrapInputNumberBase.cs
src/BootstrapBlazor/Components/Slider/Slider.razor
src/BootstrapBlazor/Components/Slider/Slider.razor.cs

feat(InputNumber): support oninput event

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/RibbonTab/RibbonTab.razor.scss
src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss

bug(Ribbon): missing menu-bg/menu-color sass variable

---

.editorconfig
src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Calendar/Calendar.razor
src/BootstrapBlazor/Components/Calendar/Calendar.razor.cs
src/BootstrapBlazor/Components/Calendar/Calendar.razor.scss
test/UnitTest/Components/CalendarTest.cs

feat(Calendar): add OnValueChanged callback

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Table/Table.razor.Toolbar.cs

refactor(Table): update PageIndex logic on dynamic datatable mode

---

exclusion.dic
src/BootstrapBlazor/Attributes/JSModuleAutoLoaderAttribute.cs
src/BootstrapBlazor/Components/Select/MultiSelect.razor.cs
src/BootstrapBlazor/Components/Validate/ValidateBase.cs
src/BootstrapBlazor/Utils/BootstrapDynamicComponent.cs
src/BootstrapBlazor/wwwroot/modules/utility.js

This PR refactors the utility module to include batch handling for script and link operations. It adds the functions addScriptBatch, removeScriptBatch, addLinkBatch, and removeLinkBatch, providing the ability to manage multiple scripts and links at once. This enhances the utility module's capabilities and improves code efficiency.
close #2808

feat(Utility): add AddLinkBatch/AddScriptBatch method

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Utils/JSModule.cs

fix(Dispose): catch ObjectDisposed exception

---

src/BootstrapBlazor/Attributes/AutoGenerateColumnAttribute.cs
src/BootstrapBlazor/Components/Display/Display.razor.cs
src/BootstrapBlazor/Components/Table/ITableColumn.cs
src/BootstrapBlazor/Components/Table/InternalTableColumn.cs
src/BootstrapBlazor/Components/Table/TableColumn.cs
src/BootstrapBlazor/Components/Upload/SingleUploadBase.cs
src/BootstrapBlazor/Services/CacheManager.cs
src/BootstrapBlazor/Utils/Utility.cs
test/UnitTest/Misc/MockTableColumn.cs
test/UnitTest/Utils/JSModuleTest.cs
test/UnitTest/Utils/UtilityTest.cs

feat(Formatter): CreateDisplayByFieldType method supports Formatter callback

---

src/BootstrapBlazor/Components/Button/PopConfirmButtonBase.cs
src/BootstrapBlazor/Components/Modal/ModalDialog.razor.cs
src/BootstrapBlazor/Components/Segmented/Segmented.razor.scss
src/BootstrapBlazor/Extensions/DialogServiceExtensions.cs
test/UnitTest/Components/DisplayTest.cs
test/UnitTest/Components/TableTest.cs
test/UnitTest/Extensions/ITableColumnExtensionsTest.cs

feat(Segmented): update style for segmented item

---

src/BootstrapBlazor/Components/Table/Table.razor.js
src/BootstrapBlazor/Utils/Utility.cs

refactor(Table): use ScrollWidth variable replace const 6px

---

src/BootstrapBlazor.Server/Components/Samples/DateTimePickers.razor
src/BootstrapBlazor/Components/ClockPicker/ClockPicker.razor
src/BootstrapBlazor/Components/ClockPicker/ClockPicker.razor.scss
src/BootstrapBlazor/Components/DateTimePicker/DatePickerBody.razor.cs
src/BootstrapBlazor/Components/DateTimePicker/DateTimePicker.razor.cs
src/BootstrapBlazor/Components/DateTimeRange/DateTimeRange.razor.cs
src/BootstrapBlazor/Components/Table/Table.razor.Toolbar.cs
src/BootstrapBlazor/Utils/Utility.cs
test/UnitTest/Components/DateTimePickerTest.cs
test/UnitTest/Components/DateTimeRangeTest.cs
test/UnitTest/Components/TimePickerSettingTest.cs
test/UnitTest/Components/ValidateFormTest.cs

feat(DateTimeRange): support DateTime mode

---

src/BootstrapBlazor/Components/Pagination/Pagination.razor.cs

复现url  https://www.blazor.zone/table/loading 
发现 分页组件有点 问题，具体为 ：
假设 每页5条数据，当 到第5页时会出现 ...  ，点击这个 ... 会跳转到 最后一页，同理 下一页的 ...也会出现； 这时应该 为  上一页 为  1，同理 下一页为 最后一页即  InternalPageCount，
close #2976

fix(Pagination): incorrect pagination jump

---

src/BootstrapBlazor.Server/Components/Samples/SelectTrees.razor
src/BootstrapBlazor.Server/Components/Samples/Selects.razor
src/BootstrapBlazor.Server/Locales/en-US.json
src/BootstrapBlazor.Server/Locales/zh-CN.json
src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Select/ISelect.cs
src/BootstrapBlazor/Components/Select/Select.razor
src/BootstrapBlazor/Components/Select/Select.razor.cs
src/BootstrapBlazor/Components/Select/SelectTree.razor
src/BootstrapBlazor/Components/Select/SelectTree.razor.cs
src/BootstrapBlazor/Components/TreeView/TreeView.razor.cs
test/UnitTest/Components/SelectTest.cs
test/UnitTest/Components/SelectTreeTest.cs

feat(Select): add IsEditable parameter

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Select/Select.razor.cs
test/UnitTest/Components/SelectTest.cs

feat(Select): add OnInputChangedCallback parameter

---

src/BootstrapBlazor.Server/Components/Samples/InputNumbers.razor
src/BootstrapBlazor.Server/Components/Samples/InputNumbers.razor.cs
src/BootstrapBlazor.Server/Locales/en-US.json
src/BootstrapBlazor.Server/Locales/zh-CN.json
src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Input/BootstrapInput.razor.js
src/BootstrapBlazor/Components/InputNumber/BootstrapInputNumber.razor.cs
src/BootstrapBlazor/Components/Validate/ValidateBase.cs
test/UnitTest/Components/InputNumberTest.cs

fix(InputNumber): input illegal value not cleared

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/SweetAlert/SwalOption.cs
src/BootstrapBlazor/Components/SweetAlert/SweetAlert.razor.cs
src/BootstrapBlazor/Components/SweetAlert/SweetContext.cs
src/BootstrapBlazor/Extensions/SwalExtensions.cs

feat(SweetAlert): eliminating latency between call show method twice

---

src/BootstrapBlazor/Attributes/AutoGenerateColumnAttribute.cs
src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Utils/Utility.cs
test/UnitTest/Attributes/AutoGenerateClassTest.cs

fix(Table): keep client column width not work when set AutoGenerateColumns to true

---

src/BootstrapBlazor/Attributes/TableMetadataForAttribute.cs
src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Input/BootstrapInputEventBase.cs
src/BootstrapBlazor/Components/InputNumber/BootstrapInputNumber.razor
src/BootstrapBlazor/Components/InputNumber/BootstrapInputNumber.razor.cs
test/UnitTest/Components/InputNumberTest.cs

fix(InputNumber): can't input 0.0 when set UseInputEvent to true

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/DateTimePicker/DatePickerBody.razor
src/BootstrapBlazor/Components/DateTimePicker/DatePickerBody.razor.cs
src/BootstrapBlazor/Components/DateTimePicker/DatePickerCell.razor.cs
src/BootstrapBlazor/Components/DateTimePicker/DateTimePicker.razor
src/BootstrapBlazor/Components/DateTimePicker/DateTimePicker.razor.cs
src/BootstrapBlazor/Extensions/DateTimeExtensions.cs
test/UnitTest/Components/DateTimePickerTest.cs
test/UnitTest/Components/LayoutTest.cs

feat(DateTimePicker): add ShowSolarTerm parameter

---

BootstrapBlazor.sln
src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj
src/Extensions/Components/BootstrapBlazor.Holiday/BootstrapBlazor.Holiday.csproj

feat(Holiday): add BootstrapBlazor.Holiday package

---

src/BootstrapBlazor/Components/IpAddress/IpAddress.razor.js

feat(IpAddress): add support for handling both keyboard and numpad input for numeric values

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Select/MultiSelect.razor.cs

fix(MultiSelect): selected value incorrect when use daynamic create

---

src/BootstrapBlazor.Server/Components/Samples/FullScreens.razor
src/BootstrapBlazor.Server/Locales/en-US.json
src/BootstrapBlazor.Server/Locales/zh-CN.json
src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/FullScreen/FullScreen.razor.scss
src/BootstrapBlazor/Components/FullScreen/FullScreenButton.razor
src/BootstrapBlazor/Components/FullScreen/FullScreenButton.razor.cs
src/BootstrapBlazor/wwwroot/modules/fullscreen.js
test/UnitTest/Components/FullScreenTest.cs

fix(FullScreenButton): show tow icons when set FullScreenIcon

---

src/BootstrapBlazor.Server/Components/Samples/TreeViews.razor
src/BootstrapBlazor.Server/Components/Samples/TreeViews.razor.cs
src/BootstrapBlazor.Server/Locales/en-US.json
src/BootstrapBlazor.Server/Locales/zh-CN.json
src/BootstrapBlazor/Components/TreeView/TreeView.razor
src/BootstrapBlazor/Components/TreeView/TreeView.razor.cs
test/UnitTest/Components/TreeViewTest.cs

feat(TreeView): add SearchTemplate parameter

---

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj
src/BootstrapBlazor.Server/Components/Samples/TreeViews.razor
src/BootstrapBlazor.Server/Components/Samples/TreeViews.razor.cs
src/BootstrapBlazor.Server/Data/TreeFoo.cs
src/BootstrapBlazor.Server/Locales/en-US.json
src/BootstrapBlazor.Server/Locales/zh-CN.json
src/BootstrapBlazor/Components/TreeView/TreeView.razor
src/BootstrapBlazor/Components/TreeView/TreeView.razor.cs
src/BootstrapBlazor/Misc/ExpandableNodeCache.cs
test/UnitTest/Components/TreeViewTest.cs
test/UnitTest/Misc/TreeNodeCacheTest.cs

1、移除 ExpandableNodeCache.ToggleNodeAsync() 中展开节点始终对子节点 CheckedState的赋值；
2、将 TreeView 节点的选择框 CheckBox 选中状态改用 @bind-State 进行双重绑定，而非手动赋值；
3、在 TreeView 切换节点展开状态时，加入节点状态更新事件检查 OnCheckStateChanged();
5、添加测试案例。

fix(TreeView): AutoCheckChildren not work use OnExpandNodeAsync load children

---

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj
src/BootstrapBlazor.Server/Components/Samples/DockViews/DockViewLayout.razor.css
src/BootstrapBlazor.Server/Properties/launchSettings.json
src/BootstrapBlazor/Localization/Json/JsonStringLocalizer.cs
src/Extensions/Components/BootstrapBlazor.Dock/BootstrapBlazor.Dock.csproj
src/Extensions/Components/BootstrapBlazor.Dock/Components/DockView/DockComponent.cs
test/UnitTest/UnitTest.csproj

refactor(DockView): missing ComponentName parameter

---

src/BootstrapBlazor.Server/Components/Samples/Selects.razor
src/BootstrapBlazor/Components/Select/Select.razor.cs
test/UnitTest/Components/SelectTest.cs

```csharp
private void OnClearValue()
{
if (ShowSearch)
{
ClearSearchText();
}
CurrentValue = default;
}
```
close #3339

feat(Select): Clear search text while clearing text content

---

src/BootstrapBlazor.Server/Components/Samples/ExportPdfButtons.razor
src/BootstrapBlazor.Server/Components/Samples/ExportPdfButtons.razor.cs
src/BootstrapBlazor.Server/Locales/en-US.json
src/BootstrapBlazor.Server/Locales/zh-CN.json
src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Button/Button.razor.js
src/BootstrapBlazor/Components/Button/ExportPdfButton.cs
src/BootstrapBlazor/Components/Button/ExportPdfButtonSettings.cs
src/BootstrapBlazor/Components/EditorForm/EditorItem.cs
src/BootstrapBlazor/Components/EditorForm/IEditorItem.cs
src/BootstrapBlazor/Components/Modal/ModalDialog.razor
src/BootstrapBlazor/Components/Table/TableColumn.cs
src/BootstrapBlazor/Options/ExportPdfButtonOptions.cs
test/UnitTest/Components/ExportPdfButtonTest.cs
test/UnitTest/Extensions/AssemblyExtensionsTest.cs
test/UnitTest/Utils/UnsafeAccessorTest.cs

feat(ExportPdfButton): add ExportPdfSettings component

---

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj
src/Extensions/Components/BootstrapBlazor.Chart/BootstrapBlazor.Chart.csproj
src/Extensions/Components/BootstrapBlazor.Chart/Components/Chart/Chart.razor.js
src/Extensions/Components/BootstrapBlazor.Chart/Components/Chart/ChartOptions.cs

Added a new plugin named `customCanvasBackgroundColor` to `Chart.razor.js` that allows setting a custom background color for the chart canvas. The `chartOption` object and `getChartOption` function were updated to include this new plugin. Also, a new property `CanvasBackgroundColor` was added to the `ChartOptions` class in `ChartOptions.cs` to get or set the background color of the chart canvas.
close #3457

feat(Chart): Add a CanvasBackgroundColor parameter

---

src/BootstrapBlazor.Server/Data/TreeFoo.cs
src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Button/Button.razor.js
src/BootstrapBlazor/Components/Button/ShareButton.cs
src/BootstrapBlazor/Components/TreeView/TreeView.razor.cs
src/BootstrapBlazor/Extensions/ExpandableNodeExtensions.cs
src/BootstrapBlazor/Misc/TreeNodeCache.cs
test/UnitTest/Components/ButtonTest.cs
test/UnitTest/Components/TreeViewTest.cs

fix(TreeView): all children node state is Indeterminate after expand node

---

src/BootstrapBlazor.Server/appsettings.json
src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Options/BootstrapBlazorOptions.cs
src/BootstrapBlazor/Options/WebClientOptions.cs
src/BootstrapBlazor/Services/WebClientService.cs
test/UnitTest/Services/WebClientServiceTest.cs

feat(WebClientOptions): add WebClientOptions class

---

src/BootstrapBlazor/Components/Table/Table.razor.cs

perf(Table): skip call client column info when not set ClientTableName

---

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj

BootstrapBlazor.FileViewer v8.0.3
- 修复 [依赖包日期格式转换错误](https://github.com/densen2014/BootstrapBlazor.FileViewer/issues/4)
- 修复 [组件依赖](https://github.com/densen2014/BootstrapBlazor.FileViewer/issues/2)
close #3534

feat(FileViewer): bump BootstrapBlazor.FileViewer version to v8.0.3

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Table/Table.razor
src/BootstrapBlazor/Components/Table/Table.razor.cs
test/UnitTest/Components/TableTest.cs

Add LoadingTemplate support
close #3537

feat(Table): Add LoadingTemplate support

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Table/Table.razor
src/BootstrapBlazor/Components/Table/TableFooterCell.razor
src/BootstrapBlazor/Components/Table/TableFooterCell.razor.cs
test/UnitTest/Components/TableFooterCellTest.cs
test/UnitTest/Services/MaskServiceTest.cs

feat(TableFooterCell): add BreakPoint parameter

---

src/BootstrapBlazor/Components/Filters/TableFilter.razor.cs
src/BootstrapBlazor/Components/Table/Table.razor.cs
src/BootstrapBlazor/Components/Table/Table.razor.js
src/BootstrapBlazor/Components/Table/Table.razor.scss
src/BootstrapBlazor/Components/Table/TableFooterCell.razor.cs

fix(Table): auto scroll top click Filter button in use virtual mode

---

src/BootstrapBlazor/Components/Upload/CardUpload.razor.cs
src/BootstrapBlazor/Extensions/IEditorItemExtensions.cs

feat(CardUpload): add CanPreviewCallback parameter

---

src/BootstrapBlazor/Components/Button/PopConfirmButton.razor
src/BootstrapBlazor/Components/Button/PopConfirmButtonBase.cs
src/BootstrapBlazor/Components/Button/PopConfirmButtonContent.razor
src/BootstrapBlazor/Components/Button/PopConfirmButtonContent.razor.cs
test/UnitTest/Components/PopConfirmButtonTest.cs

feat(PopConfirmButton): add OnCloseAsync/OnConfirmAsync cascade parameter

---

src/BootstrapBlazor.Server/Locales/en-US.json
src/BootstrapBlazor.Server/Locales/zh-CN.json
src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Table/Table.razor.cs

feat(Table): set ShowColumnWidthTooltip default value to false

---

src/BootstrapBlazor.Server/Components/Pages/GlobalOption.razor
src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Options/BootstrapBlazorOptions.cs
src/BootstrapBlazor/Options/ConnectionHubOptions.cs
src/BootstrapBlazor/Services/IPLocator/IpLocatorOptions.cs

doc(GlobalOptions): update documentation for global options

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Print/PrintButton.razor.js

fix(Print): support textarea html element

---

src/Extensions/Components/BootstrapBlazor.DockView/BootstrapBlazor.DockView.csproj
src/Extensions/Components/BootstrapBlazor.DockView/wwwroot/js/dockview-config.js
src/Extensions/Components/BootstrapBlazor.DockView/wwwroot/js/dockview-group.js
src/Extensions/Components/BootstrapBlazor.DockView/wwwroot/js/dockview-panel.js
src/Extensions/Components/BootstrapBlazor.DockView/wwwroot/js/dockview-utils.js

feat(DockView): keep IsFloating panel position

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Table/TableToolbar.razor.cs
test/UnitTest/Components/TableTest.cs

feat(TableToolbarButton): support OnClickWithoutRender callback

---

src/Extensions/Components/BootstrapBlazor.DockView/BootstrapBlazor.DockView.csproj
src/Extensions/Components/BootstrapBlazor.DockView/wwwroot/js/dockview-panel.js

refactor(DockViewV2): move component back into template when group removed

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Table/Table.razor
src/BootstrapBlazor/Components/Table/Table.razor.js

fix(Table): DisableExtendEdit/DeleteButtonCallback not work on CardView mode

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Table/Table.razor.js

fix(Table): calc table height incorrect when invisible at first render

---

src/BootstrapBlazor/Components/Layout/Layout.razor.cs

can't collapse side when set side with value
close #3981

fix(Layout): can't collapse side when set side with value

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Table/Table.razor.js

fix(Table): throw exception when resize window on enable detail and fix header

---

src/BootstrapBlazor.Server/Components/Samples/Table/TablesEdit.razor.cs
src/BootstrapBlazor.Server/Services/TableDemoDataService.cs
src/BootstrapBlazor/Components/Table/Table.razor
src/BootstrapBlazor/Components/Table/Table.razor.Edit.cs
src/BootstrapBlazor/Components/Table/Table.razor.Search.cs
src/BootstrapBlazor/Components/Table/Table.razor.cs
src/BootstrapBlazor/Services/DataServiceBase.cs
src/BootstrapBlazor/Services/IDataService.cs
src/BootstrapBlazor/Utils/Utility.cs
src/Extensions/DataServices/BootstrapBlazor.DataAccess.EntityFrameworkCore/DefaultDataService.cs
src/Extensions/DataServices/BootstrapBlazor.DataAccess.FreeSql/DefaultDataService.cs
src/Extensions/DataServices/BootstrapBlazor.DataAccess.PetaPoco/DefaultDataService.cs
src/Extensions/DataServices/BootstrapBlazor.DataAccess.SqlSugar/DefaultDataService.cs
src/maui/BootstrapBlazor.Maui/Data/TableDemoDataServiceCollectionExtensions.cs
test/UnitTest/Components/TableTest.cs
test/UnitTest/Core/TableDialogTestBase.cs
test/UnitTest/Core/TableDrawerTestBase.cs
test/UnitTest/Services/DataServiceTest.cs

feat(Table): add CreateTItemCallback to support required modifier

---

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj
src/BootstrapBlazor.Server/Components/Components/FooSortableListItem.razor.css
src/BootstrapBlazor.Server/Components/Samples/SortableLists.razor
src/BootstrapBlazor.Server/Components/Samples/SortableLists.razor.cs
src/BootstrapBlazor.Server/Locales/en-US.json
src/BootstrapBlazor.Server/Locales/zh-CN.json
src/Extensions/Components/BootstrapBlazor.Chart/BootstrapBlazor.Chart.csproj
src/Extensions/Components/BootstrapBlazor.Sortable/BootstrapBlazor.Sortable.csproj
src/Extensions/Components/BootstrapBlazor.Sortable/Components/SortableList.razor.js
src/Extensions/Components/BootstrapBlazor.Sortable/Components/SortableOption.cs
src/Extensions/Components/BootstrapBlazor.Sortable/wwwroot/sortable.esm.js

doc(Chart): revert Stack parameter

---

src/BootstrapBlazor.Server/Components/Samples/ContextMenus.razor
src/BootstrapBlazor.Server/Components/Samples/ContextMenus.razor.cs
src/BootstrapBlazor.Server/Locales/en-US.json
src/BootstrapBlazor.Server/Locales/zh-CN.json
src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/ContextMenu/ContextMenu.razor
src/BootstrapBlazor/Components/ContextMenu/ContextMenu.razor.cs
src/BootstrapBlazor/Components/ContextMenu/ContextMenuItem.cs
src/BootstrapBlazor/Components/ContextMenu/ContextMenuItem.razor
src/BootstrapBlazor/Components/ContextMenu/ContextMenuItem.razor.cs
src/BootstrapBlazor/Components/ContextMenu/ContextMenuZone.razor.cs
test/UnitTest/Components/ContextMenuTest.cs

I would like to propose a new feature for the `ContextMenu` component: an `OnClickBefore` callback event. This event should be triggered right before the context menu is displayed when the user right-clicks. It would allow developers to perform actions or checks before the menu is rendered to the user.
The `OnClickBefore` event would be extremely useful for dynamic context menu content, where menu items need to be determined based on the state of the application or specific conditions at the time of the right-click. For example, it could be used to enable or disable menu items, add new ones, or even cancel the display of the context menu altogether based on certain criteria.
```csharp
[Parameter]
public Func<object?, Task>? OnClickBefore { get; set; }
```
close #4111

feat(ContextMenu): Add OnClickBefore callback event

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/BaseComponents/BootstrapBlazorRoot.razor
src/BootstrapBlazor/Components/BaseComponents/BootstrapBlazorRoot.razor.cs
src/BootstrapBlazor/Services/IRootComponentGenerator.cs

feat(IRootComponentGenerator): add IRootComponentGenerator interface

---

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj
src/BootstrapBlazor.Server/Components/Components/CustomWinBoxContent.razor
src/Extensions/Components/BootstrapBlazor.WinBox/BootstrapBlazor.WinBox.csproj
src/Extensions/Components/BootstrapBlazor.WinBox/WinBox.razor.cs

WinBox 关闭时刷新组件，以及时触发子组件释放流程
close #4168

fix(WinBox): dispose ChildContent component

---

src/BootstrapBlazor.Server/Components/Samples/Splits.razor.cs
src/BootstrapBlazor.Server/Locales/en-US.json
src/BootstrapBlazor.Server/Locales/zh-CN.json
src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Split/Split.razor.cs
src/BootstrapBlazor/Components/Split/Split.razor.js
src/BootstrapBlazor/Components/Split/Split.razor.scss
test/UnitTest/Components/SplitTest.cs

support return to the original separation position
close #4166

feat(split): add IsKeepOriginalSize parameter

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Table/Table.razor.Edit.cs
test/UnitTest/Components/TableTest.cs

bug(Table): selected row callback causes infinite loop

---

src/BootstrapBlazor.Server/Components/Samples/JSRuntimeExtensions.razor.cs
src/BootstrapBlazor/Components/WebSpeech/Synthesizer/WebSpeechSynthesizer.cs
src/BootstrapBlazor/Extensions/JSModuleExtensions.cs
src/BootstrapBlazor/Utils/JSModule.cs
test/UnitTest/Extensions/JSModuleExtensionsTest.cs
test/UnitTest/Services/WebSpeechSynthesizerTest.cs
test/UnitTest/Utils/JSModuleTest.cs

feat(JSModule): redesign JSModule support null js object

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/ColorPicker/ColorPicker.razor.cs
src/BootstrapBlazor/Components/ColorPicker/ColorPicker.razor.js

feat(ColorPicker): add localizer parameter

---

exclusion.dic
src/BootstrapBlazor/Components/Validate/ValidateBase.cs
src/BootstrapBlazor/Locales/en.json
src/BootstrapBlazor/Locales/zh.json
src/BootstrapBlazor/Validators/FormItemValidator.cs
src/BootstrapBlazor/Validators/RequiredValidator.cs
test/UnitTest/Components/ValidateFormTest.cs
test/UnitTest/Validators/RequiredValidatorTest.cs

feat(RequiredValidator): enhance the RequiredValidator class

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Select/Select.razor.cs
test/UnitTest/Components/SelectTest.cs

fix(Select): not trigger OnSelectedItemChanged when click clear icon

---

src/BootstrapBlazor.Server/Components/Samples/Selects.razor
src/BootstrapBlazor.Server/Components/Samples/Selects.razor.cs
src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Select/Select.razor
src/BootstrapBlazor/Components/Select/Select.razor.cs
test/UnitTest/Components/SelectTest.cs

bug(Select): not show full item after click Clear button

---

src/Extensions/DataServices/BootstrapBlazor.DataAccess.FreeSql/BootstrapBlazor.DataAccess.FreeSql.csproj
src/Extensions/DataServices/BootstrapBlazor.DataAccess.FreeSql/FreeSqlExtensions.cs

通过增加 `FreeSqlExtensions.ToDynamicFilter` 扩展方法参数，支持 `FilterAction.CustomPredicate` 自定义过滤值的支持。
close #4295

feat(FreeSqlExtensions): support CustomPredicate custom convert

---

src/BootstrapBlazor/Components/AutoFill/AutoFill.razor.cs
test/UnitTest/Components/AutoFillTest.cs

fix(AutoFill): should not trigger OnCustomFilter callback when ArrowUp/Down/Esc/Enter key up

---

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj
src/BootstrapBlazor.Server/Components/Samples/SortableLists.razor
src/BootstrapBlazor.Server/Components/Samples/SortableLists.razor.cs
src/BootstrapBlazor.Server/Locales/en-US.json
src/BootstrapBlazor.Server/Locales/zh-CN.json

feat(SortableList): add OnAdd parameter

---

src/BootstrapBlazor/Components/Drawer/Drawer.razor.js
src/BootstrapBlazor/Components/TreeView/TreeView.razor.cs
src/BootstrapBlazor/Components/TreeView/TreeView.razor.js
src/BootstrapBlazor/Options/ScrollIntoViewOptions.cs
test/UnitTest/Components/TreeViewTest.cs
test/UnitTest/Options/ScrollIntoViewOptionsTest.cs

feat(TreeView): add ScrollIntoViewOptions parameter

---

src/BootstrapBlazor.Server/Components/Samples/ValidateForms.razor.cs
src/BootstrapBlazor.Server/Data/CustomValidateCollectionModel.cs
src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Validate/IValidateCollection.cs
src/BootstrapBlazor/Components/Validate/ValidateBase.cs
src/BootstrapBlazor/Components/ValidateForm/ValidateForm.razor.cs
test/UnitTest/Components/ValidateFormTest.cs

fix(ValidateForm): validate all validation from MetadataType

---

src/BootstrapBlazor/Components/Table/Table.razor.scss
src/BootstrapBlazor/Components/Table/TableToolbar.razor
src/BootstrapBlazor/Components/Table/TableToolbar.razor.cs
test/UnitTest/Components/ValidateFormTest.cs

fix(Table): IsDisabled parameter not work in Toolbar on gear mode

---

src/BootstrapBlazor/Components/DateTimeRange/DateTimeRange.razor
src/BootstrapBlazor/Components/DateTimeRange/DateTimeRange.razor.cs

Selecting end date panel on the single view mode to match the actual date passed as parameter.
{Detail}
Fixes: #4358
[是否影响老版本]

fix(DateTimePicker): body defaulting to current month

---

src/BootstrapBlazor/Components/DateTimePicker/DatePickerBody.razor.cs
test/UnitTest/Components/DateTimePickerTest.cs

perf(DateTimePicker): update cache when click year button

---

src/BootstrapBlazor/Components/Validate/ValidateBase.cs
src/BootstrapBlazor/Components/ValidateForm/ValidateForm.razor.cs
src/BootstrapBlazor/Components/ValidateForm/ValidateForm.razor.js
test/UnitTest/Components/ValidateFormTest.cs

perf(ValidateForm): support validate multiple validate form 

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Table/Table.razor.Edit.cs
src/BootstrapBlazor/Components/Table/Table.razor.Search.cs
src/BootstrapBlazor/Components/Table/Table.razor.cs
src/BootstrapBlazor/Components/ValidateForm/ValidateForm.razor.cs
src/BootstrapBlazor/Extensions/TypeExtensions.cs
src/BootstrapBlazor/Services/CacheManager.cs
src/BootstrapBlazor/Utils/Utility.cs
test/UnitTest/Components/TableTest.cs
test/UnitTest/Extensions/IQueryableExtensionsTest.cs
test/UnitTest/Extensions/LambadaExtensionsTest.cs
test/UnitTest/Extensions/ObjectExtensionsTest.cs
test/UnitTest/Extensions/QueryPageOptionsExtensionsTest.cs
test/UnitTest/Performance/ReflectionTest.cs

feat(Table): add CreateSearchModelCallback parameter

---

src/BootstrapBlazor.Server/Components/Components/Pre.razor.cs
src/BootstrapBlazor.Server/Components/Samples/Icons/BootstrapIcons.razor
src/BootstrapBlazor.Server/Components/Samples/Icons/MaterialDesignIcons.razor
src/BootstrapBlazor.Server/Locales/en-US.json
src/BootstrapBlazor.Server/Locales/zh-CN.json
src/BootstrapBlazor.Server/Services/PackageVersionService.cs

doc(Icon): update css refer documentation

---

src/BootstrapBlazor.Server/Components/App.razor
src/BootstrapBlazor.Server/Components/Components/Header.razor.cs
src/BootstrapBlazor.Server/Controllers/Api/LoginController.cs
src/BootstrapBlazor/Components/ThemeProvider/ThemeProvider.razor.cs
src/BootstrapBlazor/Components/ThemeProvider/ThemeProvider.razor.js
src/BootstrapBlazor/Components/ThemeProvider/ThemeValue.cs
src/BootstrapBlazor/Converter/JsonEnumConverter.cs
src/BootstrapBlazor/wwwroot/modules/utility.js
test/UnitTest/Components/ThemeProviderTest.cs

fixes #4399 
- [*] No
[是否影响老版本]
是
- [*] Low
- [*] Manual (required)

feat(ThemeProvider): support auto mode

---

src/BootstrapBlazor.Server/Components/Samples/Table/Tables.razor.cs
src/BootstrapBlazor.Server/Locales/en-US.json
src/BootstrapBlazor.Server/Locales/zh-CN.json
src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Table/Table.razor.Checkbox.cs
src/BootstrapBlazor/Components/Table/Table.razor.Edit.cs
src/BootstrapBlazor/Components/Table/Table.razor.Toolbar.cs
test/UnitTest/Components/TableTest.cs

feat(Table): IsKeepSelectedRows effect in add method

---

src/BootstrapBlazor.Server/Components/Samples/DropdownWidgets.razor
src/BootstrapBlazor.Server/Components/Samples/DropdownWidgets.razor.cs
src/BootstrapBlazor.Server/Locales/en-US.json
src/BootstrapBlazor.Server/Locales/zh-CN.json
src/BootstrapBlazor.Server/Properties/launchSettings.json
src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/DropdownWidget/DropdownWidget.razor
src/BootstrapBlazor/Components/DropdownWidget/DropdownWidget.razor.cs
src/BootstrapBlazor/Components/DropdownWidget/DropdownWidget.razor.js
test/UnitTest/Components/DropdownWidgetTest.cs

feat(DropdownWidget): add OnItemShown/CloseAsync parameter

---

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj
src/BootstrapBlazor.Server/Components/Samples/ImageCroppers.razor
src/BootstrapBlazor.Server/Components/Samples/ImageCroppers.razor.cs
src/BootstrapBlazor.Server/Locales/en-US.json
src/BootstrapBlazor.Server/Locales/zh-CN.json
src/BootstrapBlazor/Extensions/JSModuleExtensions.cs
test/UnitTest/Extensions/JSModuleExtensionsTest.cs

doc(ImageCropper): add round image sample code

---

src/BootstrapBlazor/Components/HtmlTag/Link.razor
src/BootstrapBlazor/Components/HtmlTag/Link.razor.cs
test/UnitTest/Components/LinkTest.cs

feat(Link): add Rel parameter #4437

---

src/BootstrapBlazor.Server/Components/Components/CultureChooser.razor.cs
src/BootstrapBlazor.Server/Components/Layout/HomeLayout.razor.cs
src/BootstrapBlazor.Server/Components/Pages/Localization.razor

fixes #4436 
fixes #4444
[是否影响老版本]

doc(UriFormat): use SafeUnescaped instead of Unescaped

---

src/BootstrapBlazor/Components/Layout/Layout.razor
src/BootstrapBlazor/Components/Layout/Layout.razor.cs
test/UnitTest/Components/LayoutTest.cs

feat(Layout): add ShowTabItemClose parameter

---

src/BootstrapBlazor.Server/Extensions/CacheManagerExtensions.cs
src/BootstrapBlazor.Server/Services/CodeSnippetService.cs
src/BootstrapBlazor/Components/ValidateForm/ValidateForm.razor.cs
src/BootstrapBlazor/Enums/TransitionType.cs
src/BootstrapBlazor/Extensions/BootstrapBlazorServiceCollectionExtensions.cs
src/BootstrapBlazor/Extensions/LocalizationOptionsExtensions.cs
src/BootstrapBlazor/Localization/ILocalizationMissingItemHandler.cs
src/BootstrapBlazor/Localization/ILocalizationResolve.cs
src/BootstrapBlazor/Localization/Json/JsonLocalizationOptions.cs
src/BootstrapBlazor/Localization/Json/JsonLocalizationServiceCollectionExtensions.cs
src/BootstrapBlazor/Localization/Json/JsonStringLocalizer.cs
src/BootstrapBlazor/Localization/Json/JsonStringLocalizerFactory.cs
src/BootstrapBlazor/Localization/Json/StringLocalizer.cs
src/BootstrapBlazor/Localization/NullLocalizationMissingItemHandler.cs
src/BootstrapBlazor/Localization/NullLocalizationResolve.cs
src/BootstrapBlazor/Options/BootstrapBlazorOptions.cs
src/BootstrapBlazor/Services/CacheManager.cs
src/BootstrapBlazor/Utils/Utility.cs
src/BootstrapBlazor/Validators/RequiredValidator.cs
test/UnitTest/Localization/JsonStringLocalizerTest.cs
test/UnitTest/Utils/UtilityTest.cs
test/UnitTest/Validators/RequiredValidatorTest.cs

refactor(Localizer): update Localization namesapce

---

src/BootstrapBlazor/Converter/JsonEnumConverter.cs

refactor(JsonEnumConverter): update namespace

---

src/BootstrapBlazor.Server/Components/Components/Pre.razor.js
src/BootstrapBlazor/Services/Serial/DefaultSerialService.cs
test/UnitTest/Services/SerialServiceTest.cs

doc(Pre): add ignoreUnescapedHTML config

---

src/BootstrapBlazor.Server/Components/Samples/Bluetooth.razor
src/BootstrapBlazor.Server/Components/Samples/Bluetooth.razor.cs
src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Services/Bluetooth/BluetoothFilter.cs
src/BootstrapBlazor/Services/Bluetooth/BluetoothManufacturerDataFilter.cs
src/BootstrapBlazor/Services/Bluetooth/BluetoothRequestOptions.cs
src/BootstrapBlazor/Services/Bluetooth/BluetoothServiceDataFilter.cs
src/BootstrapBlazor/Services/Bluetooth/DefaultBluetoothService.cs
src/BootstrapBlazor/Services/Bluetooth/IBluetoothService.cs
src/BootstrapBlazor/wwwroot/modules/bt.js
test/UnitTest/Services/BluetoothServiceTest.cs

feat(IBluetoothService): add BluetoothFilterOption parameter

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Drawer/Drawer.razor
src/BootstrapBlazor/Components/Drawer/Drawer.razor.cs
src/BootstrapBlazor/Components/Drawer/DrawerContainer.cs
src/BootstrapBlazor/Components/Drawer/DrawerOption.cs
test/UnitTest/Components/DrawerTest.cs
test/UnitTest/Services/DrawerServiceTest.cs

feat(DrawerOption): add BodyContext parameter

---

src/BootstrapBlazor.Server/Components/Samples/Dropdowns.razor
src/BootstrapBlazor.Server/Locales/en-US.json
src/BootstrapBlazor.Server/Locales/zh-CN.json

doc(Dropdown): custom content use ButtonTemplate

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Table/Table.razor.Edit.cs
src/BootstrapBlazor/Extensions/ObjectExtensions.cs
test/UnitTest/Components/TableTest.cs
test/UnitTest/Extensions/ObjectExtensionsTest.cs

[请在下方 # 后面填写相关 Issue 编号，如 #42]
fixes #5529 
This pull request includes several changes to the `BootstrapBlazor` project, focusing on version updates, enhancements to model property initialization, and improvements to unit tests. The most important changes include updating the project version, adding a new parameter for automatic model property initialization, and modifying the `CreateInstance` method to support this new parameter.
* [`src/BootstrapBlazor/BootstrapBlazor.csproj`](diffhunk://#diff-07918ce1b66955e76da5cd0ffa38512cce984fa2a09735a60e0db37b45235527L4-R4): Updated the project version from 9.4.5 to 9.4.6.
* [`src/BootstrapBlazor/Components/Table/Table.razor.Edit.cs`](diffhunk://#diff-f110e93a49468f41a886de0ccf4717f076d9f74aa3f2aab9c827d52d38d6f7d8R297-R318): Added a new parameter …

fix(Table): add IsAutoInitializeModelProperty parameter control create instance logic

---

src/BootstrapBlazor.Server/Components/Components/Header.razor
src/BootstrapBlazor.Server/Components/Layout/TutorialsNavMenu.razor.cs
src/BootstrapBlazor.Server/Components/Samples/Tutorials/Memorial.razor
src/BootstrapBlazor.Server/Components/Samples/Tutorials/Memorial.razor.cs
src/BootstrapBlazor.Server/Locales/en-US.json
src/BootstrapBlazor.Server/Locales/zh-CN.json
src/BootstrapBlazor/Extensions/JSModuleExtensions.cs
src/BootstrapBlazor/Options/BootstrapBlazorOptions.cs
src/BootstrapBlazor/wwwroot/modules/utility.js
src/BootstrapBlazor/wwwroot/scss/meilisearch.scss
src/BootstrapBlazor/wwwroot/scss/root.scss
test/UnitTest/Utils/JSModuleTest.cs

fixes #5583 
This pull request introduces a new "Memorial Mode" feature and includes several localization improvements and code documentation updates. The most important changes are summarized below:
* [`src/BootstrapBlazor.Server/Components/Samples/Tutorials/Memorial.razor`](diffhunk://#diff-307851ae102674f9c8e92fa73a9358a02f6c3242d3b35943d1ffa54ec310848aR1-R13): Added a new page for the Memorial Mode tutorial.
* [`src/BootstrapBlazor.Server/Components/Samples/Tutorials/Memorial.razor.cs`](diffhunk://#diff-5f18a5ee0c55a8c7c3f462b3eb15bf250b8487e1e2f3a613742dc71842780f32R1-R27): Implemented the Memorial Mode functionality with a toggle button to switch the mode on and off.
* [`src/BootstrapBlazor/Extensions/JSModuleExtensions.cs`](diffhunk://#diff-218f46f7d159714ea70736eaafbaecea821616f180 …

feat(Memorial): add Memorial Mode

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Input/BootstrapInput.razor.js
src/BootstrapBlazor/Components/Input/BootstrapInputBase.cs
src/BootstrapBlazor/Components/Textarea/Textarea.razor.cs

fixes #5610
fixes #5609   
This pull request includes several changes to the `BootstrapBlazor` components, focusing on improving the code readability by translating comments from Chinese to English and adding new functionality to handle `Shift + Enter` key presses in the input components.
* [`src/BootstrapBlazor/Components/Input/BootstrapInput.razor.js`](diffhunk://#diff-d525520cd4bee175ef30a217808bdf8b05ce2f85102b6bacd4522081862df5a1R15-R18): Added logic to handle `Shift + Enter` key presses, preventing the default action if `Shift` is held and `data-bb-shift-enter` attribute is set to true.
* [`src/BootstrapBlazor/Components/Input/BootstrapInputBase.cs`](diffhunk://#diff-c8b39f196c17a2c5974695ce681c8f18630ca1134c3fba29b4a3324f0205698bL9-R88): Translated all comments from Chinese to …

fix(Textarea): adding new functionality to handle Shift + Enter

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/AutoComplete/AutoComplete.razor.js

fixes #5815 
This pull request includes updates to the version number in the project file and modifications to the `AutoComplete` component's JavaScript file to improve event handling.
Version update:
* [`src/BootstrapBlazor/BootstrapBlazor.csproj`](diffhunk://#diff-07918ce1b66955e76da5cd0ffa38512cce984fa2a09735a60e0db37b45235527L4-R4): Updated the project version from `9.5.6-beta03` to `9.5.6-beta04`.
Event handling improvements in `AutoComplete` component:
* [`src/BootstrapBlazor/Components/AutoComplete/AutoComplete.razor.js`](diffhunk://#diff-6e1f08721d40e940db1bd318cba31cf6cb4ea87287c9d6e263b005912b473bb8L44-R51): Modified the `handlerKeydown` function to accept `ac` (AutoComplete instance) as a parameter and updated the event handler calls to pass `ac` along with the event object. …

fix(AutoComplete): tabbing off AutoComplete field does not close its drop down 

---

src/BootstrapBlazor/Components/AutoComplete/AutoComplete.razor.js

fixes #5832 
This pull request includes changes to the `AutoComplete` component in the `src/BootstrapBlazor/Components/AutoComplete/AutoComplete.razor.js` file to improve its behavior and functionality. The most important changes include adding a new blur event handler to close the auto-complete suggestions on tab key press, and updating the keyup event handler to use a method for showing suggestions.
Improvements to AutoComplete behavior:
* Added a new `blur` event handler to close the auto-complete suggestions when the tab key is pressed.
* Updated the keyup event handler to use the `ac.show()` method instead of directly adding the 'show' class.
* Modified the `dispose` function to remove the `keyup` event listener for the `blur` handler.
⚠️ Please check all items below before review. …

refactor(AutoComplete): auto close dropdown box after press tab

---

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj
src/BootstrapBlazor.Server/Components/Components/CustomWinBoxContent.razor.cs
src/BootstrapBlazor.Server/Components/Layout/HomeLayout.razor.cs
src/BootstrapBlazor.Server/Components/Samples/Avatars.razor.cs
src/BootstrapBlazor.Server/Components/Samples/IntersectionObservers.razor.cs
src/BootstrapBlazor.Server/Components/Samples/ListViews.razor.cs
src/BootstrapBlazor.Server/Components/Samples/Notifications.razor.cs
src/BootstrapBlazor.Server/Components/Samples/SelectObjects.razor.cs
src/BootstrapBlazor.Server/Components/Samples/Uploads.razor.cs
src/BootstrapBlazor.Server/Extensions/ICacheEntryExtensions.cs
src/BootstrapBlazor/Components/Button/Button.razor.cs
src/BootstrapBlazor/Components/Checkbox/CheckboxList.razor.cs
src/BootstrapBlazor/Components/Checkbox/CheckboxListGeneric.razor.cs
src/BootstrapBlazor/Components/SelectGeneric/SelectOptionGeneric.cs
src/BootstrapBlazor/Components/WebSpeech/WebSpeechService.cs
test/UnitTest/Components/CheckboxListGenericTest.cs
test/UnitTest/Components/DisplayTest.cs
test/UnitTest/Components/TransitionTest.cs
test/UnitTest/Localization/JsonStringLocalizerTest.cs
test/UnitTest/Services/BluetoothServiceTest.cs
test/UnitTest/Services/ClipboardServiceTest.cs
test/UnitTest/Services/IpLocatorTest.cs
tools/Benchmarks/Benmarks.cs

feat(TableExport): bump MiniExcel version to 1.41.0

---

src/BootstrapBlazor/Components/Table/Table.razor.cs

fixes #5859 
This pull request includes a single change to the `ResizeColumnCallback` method in the `Table.razor.cs` file. The change simplifies the logic for retrieving a column by removing the condition that excludes fixed columns.
* [`src/BootstrapBlazor/Components/Table/Table.razor.cs`](diffhunk://#diff-e15aff3e10d50e49be6e66542c5e6b70c93ef9854af73f6bc04bdd644637638bL1583-R1583): Modified the `ResizeColumnCallback` method to retrieve columns directly from `GetVisibleColumns()` without filtering out fixed columns.

feat(Table): support fixed column on ResizeColumnCallback

---

src/BootstrapBlazor/Components/Toast/Toast.razor.js

fixes #6038 
This pull request refactors the `Toast.razor.js` file to improve code maintainability and fix issues related to the toast progress bar and event handling. Key changes include centralizing the `progressElement` logic, updating event handlers, and enhancing the handling of the `autohide` configuration.
* Centralized the `progressElement` logic by moving its initialization to the `init` function and ensuring consistent usage across methods. This eliminates redundant queries for the `.toast-progress` element.
* Simplified event handler setup by directly using `el` (the toast element) instead of repeatedly referencing `toast.element`. This improves readability and reduces potential errors.
* Added a new event handler for the `transitionend` event on the `progressElement` to …

refactor(Toast): perfect AutoHide logic

---

src/BootstrapBlazor.Server/Components/Components/BlazorReconnector.razor
src/BootstrapBlazor.Server/Components/Samples/Inputs.razor
src/BootstrapBlazor.Server/Components/Samples/Reconnectors.razor

doc(Reconnector): update support sdk version

---

src/BootstrapBlazor.Server/Components/Pages/Install_WebApp.razor
src/BootstrapBlazor.Server/Locales/en-US.json
src/BootstrapBlazor.Server/Locales/zh-CN.json

doc(Bootstrap): remove dynamic load bootstrap doc

---

src/BootstrapBlazor.Server/Components/Samples/Table/TablesFilter.razor.cs

doc(Table): remove SortList sample

---

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj
src/BootstrapBlazor.Server/Components/App.razor
src/BootstrapBlazor.Server/Components/Samples/Icons/FluentSystemIcons.razor
src/BootstrapBlazor.Server/Components/Samples/Icons/FluentSystemIcons.razor.cs
src/BootstrapBlazor.Server/Extensions/MenusLocalizerExtensions.cs
src/BootstrapBlazor.Server/Locales/en-US.json
src/BootstrapBlazor.Server/Locales/zh-CN.json

feat(FluentSystemIcons): add microsoft fluent free icon set

---

src/BootstrapBlazor/Services/DefaultNetworkMonitorService.cs

refactor(NetworkMonitor): add try/finally keep release simaphore slim

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/SelectGeneric/MultiSelectGeneric.razor.cs

fix(MultiSelectGeneric): update value when bind-Value changed

---

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj
src/BootstrapBlazor.Server/Components/Samples/Sockets/Adapters.razor
src/BootstrapBlazor.Server/Components/Samples/Sockets/Adapters.razor.cs
src/BootstrapBlazor.Server/Components/Samples/Sockets/DataEntities.razor

doc(Socket): add DataByteConverter documentation

---

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj
src/BootstrapBlazor.Server/Components/Samples/Sockets/Adapters.razor
src/BootstrapBlazor.Server/Components/Samples/Sockets/AutoReceives.razor
src/BootstrapBlazor.Server/Components/Samples/Sockets/DataEntities.razor
src/BootstrapBlazor.Server/Components/Samples/Sockets/ManualReceives.razor

doc(Socket): update DataPackageAdapter documentation

---

src/BootstrapBlazor.Server/Components/Samples/Sockets/SocketFactories.razor

doc(Socket): remove DataTypeConverter attribute

---

src/BootstrapBlazor/Components/SelectGeneric/MultiSelectGeneric.razor
src/BootstrapBlazor/Components/SelectGeneric/MultiSelectGeneric.razor.cs

fix(MultiSelectGeneric): close button not work

---

src/BootstrapBlazor/Components/Select/SelectObject.razor.cs

fix(SelectObject): should hidden append icon when hover

---

src/BootstrapBlazor/BootstrapBlazor.csproj
src/BootstrapBlazor/Components/Table/Table.razor.js

fix(Table): double click col trigger ResizeColumnCallback
