- src/BootstrapBlazor.Chart/Locales/de-DE.json
- src/BootstrapBlazor/Locales/de-DE.json
- src/BootstrapBlazor/Locales/en-US.json
> Add German translations and adjust a typo

- src/BootstrapBlazor/Locales/de-DE.json
Updated some of the german translations - cheers
> Update German translations

- src/BootstrapBlazor/Components/Search/Search.razor
- src/BootstrapBlazor/Components/Search/SearchBase.cs
Add a clear button to the search control
> Add clear button to search bar

- src/BootstrapBlazor/Components/Table/Table.razor.Toolbar.cs
Table的SaveAsync,在使用注入服务操作,EditMode="EditMode.EditForm"模式下, 表格插入新记录时候不能刷新数据 #69
> fix: add OnQueryAsync after save method

- src/BootstrapBlazor/Locales/pt.json
Add a pt.json file with Brazil language translation
> Add a portuguese-Brazilian translation locale

- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/ValidateForms.razor
- src/BootstrapBlazor.Shared/Samples/ValidateForms.razor.cs
- src/BootstrapBlazor/Components/ValidateForm/ValidateForm.razor.cs
ValidateForm添加OnFieldChanged回调,获取修改的Field和Value
Addresses #bugnumber (in this specific format)
> feat: add OnFieldChanged on ValidateForm component

- src/BootstrapBlazor/Locales/de.json
Just as it says. Added the german translation.
> Added german language

- src/BootstrapBlazor.Shared/Samples/MultiSelects.razor
- src/BootstrapBlazor/Components/Select/MultiSelect.razor.cs
- src/BootstrapBlazor/Components/Validate/IValidateComponent.cs
- src/BootstrapBlazor/Components/Validate/ValidateBase.cs
- src/BootstrapBlazor/Components/ValidateForm/BootstrapBlazorEditContextDataAnnotationsExtensions.cs
- src/BootstrapBlazor/Components/ValidateForm/ValidateForm.razor.cs
- src/BootstrapBlazor/Validators/FormItemValidator.cs
- src/BootstrapBlazor/Validators/IValidator.cs
- src/BootstrapBlazor/Validators/MaxValidator.cs
- src/BootstrapBlazor/Validators/RequiredValidator.cs
- src/BootstrapBlazor/Validators/ValidatorBase.cs
- test/UnitTest/Components/ValidateTest.cs
Change `IValidator.Validate` to `Task `from void.
Here break backward compatibility, but it is easy way.
I don't know if this is allowed or not.
TODO: real test
> feat(#168): async validation

- src/BootstrapBlazor/Components/Table/Table.razor
- src/BootstrapBlazor/Components/Table/Table.razor.cs
Eliminated bug:
With activated row virtualization and filtering and/or sorting, the rows are not updated after filtering/sorting.
Fix tested on Blazor Server.
> Table with Row Virtualization fixed Sorting and Filtering.

- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/Carousels.razor
- src/BootstrapBlazor.Shared/wwwroot/css/site.css
- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Carousel/Carousel.razor
- src/BootstrapBlazor/Components/Carousel/Carousel.razor.cs
- src/BootstrapBlazor/Components/Carousel/CarouselItem.cs
- test/UnitTest/Components/CarouselTest.cs
```
<Carousel Width="280">
<CarouselItem>
<div class="carousel-item-demo">
<h3>Title-1</h3>
<div>Content-1</div>
<div>
<Button Icon="fa fa-fa" Text="Button-1" />
</div>
</div>
</CarouselItem>
<CarouselItem>
<div class="carousel-item-demo">
<h3>Title-2</h3>
<div>Content-2</div>
<div>
<Button Icon="fa fa-fa" Text="Button-2" />
</div>
</div>
</CarouselItem>
<CarouselItem>
<div class="carousel-item-demo">
<h3>Title-3</h3>
<div>Content-3</div>
<div>
<Button Icon="fa fa-fa" Text="Button-3" />
</div>
</div>
</CarouselItem>
</Carousel>
```
> feat: add CarouselItem for Carousel component

- src/BootstrapBlazor.Shared/Samples/Transitions.razor.cs
- src/BootstrapBlazor/Enums/TransitionType.cs
补全动画效果
Addresses #bugnumber (in this specific format)
#213
> refactor: update TransitionType enum

- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/FullScreens.razor
文字多了个"号
Addresses #bugnumber (in this specific format)
#260
> FullScreen 全屏 文档优化

- src/BootstrapBlazor/Components/Button/ButtonBase.cs
> doc: update the document for StopPropagation of ButtonBase

- README.md
update the link of shield for github.com build
#313
> doc: update readme document

- test/UnitTest/Components/TableTest.cs
Co-authored-by: alex chow <zhouchuanglin@gmail.com>
close #315
> test: 增加 ResetVisibleColumns 单元测试

- test/UnitTest/Components/TableTest.cs
Co-authored-by: alex chow <zhouchuanglin@gmail.com>
close #317
> test: add unit test for table FixedMultipleColumn method

- src/BootstrapBlazor/Components/Dialog/EditDialog.razor
- src/BootstrapBlazor/Components/Dialog/EditDialog.razor.cs
Co-authored-by: alex chow [zhouchuanglin@gmail.com](mailto:zhouchuanglin@gmail.com)
close #333
> fix: remove not found edit-dialog id warning

- src/BootstrapBlazor/wwwroot/modules/modal.js
> fix: use children.length instead of querySelectorAll

- src/BootstrapBlazor/Components/Dialog/Dialog.razor.cs
- src/BootstrapBlazor/wwwroot/modules/modal.js
> fix: close all window when Modal inside of Dialog #337

- src/Extensions/Components/BootstrapBlazor.BaiduOcr/Models/InvoiceVerifyResult.cs
> add Valid/VerifyFrequency property on InvoiceVerifyResult

- src/BootstrapBlazor.Shared/Demos/BaiduOcr/BaiduOcrVerifyVatInvoice.razor
> update verify vat invoice sample code

- test/UnitTest/Components/TableTest.cs
> test: add unit test for table IsHideFooterWhenNoData

- test/UnitTest/Components/TableDialogTest.cs
> test: add ItemsChanged unit test of Table

- .github/workflows/build.yml
- .github/workflows/pull-request.yml
Co-authored-by: alex chow <zhouchuanglin@gmail.com>
Co-authored-by: lambert lee <1708416@qq.com>
Co-authored-by: lambert lee <lish@live.cn>
close #361
> add codecov action check for pull-request

- test/UnitTest/Components/TableTreeNodeTest.cs
> test: add TableTreeNode unit test

- .github/PULL_REQUEST_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE/servicing.md
> chore: update pull reqeust template

- test/UnitTest/Components/SelectTreeTest.cs
> test: add OnSelectedItemChanged unit test

- .github/workflows/pull_request.yml
- test/UnitTest/Components/TableTest.cs
add GetCellClassString unit test
Fixes #374
> test: add GetCellClassString unit test

- .github/ISSUE_TEMPLATE/10_bug_report.yml
- .github/ISSUE_TEMPLATE/20_feature_request.yml
- .github/pull_request_template.md
> chore: update issue form

- test/UnitTest/Components/TreeViewTest.cs
> test: add ExpandIcon unit test

- .github/workflows/auto_assign_labels.yml
- .github/workflows/auto_assign_milestone.yml
- .github/workflows/auto_comment_issue.yml
> add auto assign actions

- src/BootstrapBlazor/Components/Table/Table.razor.Toolbar.cs
- test/UnitTest/Components/TableTest.cs
> test(Table): add unit test for table

- test/UnitTest/Components/TableTest.cs
> test: update table page test

- .github/workflows/auto_assign_labels_issue.yml
- .github/workflows/auto_assign_milestone_pull_request.yml
- .github/workflows/auto_comment_issue.yml
- .github/workflows/auto_pull_request_checks.yml
- BootstrapBlazor.sln
> chore: update actions/bots jobs name

- .github/workflows/auto_assign_issue.yml
- .github/workflows/auto_comment_issue.yml
- .github/workflows/auto_pull_request_checks.yml
- .github/workflows/build.yml
- .github/workflows/docker.yml
- .github/workflows/pack.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
- .github/workflows/sync_from_issue.yml
- docs/repro.md
> chore: update comment label action and repro document

- .github/workflows/auto_sync_from_issue.yml
- .github/workflows/build.yml
- .github/workflows/deploy.yml
- .github/workflows/docker.yml
- .github/workflows/pack.yml
- .github/workflows/publish.yml
- BootstrapBlazor.sln
- src/BootstrapBlazor/Components/Menu/SubMenu.razor.cs
- test/UnitTest/Components/MenuTest.cs
> test: add menu unit test improve code coverage

- .github/workflows/auto_sync_from_issue.yml
- src/BootstrapBlazor/Components/Cascader/Cascader.razor.cs
- test/UnitTest/Components/CascaderTest.cs
> test: add unit test for cascader

- src/BootstrapBlazor/Components/DateTimeRange/DateTimeRange.razor.cs
- src/BootstrapBlazor/Validators/DateTimeRangeRequiredValidator.cs
- test/UnitTest/Validators/DateTimeRangeRangeRequiredValidatorTest.cs
> test: add unit test for DateTimeRangeRequiredValidator

- .github/workflows/auto_pull_request_checks.yml
- src/BootstrapBlazor/Components/BaseComponents/BootstrapBlazorRoot.razor.cs
- src/BootstrapBlazor/Utils/Utility.cs
> test: refactor Utility.Clone method for improve code coverage

- src/BootstrapBlazor/Components/BaseComponents/BootstrapBlazorRoot.razor.cs
- test/UnitTest/Dynamic/DataTableDynamicContextTest.cs
> test: add unit test for DataTableDynamicContext

- src/BootstrapBlazor/Services/CacheManager.cs
- test/UnitTest/Utils/UtilityTest.cs
- test/UnitTest/zh-CN.json
> test: improve code coverage for CacheManager

- src/BootstrapBlazor/readme.md
> doc: update readme.md for package

- src/BootstrapBlazor.Shared/Demos/Table/TablesToolbar/TablesToolbarCustomButton.razor
- src/BootstrapBlazor.Shared/Demos/Table/TablesToolbar/TablesToolbarCustomDispalyButton.razor
- src/BootstrapBlazor.Shared/Demos/Table/TablesToolbar/TablesToolbarNormal.razor
- src/BootstrapBlazor.Shared/Demos/Table/TablesToolbar/TablesToolbarQueryTabel.razor
- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/Table/TablesToolbar.razor
Table component, Toolbar Demos update to new code block mode
fixes #427
> doc: update the table component toolbar demos

- src/BootstrapBlazor/Components/Dialog/EditDialog.razor
- src/BootstrapBlazor/Components/Dialog/EditDialog.razor.cs
bug(Table): the loader does not disappear
fixes #434
> fix: the loader does not disappear

- test/UnitTest/Components/PopConfirmButtonTest.cs
> test: add Trigger unit test improve code coverage

- test/UnitTest/Attributes/AutoGenerateClassTest.cs
> test: improve GetDisplayName code coverage

- src/BootstrapBlazor/Components/Checkbox/CheckboxList.razor.cs
> refactor: update CheckboxList for improve code coverage

- test/UnitTest/Components/TableStringFilterTest.cs
> test: add unit test for HasFilter

- src/BootstrapBlazor/Components/Handwritten/Handwritten.razor.cs
- src/BootstrapBlazor/Components/Menu/SideMenu.razor.cs
- src/BootstrapBlazor/Components/Menu/TopMenu.razor.cs
- test/UnitTest/Components/MenuTest.cs
> test: add unit test for Menu

- test/UnitTest/Components/MultiSelectTest.cs
> test: add isPopover unit test for MultiSelect

- .github/bb-auto-config.yml
- BootstrapBlazor.sln
> chore: add bb-auto-config.yml file

- test/UnitTest/Components/ToastTest.cs
> test: add null Options unit test for Toast

- .github/ISSUE_TEMPLATE/config.yml
Signed-off-by: Alex chow <zhouchuanglin@gmail.com>
打开issue展示模板,
- name: Discussions 🗨️
url: https://github.com/dotnetcore/BootstrapBlazor/discussions
about: Please post any questions during use here
- name: Quick start 🚀
url: https://github.com/dotnetcore/BootstrapBlazor/discussions/categories/quick-start
about: About BootstrapBlazor quick start please visit here
close #473
> chore: add config Issue form

- src/BootstrapBlazor/BootstrapBlazor.csproj
- test/UnitTest/Components/ButtonTest.cs
> test: add unit test for TooltipWrapperBase

- .github/ISSUE_TEMPLATE/config.yml
Signed-off-by: Alex chow <zhouchuanglin@gmail.com>
Issue #475
> chore: update config Issue form

- test/UnitTest/Extensions/EnumExtensionsTest.cs
> test: add unit test for not exist field

- src/BootstrapBlazor/Extensions/ObjectExtensions.cs
> test: add unite test for TryConvertTo

- src/BootstrapBlazor.Shared/Demos/Table/TablesFilter/TablesFilterDefaultSort.razor
- src/BootstrapBlazor.Shared/Demos/Table/TablesFilter/TablesFilterOnSort.razor
- src/BootstrapBlazor.Shared/Demos/Table/TablesFilter/TablesFilterSortString.razor
- src/BootstrapBlazor.Shared/Demos/Table/TablesFilter/TablesFilterTemplate.razor
- src/BootstrapBlazor.Shared/Demos/Table/TablesFilter/TablesFilterable.razor
- src/BootstrapBlazor.Shared/Demos/Table/TablesFilter/TablesSetFilterInCode.razor
- src/BootstrapBlazor.Shared/Demos/Table/TablesFilter/TablesShowFilterHeader.razor
- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/Table/TablesFilter.razor
> doc: update the table component filter demos

- src/BootstrapBlazor.Shared/Components/DataDialogComponent.razor
- src/BootstrapBlazor.Shared/Demos/Dialog/DialogApply.razor
- src/BootstrapBlazor.Shared/Demos/Dialog/DialogCloseDialogByCode.razor
- src/BootstrapBlazor.Shared/Demos/Dialog/DialogDisableHeaderCloseButton.razor
- src/BootstrapBlazor.Shared/Demos/Dialog/DialogPrintDialog.razor
- src/BootstrapBlazor.Shared/Samples/Prints.razor.cs
- src/BootstrapBlazor/Extensions/PrintServiceExtensions.cs
> doc: update Dialog close button sample code

- .github/ISSUE_TEMPLATE/30_documentation.yml
> chore: update document issue form

- src/BootstrapBlazor.Shared/Components/DemoBlock.razor.css
- src/BootstrapBlazor.Shared/Shared/ComponentLayout.razor
- src/BootstrapBlazor.Shared/Shared/ComponentLayout.razor.cs
update the demos C# tabItem content
**Before**
**After**
close #496
> doc: update the demos C# tabItem content

- src/BootstrapBlazor.Shared/Samples/Table/TablesRow.razor.css
file moved to new code block
close #509
> chore: remove the TableRow Demo css file

- src/BootstrapBlazor.Shared/Demos/Table/TablesRow/TablesRowClickToSelect.razor.css
- src/BootstrapBlazor.Shared/Demos/Table/TablesRow/TablesRowDoubleClickRowCallback.razor.css
- src/BootstrapBlazor.Shared/Demos/Table/TablesRow/TablesRowNubmer.razor.css
- src/BootstrapBlazor.Shared/Demos/Table/TablesRow/TablesRowSetRowClassFormatter.razor.css
> doc: remove duplicate isolation css file

- src/BootstrapBlazor/Components/IPLocator/DefaultIPLocator.cs
- test/UnitTest/Components/IPLocatorTest.cs
> test: update Locate method improve code coverage

- src/BootstrapBlazor/Components/IPLocator/DefaultIPLocator.cs
- src/BootstrapBlazor/Components/IPLocator/IIPLocator.cs
- src/BootstrapBlazor/Components/Timer/Timer.razor.cs
> test: update Timer component improve test code coverage

- src/BootstrapBlazor.Shared/Demos/Speechs/SpeechWaveNormal.razor
- src/BootstrapBlazor.Shared/Demos/Speechs/SpeechWaveShow.razor
- src/BootstrapBlazor.Shared/Demos/Speechs/SpeechWaveShowUsedTime.razor
- src/BootstrapBlazor.Shared/Demos/Table/TablesEdit/TablesEditInjectDataService.razor
- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/Speechs/SpeechWaves.razor
- src/BootstrapBlazor.Shared/Samples/Speechs/SpeechWaves.razor.cs
- src/BootstrapBlazor/Components/Speech/SpeechWave.razor.cs
> doc: update the SpeechWave demos

- src/BootstrapBlazor.Shared/Demos/Table/TablesFixedHeader/TablesFixedHeaderDialog.razor
- src/BootstrapBlazor.Shared/Demos/Table/TablesHeader/TablesHeaderNormal.razor
- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
> doc: update FixedHeader sample code

- test/UnitTest/Components/ValidateTest.cs
> test: add unit test for improve code coverage of ValidateBase

- src/BootstrapBlazor/Components/Transfer/Transfer.razor.cs
> test: improve Transfer code coverage

- src/BootstrapBlazor.Shared/Demos/Lights/LightsColor.razor
- src/BootstrapBlazor.Shared/Demos/Lights/LightsFlashing.razor
- src/BootstrapBlazor.Shared/Demos/Lights/LightsNormal.razor
- src/BootstrapBlazor.Shared/Demos/Lights/LightsTooltipText.razor
- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/Lights.razor
- src/BootstrapBlazor.Shared/Samples/Lights.razor.cs
> doc: update the Lights demos

- test/UnitTest/Components/ValidateFormTest.cs
> test: add unit test for ValidateForm improve code coverage

- test/UnitTest/Components/UploadTest.cs
> test: add unit test of UploadBase improve code coverage

- src/BootstrapBlazor.Shared/Demos/LinkButtons/LinkButtonsChildContent.razor
- src/BootstrapBlazor.Shared/Demos/LinkButtons/LinkButtonsColor.razor
- src/BootstrapBlazor.Shared/Demos/LinkButtons/LinkButtonsIcon.razor
- src/BootstrapBlazor.Shared/Demos/LinkButtons/LinkButtonsImage.razor
- src/BootstrapBlazor.Shared/Demos/LinkButtons/LinkButtonsIsDisabled.razor
- src/BootstrapBlazor.Shared/Demos/LinkButtons/LinkButtonsIsVertical.razor
- src/BootstrapBlazor.Shared/Demos/LinkButtons/LinkButtonsOnClick.razor
- src/BootstrapBlazor.Shared/Demos/LinkButtons/LinkButtonsText.razor
- src/BootstrapBlazor.Shared/Demos/LinkButtons/LinkButtonsTitle.razor
- src/BootstrapBlazor.Shared/Demos/LinkButtons/LinkButtonsUrl.razor
- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/LinkButtons.razor
- src/BootstrapBlazor.Shared/Samples/LinkButtons.razor.cs
> doc: update LinkButtons demos

- test/UnitTest/Components/TreeViewTest.cs
- test/UnitTest/Misc/TreeNodeCacheTest.cs
> test: add unit test for ExpandableNodeCache

- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/FileViewers.razor
add FileViewers tips for using under Linux.
close #563
> doc: update FileViewers demos #563

- src/BootstrapBlazor/Components/Dialog/EditDialog.razor.cs
- src/BootstrapBlazor/Extensions/DialogServiceExtensions.cs
> refactor: refine EditDialog reuse DialogCloseButton

- src/BootstrapBlazor.Shared/Demos/Table/TablesEdit/TablesEditDataService.razor
- src/BootstrapBlazor.Shared/Demos/Table/TablesEdit/TablesEditFooterTemplate.razor
- src/BootstrapBlazor.Shared/Demos/Table/TablesEdit/TablesEditInjectDataService.razor
- src/BootstrapBlazor.Shared/Demos/Table/TablesEdit/TablesEditMode.razor
- src/BootstrapBlazor.Shared/Demos/Table/TablesEdit/TablesEditOnAddAsync.razor
- src/BootstrapBlazor.Shared/Demos/Table/TablesEdit/TablesEditShowSearch.razor
- src/BootstrapBlazor.Shared/Demos/Table/TablesEdit/TablesEditTemplate.razor
> doc: update Table document

- src/BootstrapBlazor/Components/Table/Table.razor
- src/BootstrapBlazor/Components/Table/Table.razor.Toolbar.cs
- test/UnitTest/Components/TableTest.cs
> feat: add ToolbarTemplate on Table component

- src/BootstrapBlazor/Components/Table/Table.razor.cs
> fix: model value not update on Excel mode in OnSaveAsync

- src/BootstrapBlazor.Shared/Demos/Table/TablesToolbar/TablesToolbarCustomButton.razor
- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor/Components/Table/TableToolbar.razor
- src/BootstrapBlazor/Components/Table/TableToolbar.razor.cs
- src/BootstrapBlazor/Components/Table/TableToolbarButton.cs
- src/BootstrapBlazor/Components/Table/TableToolbarPopconfirmButton.cs
> feat: add IsEnableWhenSelectedOneRow parameter on TableToolbarPopconfirmButton

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Table/Table.razor.cs
- src/BootstrapBlazor/Components/Validate/ValidateBase.cs
- test/UnitTest/Components/InputTest.cs
- test/UnitTest/Components/TableTest.cs
> fix: value not updated in OnValueChanged callback

- src/BootstrapBlazor/Components/Button/PopConfirmButton.razor
- src/BootstrapBlazor/Components/Button/PopConfirmButton.razor.cs
- src/BootstrapBlazor/Components/Button/PopConfirmButtonBase.cs
- src/BootstrapBlazor/Components/Button/PopConfirmButtonContent.razor.cs
- src/BootstrapBlazor/Components/Table/TableToolbar.razor
- src/BootstrapBlazor/Components/Table/TableToolbar.razor.cs
- src/BootstrapBlazor/Components/Table/TableToolbarPopconfirmButton.cs
> refactor: update PopConfirmButton component

- src/BootstrapBlazor/Components/DateTimeRange/DateTimeRange.razor.cs
- src/BootstrapBlazor/Components/DateTimeRange/DateTimeRangeValue.cs
- test/UnitTest/Components/DateTimeRangeTest.cs
> refactor: remove the time value from DateTimeRange value

- src/BootstrapBlazor.Shared/Components/FooSearch.razor
- src/BootstrapBlazor.Shared/Data/FooSearchModel.cs
- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/DateTimeRange/DateTimeRange.razor.cs
- test/UnitTest/Components/DateTimeRangeTest.cs
> revert: remove the time value from DateTimeRange value

- src/Extensions/Components/BootstrapBlazor.TableExport/BootstrapBlazor.TableExport.csproj
- src/Extensions/Components/BootstrapBlazor.TableExport/ExcelExport.cs
> feat: update Table ExportAsync method

- src/BootstrapBlazor.Shared/Components/DemoTabItem.razor.cs
- src/BootstrapBlazor.Shared/Components/DemoTabItemSetText.razor
- src/BootstrapBlazor.Shared/Components/DemoTabItemSetText.razor.cs
- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/Tabs.razor
- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Tab/TabItem.cs
- test/UnitTest/Components/TabTest.cs
> feat: add SetHeader on TabItem

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Select/Select.razor.cs
- src/BootstrapBlazor/Components/Switch/Switch.razor.cs
Co-authored-by: XiaoDD <2238876055@qq.com>
close #633
> fix: the value not update when click Select item

- src/BootstrapBlazor.Shared/Samples/Tabs.razor
- src/BootstrapBlazor.Shared/Samples/Tabs.razor.cs
- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Tab/Tab.razor
- src/BootstrapBlazor/Components/Tab/TabItem.cs
> feat: update HeaderTemplate on Tab

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Transfer/TransferPanel.razor
- src/BootstrapBlazor/Components/Transfer/TransferPanel.razor.cs
- test/UnitTest/Components/TransferPanelTest.cs
> feat: add HeaderTemplate/ItemTemplate on Transfer component

- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/Transfers.razor.cs
- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Transfer/Transfer.razor
- src/BootstrapBlazor/Components/Transfer/Transfer.razor.cs
- test/UnitTest/Components/TransferTest.cs
> feat: add Left/Right template on Transfer component

- src/BootstrapBlazor.Shared/Demos/Table/TablesColumn/TablesColumnSelect.razor
- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Table/Table.razor
- src/BootstrapBlazor/Components/Table/Table.razor.Checkbox.cs
- test/UnitTest/Components/TableTest.cs
> feat: add ShowRowCheckboxCallback on Table

- src/BootstrapBlazor.Shared/Components/DemoBlock.razor
- src/BootstrapBlazor.Shared/Components/DemoBlock.razor.cs
- src/BootstrapBlazor.Shared/Components/Pre.razor.cs
- src/BootstrapBlazor.Shared/Extensions/CacheManagerExtensions.cs
- src/BootstrapBlazor.Shared/Services/CodeSnippetService.cs
- src/BootstrapBlazor.Shared/Shared/ComponentLayout.razor
- src/BootstrapBlazor.Shared/Shared/ComponentLayout.razor.cs
> doc: update ComponentLayout

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Table/ITableToolbarButton.cs
- src/BootstrapBlazor/Components/Table/TableToolbar.razor.cs
- src/BootstrapBlazor/Components/Table/TableToolbarButton.cs
- src/BootstrapBlazor/Components/Table/TableToolbarPopconfirmButton.cs
- test/UnitTest/Components/TableTest.cs
> feat(Table): add IsDisabledCallback on TableToolbarButton component

- src/BootstrapBlazor/Components/Camera/Camera.razor
- src/BootstrapBlazor/Components/Camera/Camera.razor.cs
- src/BootstrapBlazor/Enums/ComponentIcons.cs
- src/BootstrapBlazor/Options/Constants.cs
> feat(Camera): support icon theme

- src/BootstrapBlazor/Components/Captcha/Captcha.razor
- src/BootstrapBlazor/Components/Captcha/Captcha.razor.cs
- src/BootstrapBlazor/Components/Captcha/CaptchaOption.cs
- src/BootstrapBlazor/Enums/ComponentIcons.cs
- src/BootstrapBlazor/Options/Constants.cs
- src/BootstrapBlazor/bundleconfig.json
> feat(Captcha): support icon theme

- src/BootstrapBlazor.Shared/Demos/Transitions/TransitionsDuration.razor
- src/BootstrapBlazor.Shared/Demos/Transitions/TransitionsEndCallback.razor
- src/BootstrapBlazor.Shared/Demos/Transitions/TransitionsNormal.razor
- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/Transitions.razor
- src/BootstrapBlazor.Shared/Samples/Transitions.razor.cs
> doc: update Transitions demos

- src/BootstrapBlazor.Shared/Demos/VideoPlayers/VideoPlayersChangeURL.razor
- src/BootstrapBlazor.Shared/Demos/VideoPlayers/VideoPlayersNomal.razor
- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/VideoPlayers.razor
- src/BootstrapBlazor.Shared/Samples/VideoPlayers.razor.cs
> doc: update VideoPlayers demos

- src/BootstrapBlazor/Components/Cascader/Cascader.razor
- src/BootstrapBlazor/Components/Cascader/Cascader.razor.cs
- src/BootstrapBlazor/Enums/ComponentIcons.cs
- src/BootstrapBlazor/Services/DefaultIconTheme.cs
> feat(Cascader): support Icon theme

- src/BootstrapBlazor/Components/Cascader/Cascader.razor
- src/BootstrapBlazor/Components/Cascader/Cascader.razor.cs
- src/BootstrapBlazor/Components/Cascader/SubCascader.razor
- src/BootstrapBlazor/Components/Cascader/SubCascader.razor.cs
- src/BootstrapBlazor/Components/Collapse/CollapseItem.cs
- src/BootstrapBlazor/Components/Console/Console.razor.cs
- src/BootstrapBlazor/Enums/ComponentIcons.cs
- src/BootstrapBlazor/Services/DefaultIconTheme.cs
> feat(Console): support Icon theme

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Console/Console.razor
- src/BootstrapBlazor/Components/Console/Console.razor.cs
- test/UnitTest/Components/ConsoleTest.cs
> feat(Console): add ItemTemplate parameter

- src/BootstrapBlazor/Components/Search/Search.razor.cs
- src/BootstrapBlazor/Enums/ComponentIcons.cs
- src/BootstrapBlazor/Services/DefaultIconTheme.cs
> feat(Search): support Icon theme

- src/BootstrapBlazor/Components/Dialog/ResultDialogOption.cs
- src/BootstrapBlazor/Components/Dialog/SearchDialog.razor
- src/BootstrapBlazor/Components/Dialog/SearchDialog.razor.cs
- src/BootstrapBlazor/Components/Modal/ModalDialog.razor
- src/BootstrapBlazor/Components/Modal/ModalDialog.razor.cs
- src/BootstrapBlazor/Enums/ComponentIcons.cs
- src/BootstrapBlazor/Services/DefaultIconTheme.cs
- test/UnitTest/Components/DialogTest.cs
> feat(SearchDialog): support Icon theme

- src/BootstrapBlazor/Components/Print/PrintButton.razor.cs
- src/BootstrapBlazor/Enums/ComponentIcons.cs
- src/BootstrapBlazor/Services/DefaultIconTheme.cs
> feat(Print): support Icon theme

- src/BootstrapBlazor/Components/Button/ButtonBase.cs
- src/BootstrapBlazor/Components/Button/PopConfirmButtonBase.cs
- src/BootstrapBlazor/Components/DateTimeRange/DateTimeRange.razor.cs
- src/BootstrapBlazor/Components/DropdownWidget/DropdownWidgetItem.cs
- src/BootstrapBlazor/Components/Filters/FilterButton.razor
- src/BootstrapBlazor/Components/Filters/FilterButton.razor.cs
- src/BootstrapBlazor/Enums/ComponentIcons.cs
- src/BootstrapBlazor/Services/DefaultIconTheme.cs
- test/UnitTest/Components/SwalTest.cs
> feat(FilterButton): support Icon theme

- src/BootstrapBlazor/Components/Filters/TableFilter.razor
- src/BootstrapBlazor/Components/Filters/TableFilter.razor.cs
- src/BootstrapBlazor/Enums/ComponentIcons.cs
- src/BootstrapBlazor/Services/DefaultIconTheme.cs
> feat(TableFilter): support Icon theme

- src/BootstrapBlazor/Components/FullScreen/FullScreenButton.razor.cs
- src/BootstrapBlazor/Enums/ComponentIcons.cs
- src/BootstrapBlazor/Services/DefaultIconTheme.cs
> feat(FullScreenButton): support Icon theme

- src/BootstrapBlazor.Shared/Samples/Charts/Bubble.razor
- src/BootstrapBlazor.Shared/Samples/Charts/Doughnut.razor
- src/BootstrapBlazor.Shared/Samples/Charts/Line.razor
- src/BootstrapBlazor.Shared/Samples/Charts/Pie.razor
> doc(Chart): update document for Chart sample code

- src/BootstrapBlazor.Shared/Demos/Table/TablesFixedColumn/TablesFixedColHeader.razor
- src/BootstrapBlazor.Shared/Demos/Table/TablesFixedColumn/TablesFixedColTableHeader.razor
- src/BootstrapBlazor.Shared/Demos/Table/TablesFixedColumn/TablesFixedExtendButtonsColumn.razor
- src/BootstrapBlazor.Shared/Demos/Table/TablesFixedColumn/TablesFixedHeaderAndExtendButtonsColumn.razor
- src/BootstrapBlazor.Shared/Samples/Table/TablesFixedColumn.razor
- src/BootstrapBlazor.Shared/Shared/MainLayout.razor.css
- src/BootstrapBlazor.Shared/Shared/NavMenu.razor.css
- src/BootstrapBlazor.Shared/wwwroot/css/site.css
- src/BootstrapBlazor/Components/Gotop/GoTop.razor
- src/BootstrapBlazor/Components/Gotop/GoTop.razor.cs
- src/BootstrapBlazor/Enums/ComponentIcons.cs
- src/BootstrapBlazor/Services/DefaultIconTheme.cs
> feat(GoTop): support Icon theme

- src/BootstrapBlazor/Components/ImageViewer/ImagePreviewer.razor
- src/BootstrapBlazor/Components/ImageViewer/ImagePreviewer.razor.cs
- src/BootstrapBlazor/Enums/ComponentIcons.cs
- src/BootstrapBlazor/Services/DefaultIconTheme.cs
> feat(ImagePrviewer): suport Icon theme

- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
> doc(Table): update fix column sample code

- src/BootstrapBlazor.Shared/Demos/Table/TablesDetailRow/TablesDetailRowIsDetails.razor
- src/BootstrapBlazor.Shared/Demos/Table/TablesFixedColumn/TablesFixedColHeader.razor
- src/BootstrapBlazor.Shared/Demos/Table/TablesFixedColumn/TablesFixedColTableHeader.razor
- src/BootstrapBlazor.Shared/Demos/Table/TablesFixedColumn/TablesFixedExtendButtonsColumn.razor
- src/BootstrapBlazor.Shared/Demos/Table/TablesFixedColumn/TablesFixedHeaderAndExtendButtonsColumn.razor
- src/BootstrapBlazor.Shared/Demos/Table/TablesFixedHeader/TablesFixedHeaderAllowResizing.razor
- src/BootstrapBlazor.Shared/Demos/Table/TablesFixedHeader/TablesFixedHeaderAutoHeight.razor
- src/BootstrapBlazor.Shared/Demos/Table/TablesFixedHeader/TablesFixedHeaderNormal.razor
- src/BootstrapBlazor.Shared/Demos/Table/TablesFixedHeader/TablesFixedHeaderWidth.razor
- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Table/Table.razor
- src/BootstrapBlazor/Components/Table/Table.razor.Sort.cs
- src/BootstrapBlazor/Components/Table/Table.razor.Toolbar.cs
- src/BootstrapBlazor/Components/Table/Table.razor.cs
- test/UnitTest/Components/TableTest.cs
> feat(Table): DetailRowHeader column support fixed

- src/BootstrapBlazor.Shared/Demos/Selects/SelectsBindingSelectedItem.razor
- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/Selects.razor
- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Display/DisplayBase.cs
- src/BootstrapBlazor/Components/Select/Select.razor.cs
- src/BootstrapBlazor/Components/Select/SelectBase.cs
- src/BootstrapBlazor/Enums/ComponentIcons.cs
- src/BootstrapBlazor/Services/DefaultIconTheme.cs
- test/UnitTest/Components/SelectTest.cs
> feat(Select): support bind SelectItem

- src/BootstrapBlazor/Components/ImageViewer/ImageViewer.razor
- src/BootstrapBlazor/Components/ImageViewer/ImageViewer.razor.cs
- src/BootstrapBlazor/Enums/ComponentIcons.cs
- src/BootstrapBlazor/Services/DefaultIconTheme.cs
> feat(ImageViewer): support Icon theme

- src/BootstrapBlazor.Shared/Demos/Splits/SplitsNested.razor
- src/BootstrapBlazor.Shared/Demos/Splits/SplitsNormal.razor
- src/BootstrapBlazor.Shared/Demos/Splits/SplitsPercent.razor
- src/BootstrapBlazor.Shared/Demos/Splits/SplitsVertical.razor
- src/BootstrapBlazor.Shared/Samples/Splits.razor
- src/BootstrapBlazor.Shared/Samples/Splits.razor.cs
- src/BootstrapBlazor.Shared/Samples/Splits.razor.css
> doc: update Splits Demos

- src/BootstrapBlazor/Components/InputNumber/BootstrapInputNumber.razor
- src/BootstrapBlazor/Components/InputNumber/BootstrapInputNumber.razor.cs
- src/BootstrapBlazor/Enums/ComponentIcons.cs
- src/BootstrapBlazor/Services/DefaultIconTheme.cs
> feat(InputNumber): support Icon theme

- src/BootstrapBlazor/Components/Layout/Layout.razor
- src/BootstrapBlazor/Components/Layout/Layout.razor.cs
- src/BootstrapBlazor/Enums/ComponentIcons.cs
- src/BootstrapBlazor/Services/DefaultIconTheme.cs
> feat(Layout): support Icon theme

- src/BootstrapBlazor/Components/Pagination/Pagination.razor.cs
- src/BootstrapBlazor/Enums/ComponentIcons.cs
- src/BootstrapBlazor/Services/DefaultIconTheme.cs
> feat(Pagination): support Icon theme

- src/BootstrapBlazor/Components/InputNumber/BootstrapInputNumber.razor.cs
- src/BootstrapBlazor/Components/Rate/Rate.razor.cs
- src/BootstrapBlazor/Enums/ComponentIcons.cs
- src/BootstrapBlazor/Services/DefaultIconTheme.cs
- test/UnitTest/Components/IPLocatorTest.cs
> feat(Rate): support Icon theme

- src/BootstrapBlazor/Components/Select/MultiSelect.razor.cs
- src/BootstrapBlazor/Enums/ComponentIcons.cs
- src/BootstrapBlazor/Services/DefaultIconTheme.cs
> feat(MultiSelect): support Icon theme

- src/BootstrapBlazor/Components/Skeleton/SkeletonTree.razor
- src/BootstrapBlazor/Components/Skeleton/SkeletonTree.razor.cs
- test/UnitTest/Components/SkeletonTest.cs
> feat(SkeletonTree): support Icon theme

- src/BootstrapBlazor/Components/SweetAlert/SweetAlertBody.razor.cs
- src/BootstrapBlazor/Enums/ComponentIcons.cs
- src/BootstrapBlazor/Services/DefaultIconTheme.cs
> feat(Swal): support Icon theme

- src/BootstrapBlazor/Components/Select/SelectTree.razor.cs
- src/BootstrapBlazor/Components/Timer/Timer.razor
- src/BootstrapBlazor/Components/Timer/Timer.razor.cs
- src/BootstrapBlazor/Enums/ComponentIcons.cs
- src/BootstrapBlazor/Services/DefaultIconTheme.cs
> feat(Timer): support Icon theme

- src/BootstrapBlazor/Components/Toast/Toast.razor.cs
- src/BootstrapBlazor/Components/Toast/ToastOption.cs
- src/BootstrapBlazor/Enums/ComponentIcons.cs
- src/BootstrapBlazor/Services/DefaultIconTheme.cs
> feat(Toast): support Icon theme

- src/BootstrapBlazor/Components/Tab/Tab.razor.cs
- src/BootstrapBlazor/Components/Transfer/Transfer.razor
- src/BootstrapBlazor/Components/Transfer/Transfer.razor.cs
- src/BootstrapBlazor/Components/Transfer/TransferPanel.razor
- src/BootstrapBlazor/Components/Transfer/TransferPanel.razor.cs
- src/BootstrapBlazor/Enums/ComponentIcons.cs
- src/BootstrapBlazor/Services/DefaultIconTheme.cs
- test/UnitTest/Components/ToastTest.cs
> feat(Transfer): support Icon theme

- src/BootstrapBlazor.Shared/Demos/Spinners/SpinnerColor.razor
- src/BootstrapBlazor.Shared/Demos/Spinners/SpinnerCustom.razor
- src/BootstrapBlazor.Shared/Demos/Spinners/SpinnerFlex.razor
- src/BootstrapBlazor.Shared/Demos/Spinners/SpinnerFloat.razor
- src/BootstrapBlazor.Shared/Demos/Spinners/SpinnerGrowing.razor
- src/BootstrapBlazor.Shared/Demos/Spinners/SpinnerGrowingColor.razor
- src/BootstrapBlazor.Shared/Demos/Spinners/SpinnerNormal.razor
- src/BootstrapBlazor.Shared/Demos/Spinners/SpinnerSize.razor
- src/BootstrapBlazor.Shared/Samples/Spinners.razor
> doc: update Spinners demos

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Enums/ComponentIcons.cs
- src/BootstrapBlazor/Extensions/LocalizationOptionsExtensions.cs
- src/BootstrapBlazor/Localization/Json/JsonLocalizationOptions.cs
- test/UnitTest/Utils/UtilityTest.cs
> feat(Localizer): set reloadOnChagned parameter value to false

- src/BootstrapBlazor.Shared/Demos/Table/TablesExcel/TablesExcelOnQuery.razor
- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Table/Table.razor.cs
> bug(Table): always edit first row in Excel mode

- src/BootstrapBlazor/Components/Table/Table.razor
- src/BootstrapBlazor/Components/Table/Table.razor.Edit.cs
- src/BootstrapBlazor/Components/Table/Table.razor.TreeNode.cs
- src/BootstrapBlazor/Components/Table/Table.razor.cs
- src/BootstrapBlazor/Components/Tree/Tree.razor.cs
- test/UnitTest/Components/TableTest.cs
> feat(Tree): support Icon theme 

- src/BootstrapBlazor/Components/Menu/MenuLink.razor.cs
- src/BootstrapBlazor/Components/Menu/SideMenu.razor
- src/BootstrapBlazor/Components/Menu/SideMenu.razor.cs
- src/BootstrapBlazor/Components/Menu/SubMenu.razor
- src/BootstrapBlazor/Components/Menu/SubMenu.razor.cs
- src/BootstrapBlazor/Components/Menu/TopMenu.razor
- src/BootstrapBlazor/Components/Menu/TopMenu.razor.cs
- src/BootstrapBlazor/Enums/ComponentIcons.cs
- src/BootstrapBlazor/Services/DefaultIconTheme.cs
> feat(Menu): support Icon theme

- src/BootstrapBlazor/Components/Menu/MenuLink.razor.cs
- src/BootstrapBlazor/Components/Menu/SideMenu.razor
- src/BootstrapBlazor/Components/Menu/SideMenu.razor.cs
- src/BootstrapBlazor/Components/Menu/SubMenu.razor
- src/BootstrapBlazor/Components/Menu/SubMenu.razor.cs
- src/BootstrapBlazor/Components/Menu/TopMenu.razor
- src/BootstrapBlazor/Components/Menu/TopMenu.razor.cs
- src/BootstrapBlazor/Enums/ComponentIcons.cs
- src/BootstrapBlazor/Services/DefaultIconTheme.cs
> feat(MenuLink): support Icon theme

- src/BootstrapBlazor/Components/Step/Step.razor.cs
- src/BootstrapBlazor/Components/Step/StepItem.cs
- src/BootstrapBlazor/Components/Step/Steps.razor.cs
- src/BootstrapBlazor/Enums/ComponentIcons.cs
- src/BootstrapBlazor/Services/DefaultIconTheme.cs
> feat(Step): support Icon theme

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Misc/SelectedItem.cs
> feat(SelectedItem): add virtual keyword on Text property

- src/BootstrapBlazor.Shared/Demos/Footers/FooterChildContent.razor
- src/BootstrapBlazor.Shared/Demos/Footers/FooterNormal.razor
- src/BootstrapBlazor.Shared/Demos/Footers/FooterShowGoto.razor
- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/Footers.razor
- src/BootstrapBlazor.Shared/Samples/Footers.razor.cs
> doc: update Footers demos

- src/BootstrapBlazor.Shared/Demos/QRCodes/QRCodeContent.razor
- src/BootstrapBlazor.Shared/Demos/QRCodes/QRCodeDarkColor.razor
- src/BootstrapBlazor.Shared/Demos/QRCodes/QRCodeNormal.razor
- src/BootstrapBlazor.Shared/Demos/QRCodes/QRCodeWidth.razor
- src/BootstrapBlazor.Shared/Samples/QRCodes.razor
- src/BootstrapBlazor.Shared/Samples/QRCodes.razor.cs
> doc: update QRCodes demos

- src/BootstrapBlazor.Shared/Demos/Sliders/SliderBinding.razor
- src/BootstrapBlazor.Shared/Demos/Sliders/SliderNormal.razor
- src/BootstrapBlazor.Shared/Samples/Sliders.razor
- src/BootstrapBlazor.Shared/Samples/Sliders.razor.cs
> doc: update Sliders demos

- src/BootstrapBlazor.Shared/Samples/ValidateForms.razor
update ValidateFormNormal Localizer
close #902
> doc: update ValidateFormNormal Localizer

- src/Extensions/Components/BootstrapBlazor.Topology/BootstrapBlazor.Topology.csproj
- src/Extensions/Components/BootstrapBlazor.Topology/Components/Topology/Topology.razor.cs
> feat(Topology): add Scale/Reset method on instance

- src/BootstrapBlazor.Shared/Demos/Topologies/TopologiesNomal.razor
> doc(Topology): update resize sample code

- src/BootstrapBlazor.Shared/Demos/Textareas/TextareasScroll.razor
- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/wwwroot/modules/textarea.js
> fix(Textarea): goto top not work

- src/BootstrapBlazor.Shared/Shared/HomeLayout.razor
> doc(Footer): add Internet Content Provider info

- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/Toasts.razor
- src/BootstrapBlazor/Components/Toast/Toast.razor
- src/BootstrapBlazor/Components/Toast/Toast.razor.cs
- src/BootstrapBlazor/Services/DefaultIconTheme.cs
> doc(Toast): update Toast document

- src/BootstrapBlazor/Components/Button/PopConfirmButtonContent.razor
- src/BootstrapBlazor/Components/Button/PopConfirmButtonContent.razor.cs
- src/BootstrapBlazor/Enums/ComponentIcons.cs
- src/BootstrapBlazor/Services/DefaultIconTheme.cs
- test/UnitTest/Components/PopConfirmButtonTest.cs
> feat(IconTheme): remove PopConfirmButtonContentIcon enum item

- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/Table/Tables.razor
> doc(Table): add Tips for bind-Field

- src/BootstrapBlazor.Shared/Demos/Speechs/Synthesizers/SynthesizerNormal.razor
- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/Speechs/Synthesizers.razor
> doc(Speech): update the Synthesizers demos

- src/BootstrapBlazor/Components/Modal/Modal.razor.cs
- test/UnitTest/Components/ModalTest.cs
> feat(Modal): add Modal parameter on FirstAfterRenderCallbackAsync

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Extensions/BootstrapBlazorServiceCollectionExtensions.cs
- src/BootstrapBlazor/Options/IconThemeOptions.cs
- src/BootstrapBlazor/Services/DefaultIconTheme.cs
- test/UnitTest/Components/TableTest.cs
- test/UnitTest/Services/ConfigureIconMapperOptionsTest.cs
> feat(Icon): add Icon theme service

- src/BootstrapBlazor.Shared/Components/UpdateIntro.razor
> doc: update UpdateIntro description

- src/BootstrapBlazor.Shared/Demos/AutoComplete/AutoCompleteDebounce.razor
- src/BootstrapBlazor.Shared/Demos/AutoComplete/AutoCompleteGroup.razor
- src/BootstrapBlazor.Shared/Demos/AutoComplete/AutoCompleteLikeMatch.razor
- src/BootstrapBlazor.Shared/Demos/AutoComplete/AutoCompleteNoDataTip.razor
- src/BootstrapBlazor.Shared/Demos/AutoComplete/AutoCompleteNormal.razor
- src/BootstrapBlazor.Shared/Demos/AutoComplete/AutoCompleteOnSelectedItemChanged.razor
- src/BootstrapBlazor.Shared/Demos/AutoComplete/AutoCompleteShowLabel.razor
- src/BootstrapBlazor.Shared/Demos/AutoComplete/AutoCompleteValueChanged.razor
- src/BootstrapBlazor.Shared/Extensions/CacheManagerExtensions.cs
- src/BootstrapBlazor.Shared/Services/CodeSnippetService.cs
> doc(Localizer): remove inject IStringLocalizer statement from sample code

- src/BootstrapBlazor.Shared/Services/CodeSnippetService.cs
> doc(Localizer): update failed to intercept newline symbol

- src/BootstrapBlazor.Shared/Demos/Charts/Line/LineChartJS.razor
- src/BootstrapBlazor.Shared/Demos/Charts/Line/LineChartJS.razor.js
- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/Charts/Line.razor
通过调用JS方法生成Chart,可以更加灵活的配置各项属性。
close #968
> doc(LineChart): add a demo to generate charts using the Chart.JS

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/wwwroot/modules/data.js
- src/BootstrapBlazor/wwwroot/modules/utility.js
> feat(javascript): add data/utility javascript

- src/BootstrapBlazor.Server/Controllers/Api/CodeController.cs
- src/BootstrapBlazor.Server/Services/ClearUploadFilesService.cs
- src/BootstrapBlazor.Shared/Data/WebsiteOptions.cs
- src/BootstrapBlazor.Shared/Demos/Charts/Line/LineChartJS.razor
- src/BootstrapBlazor.Shared/Services/CodeSnippetService.cs
- src/BootstrapBlazor.Shared/wwwroot/modules/pre.js
> doc(Chart): do not show the source code on LineChart sample page

- src/Extensions/Components/BootstrapBlazor.Chart/BootstrapBlazor.Chart.csproj
- src/Extensions/Components/BootstrapBlazor.Chart/Components/Chart/Chart.razor.js
- src/Extensions/Components/BootstrapBlazor.Chart/Components/Chart/ChartLegendPosition.cs
- src/Extensions/Components/BootstrapBlazor.Chart/Components/Chart/ChartOptions.cs
- src/Extensions/Components/BootstrapBlazor.Chart/Converter/ChartLegendPositionConverter.cs
support LegendPosition
close #983
> feat(Chart): support LegendPosition

- src/BootstrapBlazor.Shared/Demos/Charts/Pie/PieLegendPostion.razor
- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/Charts/Index.razor
- src/BootstrapBlazor.Shared/Samples/Charts/Index.razor.cs
- src/BootstrapBlazor.Shared/Samples/Charts/Pie.razor
- src/BootstrapBlazor.Shared/Samples/Charts/Utility.cs
- src/Extensions/Components/BootstrapBlazor.Chart/BootstrapBlazor.Chart.csproj
- src/Extensions/Components/BootstrapBlazor.Chart/Components/Chart/ChartOptions.cs
- src/Extensions/Components/BootstrapBlazor.Chart/Converter/ChartLegendPositionConverter.cs
add attribute description
add pie legend position demo
close #991
> doc(Chart): update chart demo

- src/Directory.Build.props
- src/Extensions/Components/BootstrapBlazor.Chart/BootstrapBlazor.Chart.csproj
> chore(Preview): disable the message for use preview SDK

- src/BootstrapBlazor/BootstrapBlazor.csproj
> doc(CountUp): fix load countUp.min.js failed issue

- src/BootstrapBlazor/Components/FullScreen/FullScreenButton.razor.cs
- src/Extensions/Components/BootstrapBlazor.MaterialDesign.Extensions/BootstrapBlazor.MaterialDesign.Extensions.csproj
- src/Extensions/Components/BootstrapBlazor.MaterialDesign.Extensions/DefaultIcon.cs
> feat(mdi): update fullscreen icon

- src/BootstrapBlazor/Components/FullScreen/FullScreen.cs
- src/BootstrapBlazor/Components/FullScreen/FullScreenService.cs
- src/BootstrapBlazor/Extensions/FullScreenServiceExtensions.cs
- src/BootstrapBlazor/wwwroot/modules/fullscreen.js
> feat(FullScreen): use JavaScript isolation

- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
> doc(label): update document for label settings

- src/BootstrapBlazor/Components/Download/Download.cs
- src/BootstrapBlazor/wwwroot/modules/download.js
- src/BootstrapBlazor/wwwroot/modules/fullscreen.js
> feat(Download): use JavaScript isolation

- src/BootstrapBlazor/Components/Ajax/Ajax.cs
- src/BootstrapBlazor/wwwroot/modules/ajax.js
> feat(Ajax): use JavaScript isolation

- test/UnitTestEditor/EditorTest.cs
> test(EditorTest): build failed EditorTest project

- src/BootstrapBlazor/Components/DateTimeRange/DateTimeRange.razor
- src/BootstrapBlazor/Components/DateTimeRange/DateTimeRange.razor.cs
- test/UnitTest/Components/DateTimeRangeTest.cs
> fix(DateTimeRnage): incorrect EndValue when click confirm button after choose sidebar item

- src/Extensions/Components/BootstrapBlazor.Chart/BootstrapBlazor.Chart.csproj
- src/Extensions/Components/BootstrapBlazor.Chart/Components/Chart/Chart.razor.js
- src/Extensions/Components/BootstrapBlazor.Chart/Components/Chart/ChartOptions.cs
> feat(Chart): do not show scales and grid by default Pie/Doughnut

- src/BootstrapBlazor.Shared/Components/ThemeChooser.razor.js
- src/BootstrapBlazor/Components/Ajax/Ajax.cs
- src/BootstrapBlazor/Components/AutoRedirect/AutoRedirect.cs
- src/BootstrapBlazor/Components/BaseComponents/BootstrapModuleComponentBase.cs
- src/BootstrapBlazor/Components/DateTimePicker/TimePickerCell.razor
- src/BootstrapBlazor/Components/Dialog/EditDialog.razor
- src/BootstrapBlazor/Components/Dialog/IconDialog.razor
- src/BootstrapBlazor/Components/Download/Download.cs
- src/BootstrapBlazor/Components/FullScreen/FullScreen.cs
- src/BootstrapBlazor/Components/ImageViewer/ImageViewer.razor.js
- src/BootstrapBlazor/Components/Menu/Menu.razor.js
- src/BootstrapBlazor/Components/ResizeNotification/ResizeNotification.cs
- src/BootstrapBlazor/Components/Table/Table.razor.js
- test/UnitTest/Components/BootstrapModuleComponentBaseTest.cs
> feat(JSModuleAutoLoader): redesign ModuleName parameter function

- src/BootstrapBlazor/Components/Validate/ValidateBase.cs
- src/BootstrapBlazor/wwwroot/modules/validate.js
> feat(validate): use JavaScript isolation

- src/Extensions/Components/BootstrapBlazor.FontAwesome/BootstrapBlazor.FontAwesome.csproj
- src/Extensions/Components/BootstrapBlazor.FontAwesome/Components/FAIconList.razor.cs
- src/Extensions/Components/BootstrapBlazor.FontAwesome/Components/FAIconList.razor.js
> doc(FontAwesome): update xml annotation

- src/BootstrapBlazor.Shared/Demos/Captcha/CaptchaNormal.razor
- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Captcha/Captcha.razor.cs
- test/UnitTest/Components/CaptchaTest.cs
> feat(Captcha): change OnValid to OnValidAsync

- src/BootstrapBlazor/Components/Captcha/Captcha.razor.cs
- test/UnitTest/Components/CaptchaTest.cs
> feat(Captcha): add Max parameter

- src/Extensions/Components/BootstrapBlazor.MaterialDesign.Extensions/BootstrapBlazor.MaterialDesign.Extensions.csproj
- src/Extensions/Components/BootstrapBlazor.MaterialDesign.Extensions/DefaultIcon.cs
> feat(Icon): add ClearIcon for Select component

- src/BootstrapBlazor/Components/DateTimePicker/DateTimePicker.razor.js
> fix(DateTimePicker): modify the reference script

- src/BootstrapBlazor.Shared/BootstrapBlazor.Shared.csproj
- src/Extensions/Components/BootstrapBlazor.BarCode/BootstrapBlazor.BarCode.csproj
- src/Extensions/Components/BootstrapBlazor.BarCode/Components/BarcodeReader/BarcodeReader.razor.cs
> feat(BarcodeReader): support for setting camera at initialization

- src/BootstrapBlazor.Shared/BootstrapBlazor.Shared.csproj
- src/Extensions/Components/BootstrapBlazor.BarCode/BootstrapBlazor.BarCode.csproj
- src/Extensions/Components/BootstrapBlazor.Chart/Components/Chart/Chart.razor.cs
- src/Extensions/Components/BootstrapBlazor.FontAwesome/BootstrapBlazor.FontAwesome.csproj
- src/Extensions/Components/BootstrapBlazor.FontAwesome/Components/FAIconList.razor
- src/Extensions/Components/BootstrapBlazor.FontAwesome/Components/FAIconList.razor.cs
- src/Extensions/Components/BootstrapBlazor.FontAwesome/Components/FAIconList.razor.js
> feat(FontAwesome): remove BootstrapModuleComponentBase class

- src/BootstrapBlazor.Shared/BootstrapBlazor.Shared.csproj
- src/Extensions/Components/BootstrapBlazor.Markdown/BootstrapBlazor.Markdown.csproj
- src/Extensions/Components/BootstrapBlazor.Markdown/Components/Markdown/Markdown.razor.cs
> feat(Markdown): remove BootstrapModuleComponentBase class

- src/BootstrapBlazor.Shared/BootstrapBlazor.Shared.csproj
- src/Extensions/Components/BootstrapBlazor.SummerNote/BootstrapBlazor.SummerNote.csproj
- src/Extensions/Components/BootstrapBlazor.SummerNote/Components/Editor/Editor.razor.cs
> feat(Editor): reduce dependency package version

- src/BootstrapBlazor.Shared/BootstrapBlazor.Shared.csproj
- src/BootstrapBlazor.Shared/Demos/Topologies/TopologiesNormal.razor
- src/Extensions/Components/BootstrapBlazor.Topology/BootstrapBlazor.Topology.csproj
- src/Extensions/Components/BootstrapBlazor.Topology/Components/Topology/Topology.razor.cs
- src/Extensions/Components/BootstrapBlazor.Topology/Components/Topology/Topology.razor.js
> feat(Topology): add canvas height check

- src/BootstrapBlazor/Components/Select/Select.razor.js
- src/BootstrapBlazor/Components/Slider/Slider.razor.js
- src/BootstrapBlazor/wwwroot/modules/data.js
- src/BootstrapBlazor/wwwroot/modules/drag.js
- src/BootstrapBlazor/wwwroot/modules/utility.js
- src/BootstrapBlazor/wwwroot/modules/viewer.js
> feat(drag): design drag component

- src/BootstrapBlazor/Extensions/PropertyInfoExtensions.cs
- src/BootstrapBlazor/Utils/Utility.cs
> fix(Table): throw exception when model include static property

- src/BootstrapBlazor/Components/Upload/CardUpload.razor
- src/BootstrapBlazor/Components/Upload/CardUpload.razor.cs
- src/BootstrapBlazor/Components/Upload/UploadBase.cs
- src/BootstrapBlazor/wwwroot/modules/upload.js
- src/BootstrapBlazor/wwwroot/modules/viewer.js
- test/UnitTest/Components/UploadTest.cs
> feat(Upload): use JavaScript isolation

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Button/PopConfirmButton.razor.cs
- src/BootstrapBlazor/Components/Button/PopConfirmButton.razor.js
> fix(PopConfirmButton): do not pop on wasm mode

- localization/es.json
Algunas pequeñas correcciones, si encuentro mas las seguiré editando
close #1195
> chore(Localizer): update es.json

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Select/MultiSelect.razor
- src/BootstrapBlazor/Components/Select/MultiSelect.razor.cs
- test/UnitTest/Components/MultiSelectTest.cs
> fix(MultiSelect): value not change when use OnSearchTextChanged as data source

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/DateTimeRange/DateTimeRange.razor
> fix(DateTimeRange): not update display value after click Confirm/Today/Clear buttons

- src/BootstrapBlazor.Shared/Demos/EyeDropper/EyeDropperNormal.razor
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/EyeDropper/EyeDropper.cs
- src/BootstrapBlazor/Components/EyeDropper/EyeDropperService.cs
- src/BootstrapBlazor/wwwroot/modules/eye-dropper.js
- test/UnitTest/Services/EyeDropperTest.cs
> refactor(EyeDropper): handle error by press ESC key

- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/EyeDropper/EyeDropper.cs
- src/BootstrapBlazor/Components/FullScreen/FullScreen.cs
- src/BootstrapBlazor/Components/Table/Table.razor
- test/UnitTest/Components/TableTest.cs
- test/UnitTest/Components/UploadTest.cs
> fix(Table): not show the BeforeRowButtonTemplate button in CardView

- src/.config/dotnet-tools.json
- src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj
- src/BootstrapBlazor.Server/Directory.Build.props
- src/BootstrapBlazor.Server/Directory.Build.targets
- src/BootstrapBlazor/Components/Tree/Tree.razor.cs
- src/Revert.targets
- src/Version.targets
> chore(JSVersion): update output info

- src/BootstrapBlazor.Shared/Practicals/Pintereso/Pintereso.razor.css
- src/BootstrapBlazor.Shared/Shared/PracNavMenu.razor.cs
> doc(Download): bad file after download

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Select/Select.razor.js
> fix(Select): keyboard not work on ShowSearch mode

- src/BootstrapBlazor/Components/Cascader/Cascader.js
- src/BootstrapBlazor/Components/Cascader/Cascader.razor.cs
> refactor(Cascader): remove JavaScript file

- src/Extensions/Components/BootstrapBlazor.Topology/Components/Topology/Topology.razor
- src/Extensions/Components/BootstrapBlazor.Topology/Components/Topology/Topology.razor.cs
> feat(Topology): support html attribute on element

- src/BootstrapBlazor/Attributes/AutoGenerateColumnAttribute.cs
- src/BootstrapBlazor/Components/EditorForm/EditorForm.razor.cs
- test/UnitTest/Components/EditorFormTest.cs
> refactor(EditorForm): rename ColSpan to Cols

- src/BootstrapBlazor/Components/AutoComplete/AutoComplete.razor.cs
- src/BootstrapBlazor/Components/DateTimePicker/PopoverDropdownBase.cs
- src/BootstrapBlazor/Components/Select/PopoverSelectBase.cs
- test/UnitTest/Components/AutoCompleteTest.cs
- test/UnitTest/Components/CalendarTest.cs
- test/UnitTest/Components/DateTimeRangeTest.cs
- test/UnitTest/Components/DragDropTest.cs
- test/UnitTest/Components/MultiSelectTest.cs
- test/UnitTest/Components/SwalTest.cs
- test/UnitTest/Components/TreeViewTest.cs
> refactor(PopoverDropdown): update Placement default value to false

- src/Extensions/Components/BootstrapBlazor.TableExport/BootstrapBlazor.TableExport.csproj
- src/Extensions/Components/BootstrapBlazor.TableExport/ExcelExport.cs
> feat(Export): use min-excel instead of Epplus

- src/BootstrapBlazor.Shared/Shared/PracNavMenu.razor.cs
- test/UnitTest/Components/SwalTest.cs
> doc(Practicals): use stream instead of byte collection

- src/BootstrapBlazor.Shared/Shared/PracNavMenu.razor.cs
- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Extensions/BootstrapBlazorServiceCollectionExtensions.cs
- src/BootstrapBlazor/Options/ArchiveOptions.cs
- src/BootstrapBlazor/Services/DefaultZipArchiveService.cs
- src/BootstrapBlazor/Services/IZipArchiveService.cs
- test/UnitTest/Components/TableDateTimeFilterTest.cs
- test/UnitTest/Services/ZipArchiveServiceTest.cs
> feat(ZipArchiveService): add ZipArchiveService

- src/BootstrapBlazor/Services/DefaultZipArchiveService.cs
- src/BootstrapBlazor/Services/IZipArchiveService.cs
- test/UnitTest/Components/TableNumberFilterTest.cs
- test/UnitTest/Services/ZipArchiveServiceTest.cs
> feat(ZipArchiveService): add Extract/GetEntry function

- src/BootstrapBlazor/Components/Table/Table.razor.cs
- test/UnitTest/Components/LinkButtonTest.cs
- test/UnitTest/Components/ToastTest.cs
> bug(Table): tooltip content not updated from the second pages

- src/BootstrapBlazor.Shared/Demos/AzureOpenAI/AzureOpenAIChat.razor
- src/BootstrapBlazor.Shared/Demos/AzureOpenAI/AzureOpenAIChat.razor.css
- src/BootstrapBlazor.Shared/Extensions/MenusLocalizerExtensions.cs
- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
> doc(AzureOpenAI): update Azure OpenAI sample

- src/BootstrapBlazor.Shared/Demos/AzureOpenAI/AzureOpenAIChat.razor
- src/BootstrapBlazor.Shared/Demos/AzureOpenAI/AzureOpenAIChat.razor.js
> doc(AzureOpenAI): add auto scroll function

- src/BootstrapBlazor/Extensions/BootstrapBlazorServiceCollectionExtensions.cs
- src/BootstrapBlazor/Services/ComponentHtmlRenderer.cs
- src/BootstrapBlazor/Services/IComponentHtmlRenderer.cs
- src/BootstrapBlazor/Services/Internal/HtmlRenderer.cs
- src/BootstrapBlazor/Services/Internal/HtmlRootComponent.cs
- src/BootstrapBlazor/Services/Internal/StaticHtmlRenderer.HtmlWriting.cs
- src/BootstrapBlazor/Services/Internal/StaticHtmlRenderer.cs
- test/UnitTest/Components/ListViewTest.cs
- test/UnitTest/Components/TableStringFilterTest.cs
- test/UnitTest/Services/HtmlRendererTest.cs
> feat(IComponentHtmlRenderer): add IComponentHtmlRenderer service

- src/BootstrapBlazor.Shared/BootstrapBlazor.Shared.csproj
- src/BootstrapBlazor.Shared/Demos/AzureOpenAI/AzureOpenAIChat.razor
- src/BootstrapBlazor.Shared/Demos/AzureOpenAI/AzureOpenAIChat.razor.css
- src/BootstrapBlazor.Shared/Demos/AzureOpenAI/AzureOpenAIChat.razor.js
- src/Extensions/Components/BootstrapBlazor.AzureOpenAI/BootstrapBlazor.AzureOpenAI.csproj
- src/Extensions/Components/BootstrapBlazor.AzureOpenAI/Services/AzureOpenAIService.cs
- src/Extensions/Components/BootstrapBlazor.AzureOpenAI/Services/IAzureOpenAIService.cs
> feat(AzureOpenAI): add GetChatStreaming api

- src/BootstrapBlazor/wwwroot/modules/utility.js
> feat(Utility): copy function compatible with http protocal

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/AutoFill/AutoFill.razor.cs
> fix(AutoFill): does not collapse after clicking the dropdown menu item

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Layout/Layout.razor.cs
> feat(Layout): add Resource parameter

- src/BootstrapBlazor.Shared/BootstrapBlazor.Shared.csproj
- src/Extensions/Components/BootstrapBlazor.SummerNote/BootstrapBlazor.SummerNote.csproj
- src/Extensions/Components/BootstrapBlazor.SummerNote/Components/Editor/Editor.razor.js
> fix(Editor): submit button support localization

- src/BootstrapBlazor.Shared/BootstrapBlazor.Shared.csproj
- src/Extensions/Components/BootstrapBlazor.SummerNote/BootstrapBlazor.SummerNote.csproj
- src/Extensions/Components/BootstrapBlazor.SummerNote/Components/Editor/Editor.razor.cs
- src/Extensions/Components/BootstrapBlazor.SummerNote/Components/Editor/Editor.razor.js
- test/UnitTest/Components/LayoutTest.cs
- test/UnitTest/Components/ListViewTest.cs
> feat(Editor): add LanguageUrl parameter support multiple language script plugin

- src/BootstrapBlazor/Options/BootstrapBlazorOptions.cs
- src/BootstrapBlazor/Services/DefaultJSVersionService.cs
> feat(JSModule): support config JSModule version

- src/BootstrapBlazor/Utils/BootstrapDynamicComponent.cs
> feat(BootstrapDynamicComponent): add new overload method for CreateComponent

- src/BootstrapBlazor/Locales/en.json
Changes to Locales/en.json to better match English language standards
close #1329
> doc(Localization): update en localization

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/wwwroot/modules/validate.js
> fix(Validate): tooltip title incorrect

- src/BootstrapBlazor/Components/Tooltip/Tooltip.razor.js
> feat(Tooltip): support update title

- src/BootstrapBlazor/Services/DefaultJSVersionService.cs
发布时选择单文件时, xx.Assembly.Location 为空, 需要回落到 xx.Assembly.GetName() 读取版本
close #1328
> fix(GetVersion) publish to single file get version incorrect #1328 

- src/BootstrapBlazor.Shared/Pages/Index.razor.css
- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Carousel/Carousel.razor
> refactor(Carousel): update indicator for bootstrap 5.3.0

- src/BootstrapBlazor.Shared/Demos/Transitions/TransitionsEndCallback.razor
- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Transition/Transition.razor.cs
- src/BootstrapBlazor/Components/Transition/Transition.razor.js
> fix(Transition): duration parameter not work

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Extensions/ITableColumnExtensions.cs
- test/UnitTest/Extensions/ITableColumnExtensionsTest.cs
> fix(EditorForm): custom placeholders are not working in GroupBox

- src/BootstrapBlazor.Shared/Components/AIChat.razor
- src/BootstrapBlazor.Shared/Components/AIChat.razor.cs
- src/BootstrapBlazor.Shared/Components/AIChat.razor.css
- src/BootstrapBlazor.Shared/Components/AIChat.razor.js
- src/BootstrapBlazor.Shared/Components/ThemeChooser.razor.css
- src/BootstrapBlazor.Shared/Components/ThemeChooser.razor.js
- src/BootstrapBlazor.Shared/Shared/BaseLayout.razor
- src/BootstrapBlazor/Components/Button/Button.razor.js
- src/BootstrapBlazor/Components/Button/ButtonBase.cs
- src/BootstrapBlazor/Components/IFrame/IFrame.razor.js
- src/BootstrapBlazor/Components/Table/Table.razor.cs
- test/UnitTest/Components/ButtonTest.cs
- test/UnitTest/Components/InputTest.cs
> refactor(Tooltip): support real-time title updates

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Extensions/BootstrapBlazorServiceCollectionExtensions.cs
- src/BootstrapBlazor/Extensions/ConfigurationExtensions.cs
> fix(IConfiguration): throw exception use BootstrapBlazor in WinForm/WPF

- src/BootstrapBlazor/Components/Camera/Camera.razor.js
> fix(Camera): stop track failed in dispose

- src/BootstrapBlazor/Attributes/AutoGenerateColumnAttribute.cs
- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/EditorForm/EditorItem.cs
- src/BootstrapBlazor/Components/Table/InternalTableColumn.cs
- src/BootstrapBlazor/Components/Table/TableColumn.cs
> refactor(IEditorItem): add virtual key word on sub class

- src/Extensions/Components/BootstrapBlazor.Dock/Components/DockView/DockView.razor.js
> feat(DockView): auto update component item title

- src/Extensions/Components/BootstrapBlazor.Dock/Components/DockView/DockView.razor.js
> feat(DockView): auto-update component item visible state 

- src/BootstrapBlazor.Shared/Shared/DockLayout.razor.cs
- src/Extensions/Components/BootstrapBlazor.Dock/BootstrapBlazor.Dock.csproj
- src/Extensions/Components/BootstrapBlazor.Dock/Components/DockView/DockView.razor.js
> feat(DockView): auto-update tab via original title

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/RibbonTab/RibbonTab.razor
- src/BootstrapBlazor/Components/RibbonTab/RibbonTab.razor.cs
> feat(RibbonTab): add Render method

- src/Extensions/Components/BootstrapBlazor.Topology/BootstrapBlazor.Topology.csproj
- src/Extensions/Components/BootstrapBlazor.Topology/Components/Topology/Topology.razor
- src/Extensions/Components/BootstrapBlazor.Topology/Components/Topology/Topology.razor.cs
- src/Extensions/Components/BootstrapBlazor.Topology/Components/Topology/Topology.razor.js
> feat(Topology): add OnResize observer

- src/Extensions/Components/BootstrapBlazor.Topology/BootstrapBlazor.Topology.csproj
- src/Extensions/Components/BootstrapBlazor.Topology/Components/Topology/Topology.razor.js
> feat(Topology): support use in Modal

- src/Extensions/Components/BootstrapBlazor.Topology/BootstrapBlazor.Topology.csproj
- src/Extensions/Components/BootstrapBlazor.Topology/Components/Topology/Topology.razor.cs
> fix(Topology): throw exception on PushData method

- src/BootstrapBlazor.Shared/BootstrapBlazor.Shared.csproj
- src/BootstrapBlazor.Shared/Demos/Charts/Line/LineChartJS.razor.js
- src/BootstrapBlazor.Shared/Demos/Charts/Line/LineOnInit.razor
- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/Extensions/Components/BootstrapBlazor.Chart/BootstrapBlazor.Chart.csproj
- src/Extensions/Components/BootstrapBlazor.Chart/Components/Chart/Chart.razor.js
- src/Extensions/Components/BootstrapBlazor.Chart/Components/Chart/ChartOptions.cs
1. add the ```LegendLabelsFontSize``` property to the ```ChartOptions``` class to modify the legend font size
2. update the localizer doc
3. update chart demos
close #1386
> feat(Chart): support change labels font size

- src/BootstrapBlazor.Shared/wwwroot/css/site.css
- test/UnitTest/Components/RibbonTabTest.cs
> doc(Table): update set highlight style sample

- src/BootstrapBlazor/Components/Button/PopConfirmButton.razor.js
> refactor(PopConfirmButton): auto close other shown popup confirm window

- src/BootstrapBlazor.Shared/BootstrapBlazor.Shared.csproj
- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Select/Select.razor.cs
- test/UnitTest/Components/SelectTest.cs
> fix(Select): trigger OnSelectedItemChanged twice

- src/BootstrapBlazor.Shared/BootstrapBlazor.Shared.csproj
- src/BootstrapBlazor/Components/ContextMenu/ContextMenu.razor.js
- src/BootstrapBlazor/Components/Table/Table.razor.js
- src/Extensions/Components/BootstrapBlazor.Dock/BootstrapBlazor.Dock.csproj
- src/Extensions/Components/BootstrapBlazor.Dock/Components/DockView/DockComponent.cs
- src/Extensions/Components/BootstrapBlazor.Dock/Components/DockView/DockContentType.cs
- src/Extensions/Components/BootstrapBlazor.Dock/Components/DockView/DockView.razor.js
> feat(DockView): update Key parameter default value from Title

- src/BootstrapBlazor.Shared/Data/FooSearchModel.cs
- src/BootstrapBlazor.Shared/Demos/Table/TablesLoading/TablesLoadingShowLoading.razor
- src/BootstrapBlazor.Shared/Demos/Table/TablesLoading/TablesLoadingShowLoadingInFirstRender.razor
- src/BootstrapBlazor.Shared/Demos/Table/TablesLoading/TablesLoadingShowSkeleton.razor
- src/BootstrapBlazor.Shared/Demos/Table/TablesSearch/TablesAutoGenerateSearch.razor
- src/BootstrapBlazor.Shared/Demos/Table/TablesSearch/TablesCustomColSearch.razor
- src/BootstrapBlazor.Shared/Demos/Table/TablesSearch/TablesCustomerSearchModel.razor
- src/BootstrapBlazor/Components/Table/ITableSearchModel.cs
- src/BootstrapBlazor/Components/Table/Table.razor
- src/BootstrapBlazor/Components/Table/Table.razor.Edit.cs
- src/BootstrapBlazor/Components/Table/Table.razor.Search.cs
- src/BootstrapBlazor/Components/Table/Table.razor.Toolbar.cs
- src/BootstrapBlazor/Options/QueryPageOptions.cs
- test/UnitTest/Components/TableTest.cs
> refactor(Table): rename Searchs to Searches

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Table/Table.razor.js
> fix(Table): column not align when resize column on Fix Header mode

- src/BootstrapBlazor/Extensions/TypeExtensions.cs
- src/Extensions/Components/BootstrapBlazor.Dock/BootstrapBlazor.Dock.csproj
- src/Extensions/Components/BootstrapBlazor.Dock/Components/DockView/DockView.razor.js
- test/UnitTest/Components/MenuTest.cs
> feat(DockView): remove the index parameter on AddItem method

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Table/Table.razor.js
> feat(Table): auto height support ShowSearch top

- src/BootstrapBlazor.Shared/Practicals/LoginAndRegister/PracLogin.razor
- src/BootstrapBlazor.Shared/Practicals/LoginAndRegister/PracLogin.razor.css
- src/BootstrapBlazor.Shared/Shared/PracNavMenu.razor.cs
> doc(Login): add Login template

- src/BootstrapBlazor.Shared/Practicals/LoginAndRegister/PracLogin.razor
> doc(Login): update Login sample

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/LazyLoading/LazyLoading.cs
- test/UnitTest/Components/LazyLoadingTest.cs
> feat(LazyLoading): add LazyLoading component

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/BaseComponents/DynamicElement.cs
- src/BootstrapBlazor/Components/Table/Table.razor
- src/BootstrapBlazor/wwwroot/modules/utility.js
> refactor(Table): add TriggerContextMenu parameter

- src/BootstrapBlazor.Shared/BootstrapBlazor.Shared.csproj
- src/BootstrapBlazor.Shared/Samples/MouseFollowers.razor
1、add nuget package tips
2、change project reference to nuget package reference
close #1451
> doc(MouseFollower): update MouseFollower demo

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Services/ComponentHtmlRenderer.cs
- src/BootstrapBlazor/Services/IComponentHtmlRenderer.cs
- test/UnitTest/Services/HtmlRendererTest.cs
> feat(HtmlRender): add type parameter overload method

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/IFrame/IFrame.razor.cs
- src/BootstrapBlazor/Components/IFrame/IFrame.razor.js
> feat(IFrame): add instance method PushData

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/IFrame/IFrame.razor.cs
> refactor(IFrame): update PushData to public

- src/BootstrapBlazor/Extensions/JSModuleExtensions.cs
> refactor(JSModule): support no version JavaScript file

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Table/Table.razor.js
> fix(Table): can not resize table column when set ShowDetails to true

- src/Extensions/Components/BootstrapBlazor.MaterialDesign.Extensions/BootstrapBlazor.MaterialDesign.Extensions.csproj
> feat(IconTheme): add Pdf icon

- src/BootstrapBlazor.Shared/BootstrapBlazor.Shared.csproj
- src/BootstrapBlazor.Shared/Demos/Table/TablesExport/TablesExportShowExportButton.razor
- src/BootstrapBlazor/Utils/Utility.cs
- src/Extensions/Components/BootstrapBlazor.TableExport/BootstrapBlazor.TableExport.csproj
- src/Extensions/Components/BootstrapBlazor.TableExport/ExcelExport.cs
> feat(Table): export support Lookup parameter

- src/BootstrapBlazor.Shared/Samples/Table/TablesLookup.razor
- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Table/Table.razor
- src/BootstrapBlazor/Components/Table/Table.razor.js
> fix(Table): table JavaScript throw exception

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Filters/TableFilter.razor.js
> fix(Filter): can't input in Modal

- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/Dialogs.razor
- src/BootstrapBlazor/Components/Modal/ModalDialog.razor
- src/BootstrapBlazor/Components/Modal/ModalDialog.razor.cs
> doc(Dialog): update document for CloseDialogAsync

- src/BootstrapBlazor.Shared/Demos/Html2Pdf/Html2PdfNormal.razor
- src/BootstrapBlazor.Shared/Extensions/MenusLocalizerExtensions.cs
- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/Html2Pdfs.razor
> doc(Html2Pdf): add html to pdf sample code

- src/BootstrapBlazor.Shared/wwwroot/css/motronic.css
- src/BootstrapBlazor.Shared/wwwroot/css/site.css
- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Table/Table.razor.js
> fix(Table): trigger sort event when resize column

- src/BootstrapBlazor.Shared/BootstrapBlazor.Shared.csproj
- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Table/Table.razor
> fix(Table): ShowCheckboxCallback not work on CardView mode

- src/BootstrapBlazor.Shared/BootstrapBlazor.Shared.csproj
- src/BootstrapBlazor.Shared/Components/Pre.razor.js
- src/BootstrapBlazor/Components/Slider/Slider.razor.cs
- src/Extensions/Components/BootstrapBlazor.SummerNote/BootstrapBlazor.SummerNote.csproj
- src/Extensions/Components/BootstrapBlazor.SummerNote/Components/Editor/Editor.razor.js
> chore(SummerNote): update import module path

- src/BootstrapBlazor/Components/AutoComplete/AutoComplete.razor.js
- src/BootstrapBlazor/Components/Checkbox/Checkbox.razor
- src/BootstrapBlazor/Components/Display/DisplayBase.cs
- src/BootstrapBlazor/Components/EditorForm/EditorForm.razor
- src/BootstrapBlazor/Components/Input/BootstrapInput.razor.js
- src/BootstrapBlazor/Components/Input/BootstrapInputBase.cs
> feat(Checkbox): support inside BootstrapInputGroup

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Filters/TableFilter.razor.js
- src/BootstrapBlazor/Components/Modal/Modal.razor.js
> fix(Modal): remove focustrap function

- src/BootstrapBlazor.Docs/BootstrapBlazor.Docs.csproj
- src/BootstrapBlazor.Shared/BootstrapBlazor.Shared.csproj
- src/Extensions/Components/BootstrapBlazor.Live2DDisplay/BootstrapBlazor.Live2DDisplay.csproj
> doc(Shared): update package version

- src/BootstrapBlazor/Components/Camera/Camera.razor.js
> feat: Camera supports continuous focus mode

- src/BootstrapBlazor/wwwroot/modules/utility.js
同一个网页请求相同脚本时，后续脚本未阻塞，导致脚本报错
close #1546
> fix(AddScript): load failed when concurrency request script

- src/BootstrapBlazor/Services/DefaultZipArchiveService.cs
- src/BootstrapBlazor/Services/IZipArchiveService.cs
- test/UnitTest/Services/ZipArchiveServiceTest.cs
> chore(IZipArchiveService): remove await keyword

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- SECURITY.md
> doc(conduct): add code-conduct/security/contribute markdown doc

- src/BootstrapBlazor.Shared/Demos/Live2DDisplay/Live2DDisplayNormal.razor
- src/Extensions/Components/BootstrapBlazor.Live2DDisplay/Components/Live2DDisplay/Live2DDisplay.razor.cs
- src/Extensions/Components/BootstrapBlazor.Live2DDisplay/Components/Live2DDisplay/Live2DDisplay.razor.js
support draggble the model element on the document
close #1557
> feat(Live2DDisplay): support draggble element

- src/Extensions/Components/BootstrapBlazor.Dock/BootstrapBlazor.Dock.csproj
- src/Extensions/Components/BootstrapBlazor.Dock/Components/DockView/DockView.razor.cs
- src/Extensions/Components/BootstrapBlazor.Dock/Components/DockView/DockView.razor.js
- src/Extensions/Components/BootstrapBlazor.Dock/Components/DockView/DockViewConfig.cs
> feat(DockView): add LockChangedCallbackAsync parameter

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Filters/BoolFilter.razor.cs
- src/BootstrapBlazor/Components/Filters/DateTimeFilter.razor.cs
- src/BootstrapBlazor/Components/Filters/EnumFilter.razor.cs
- src/BootstrapBlazor/Components/Filters/FilterBase.cs
- src/BootstrapBlazor/Components/Filters/LookupFilter.razor.cs
- src/BootstrapBlazor/Components/Filters/NumberFilter.razor.cs
- src/BootstrapBlazor/Components/Filters/StringFilter.razor.cs
> feat(Filter): add Items parameter

- src/BootstrapBlazor/Components/Table/Table.razor.cs
- test/UnitTest/Components/TableTest.cs
> feat(Table): add OnDragColumnEndAsync parameter

- src/BootstrapBlazor.Shared/BootstrapBlazor.Shared.csproj
- src/Extensions/Components/BootstrapBlazor.SummerNote/BootstrapBlazor.SummerNote.csproj
- src/Extensions/Components/BootstrapBlazor.SummerNote/Components/Editor/Editor.razor.js
> fix(Editor): throw exception for dispose tooltip

- src/BootstrapBlazor.Shared/Demos/Table/TablesTree/TablesTreeData.razor
- src/BootstrapBlazor.Shared/Demos/Table/TablesTree/TablesTreeEdit.razor
- src/BootstrapBlazor.Shared/Demos/Table/TablesTree/TablesTreeIcon.razor
- src/BootstrapBlazor.Shared/Demos/Table/TablesTree/TablesTreeLevel.razor
> doc(Table): update table tree sample

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Menu/Menu.razor.cs
- src/BootstrapBlazor/Components/Menu/MenuItem.cs
- src/BootstrapBlazor/Components/Menu/MenuLink.razor.cs
- test/UnitTest/Components/MenuTest.cs
> feat(Menu): cascade set parent to expand on Vertical mode

- src/BootstrapBlazor.Shared/BootstrapBlazor.Shared.csproj
- src/Extensions/Components/BootstrapBlazor.Dock/BootstrapBlazor.Dock.csproj
- src/Extensions/Components/BootstrapBlazor.Dock/Components/DockView/DockView.razor.js
> refactor(DockView): sync Lock state after close tab/stack

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Tab/Tab.razor
- test/UnitTest/Components/LinkButtonTest.cs
- test/UnitTest/Components/ListViewTest.cs
- test/UnitTest/Components/TabTest.cs
- test/UnitTest/Components/TableTest.cs
> bug(Tab): should not rerender tabitem when close preview tabitem

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Table/TableFooterCell.razor
- src/BootstrapBlazor/Components/Table/TableFooterCell.razor.cs
- test/UnitTest/Components/TableFooterCellTest.cs
add Formatter/FormatString parameter
close #1592
> feat(TableFooterCell): add FormatString/Formatter parameter

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Table/Table.razor
- src/BootstrapBlazor/Components/Table/Table.razor.cs
- test/UnitTest/Components/TableTest.cs
> fix(TableColumn): ShownWithBreakPoint not work

- src/BootstrapBlazor.Server/appsettings.json
- src/BootstrapBlazor.Shared/Shared/NavMenu.razor.cs
> doc(NavMenu): only expand the active menu

- src/BootstrapBlazor/Components/AutoComplete/AutoComplete.razor
- src/BootstrapBlazor/Components/AutoComplete/AutoComplete.razor.cs
- src/BootstrapBlazor/Components/AutoComplete/AutoComplete.razor.js
- src/BootstrapBlazor/Components/Search/Search.razor
- src/BootstrapBlazor/wwwroot/modules/base-popover.js
> feat(AutoComplete): support popover function

- src/BootstrapBlazor.Server/wwwroot/css/site.css
- src/BootstrapBlazor.Shared/Components/DemoBlock.razor.css
- src/BootstrapBlazor.Shared/Demos/AutoComplete/AutoCompleteNormal.razor
- src/BootstrapBlazor.Shared/Demos/AutoFill/AutoFillNormal.razor
- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/AutoComplete/AutoComplete.razor
- src/BootstrapBlazor/Components/AutoComplete/AutoComplete.razor.cs
- src/BootstrapBlazor/Components/AutoComplete/AutoComplete.razor.js
- src/BootstrapBlazor/Components/AutoComplete/PopoverCompleteBase.cs
- src/BootstrapBlazor/Components/AutoFill/AutoFill.razor
- src/BootstrapBlazor/Components/AutoFill/AutoFill.razor.cs
- src/BootstrapBlazor/Components/Search/Search.razor
- src/BootstrapBlazor/Misc/IPopoverBaseComponent.cs
> feat(AutoFill): add IsPopover parameter

- src/BootstrapBlazor.Shared/Components/DemoBlock.razor
- src/BootstrapBlazor.Shared/Components/DemoBlock.razor.cs
- src/BootstrapBlazor.Shared/Samples/Table/TablesDynamicExcel.razor
- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Menu/Menu.razor.cs
- src/BootstrapBlazor/Components/Menu/MenuItem.cs
- src/BootstrapBlazor/Utils/JSModule.cs
- test/UnitTest/Components/AutoCompleteTest.cs
- test/UnitTest/Components/MenuTest.cs
> feat(Menu): support url hash and query

- src/Extensions/Components/BootstrapBlazor.Topology/BootstrapBlazor.Topology.csproj
- src/Extensions/Components/BootstrapBlazor.Topology/Components/Topology/Topology.razor
- src/Extensions/Components/BootstrapBlazor.Topology/Components/Topology/Topology.razor.cs
- src/Extensions/Components/BootstrapBlazor.Topology/Components/Topology/Topology.razor.js
> feat(Topology): support keep fit status function

- src/BootstrapBlazor.Shared/Samples/Html2Pdfs.razor
- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Title/Title.cs
- test/UnitTest/Components/TitleTest.cs
> fix(Title): not work SetTitle method

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/AutoComplete/AutoComplete.razor
- src/BootstrapBlazor/Components/AutoComplete/AutoComplete.razor.cs
- src/BootstrapBlazor/Components/AutoComplete/AutoComplete.razor.js
> fix(AutoComplete): can't input chinese character inside validate form

- src/BootstrapBlazor/Components/AutoComplete/AutoComplete.razor
- src/BootstrapBlazor/Components/AutoComplete/AutoComplete.razor.cs
- src/BootstrapBlazor/Components/AutoFill/AutoFill.razor
- src/BootstrapBlazor/Components/AutoFill/AutoFill.razor.cs
- src/BootstrapBlazor/Components/Search/Search.razor
- src/BootstrapBlazor/Components/Search/Search.razor.cs
> fix(AutoFill): compatible with inside validate form

- src/BootstrapBlazor.Shared/BootstrapBlazor.Shared.csproj
- src/BootstrapBlazor.Shared/Extensions/MenusLocalizerExtensions.cs
- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/Html2Pdfs.razor
- src/BootstrapBlazor.Shared/Samples/Uploads.razor
- src/Extensions/Components/BootstrapBlazor.Html2Pdf/BootstrapBlazor.Html2Pdf.csproj
- src/Extensions/Components/BootstrapBlazor.Html2Pdf/Services/DefaultPdfService.cs
- src/Extensions/Components/BootstrapBlazor.Html2Pdf/Services/IHtml2Pdf.cs
- src/Extensions/Components/BootstrapBlazor.Html2Pdf/wwwroot/export.js
> doc(Html2Pdf): update sample code

- src/BootstrapBlazor.Shared/Extensions/MenusLocalizerExtensions.cs
> doc(Charts): update sample router

- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/Table/TablesDialog.razor
- src/BootstrapBlazor.Shared/Samples/Table/TablesDialog.razor.cs
refactor the Tables Dialog document
close #1808
> doc(Tables/Dialog): refactor the Tables Dialog document(#1808)

- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/Table/TablesLookup.razor
- src/BootstrapBlazor.Shared/Samples/Table/TablesLookup.razor.cs
> doc(Table/Lookup): refact table lookup sample document

- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/Table/TablesHeader.razor
- src/BootstrapBlazor.Shared/Samples/Table/TablesHeader.razor.cs
refactor the Tables MultiHeader document.
close #1838
> doc(Table/MultiHeader): refactor the Table MultiHeader document

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Card/Card.razor.cs
- src/BootstrapBlazor/Components/Collapse/Collapse.razor.cs
- test/UnitTest/Components/CardTest.cs
> feat(Card): collapsed parameter support bind

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Card/Card.razor
- src/BootstrapBlazor/Components/Card/Card.razor.cs
- src/BootstrapBlazor/Components/Card/Card.razor.js
- test/UnitTest/Components/CardTest.cs
> feat(Card): support collapsing animation and bind collapsed both

- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
update empty resource
close #1875
> doc(Empty): update empty resource

- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/Inputs.razor
- src/BootstrapBlazor/Components/Input/BootstrapInput.razor
- test/UnitTestDocs/MenuTest.cs
> doc(Input): update Input resource

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Card/Card.razor.cs
- src/BootstrapBlazor/Components/Card/Card.razor.js
- test/UnitTest/Components/CardTest.cs
> refactor(Card): use hidden/shown event trigger collapse changed callback

- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/PdfReaders.razor
> doc(PdfReader): update pdfreader resource

- src/BootstrapBlazor.Shared/Samples/Searches.razor.cs
> doc(Search): update search resource key name

- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/SignaturePadPageResponsive.razor
> doc(SignaturePadPageResponsive): update signaturepadpageresponsive resource

- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/RibbonTabs.razor
- src/BootstrapBlazor.Shared/Samples/RibbonTabs.razor.cs
- src/BootstrapBlazor.Shared/Shared/ComponentLayout.razor.css
- src/BootstrapBlazor.Shared/Shared/ComponentLayout.razor.js
- src/BootstrapBlazor/Components/RibbonTab/RibbonTab.razor.cs
- src/BootstrapBlazor/Components/RibbonTab/RibbonTab.razor.js
- test/UnitTest/Components/RibbonTabAnchorTest.cs
- test/UnitTest/Components/RibbonTabTest.cs
- test/UnitTest/Core/RobbinTabTestBase.cs
> feat(Ribbon): support anchor hash

- src/BootstrapBlazor.Shared/Samples/Messages.razor
- src/BootstrapBlazor.Shared/Samples/Messages.razor.cs
- src/BootstrapBlazor/Components/Message/Message.razor
- src/BootstrapBlazor/Components/Message/Message.razor.cs
- test/UnitTest/Components/MessageTest.cs
> fix(Message): incorrect disappearance order when placement is bottom

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Popover/Popover.cs
> fix(Popover): incorrect content when reset Popover content

- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/Charts/Index.razor
- src/BootstrapBlazor.Shared/Samples/DockViews/DockViewIndex.razor
- src/BootstrapBlazor.Shared/Samples/DockViews/Index.razor
> doc(DockView): update index document

- src/BootstrapBlazor/Services/IJSRuntimeEventHandler.cs
- src/BootstrapBlazor/Services/JSRuntimeEventHandler.cs
- src/BootstrapBlazor/wwwroot/modules/event-services.js
RunEval function support return value
close #1917
> feat(JSRuntimeEventHandler): RunEval function support return value

- src/BootstrapBlazor.Shared/Pages/Breakpoints.razor
- src/BootstrapBlazor.Shared/Pages/Install_Maui.razor
- src/BootstrapBlazor.Shared/Pages/Theme.razor
- src/BootstrapBlazor/Components/ImageViewer/ImageViewer.razor.js
- test/UnitTest/Components/MenuTest.cs
- test/UnitTest/Components/MultiSelectTest.cs
> doc(Router): update break point page router

- src/BootstrapBlazor/Components/BaseComponents/BootstrapModuleComponentBase.cs
- src/BootstrapBlazor/Components/Button/Button.razor.cs
- src/BootstrapBlazor/Components/Button/ButtonBase.cs
- src/BootstrapBlazor/Components/Table/ColumnVisibleItem.cs
- src/BootstrapBlazor/Enums/Placement.cs
- test/UnitTest/Performance/RecordTest.cs
> chore(Misc): refactor button code

- src/BootstrapBlazor/Components/Message/Message.razor.js
> refactor(Message): use animation close message popup

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Table/Table.razor
- src/BootstrapBlazor/Components/Table/Table.razor.cs
- test/UnitTest/Components/TableTest.cs
> fix(Table): Table LineNo no work expected after scroll with virtual scroll

- src/BootstrapBlazor/Components/Button/PopConfirmButton.razor
- src/BootstrapBlazor/Components/Button/PopConfirmButton.razor.cs
- test/UnitTest/Components/PopConfirmButtonTest.cs
> fix(PopConfirmButton): can't trigger onclick event when set TooltipText parameter

- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/EditorForms.razor.cs
- src/BootstrapBlazor.Shared/Samples/Table/TablesFixedColumn.razor
- src/BootstrapBlazor.Shared/Samples/Table/TablesFixedColumn.razor.cs
> doc(Table): update fix column sample

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Table/Table.razor.cs
> fix(Table): clear filter on Virtual mode result incorrect

- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
> doc(Upload): update fa-icon link

- src/BootstrapBlazor/Components/AutoComplete/AutoComplete.razor
- src/BootstrapBlazor/Components/AutoComplete/AutoComplete.razor.cs
- src/BootstrapBlazor/Components/AutoComplete/AutoComplete.razor.js
- src/BootstrapBlazor/Components/AutoComplete/PopoverCompleteBase.cs
- src/BootstrapBlazor/Components/AutoFill/AutoFill.razor
- src/BootstrapBlazor/Components/AutoFill/AutoFill.razor.cs
- src/BootstrapBlazor/Components/Input/BootstrapInputBase.cs
- src/BootstrapBlazor/Components/Search/Search.razor
- src/BootstrapBlazor/Components/Search/Search.razor.cs
- src/BootstrapBlazor/wwwroot/modules/utility.js
- test/UnitTest/Components/AutoCompleteTest.cs
- test/UnitTest/Components/AutoFillTest.cs
- test/UnitTest/Components/SearchTest.cs
> refactor(AutoComplete): move parameters into base class

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Table/Table.razor
- test/UnitTest/Components/LayoutTest.cs
- test/UnitTest/Components/TableTest.cs
> fix(Table): virtual scroll support ShowLineNo parameter

- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/CountUps.razor
- src/BootstrapBlazor.Shared/Samples/CountUps.razor.cs
- src/BootstrapBlazor.Shared/Samples/CountUps.razor.css
- src/BootstrapBlazor/Components/CountUp/CountUpOption.cs
- test/UnitTest/Components/CountUpTest.cs
> feat(CountUp): add Numerals parameter support Arabic language

- src/BootstrapBlazor/Components/Table/ITableExportDataContext.cs
- src/BootstrapBlazor/Components/Table/Table.razor.Toolbar.cs
- src/BootstrapBlazor/Components/Table/TableExportDataContext.cs
- src/BootstrapBlazor/Enums/TableExportType.cs
- test/UnitTest/Components/TableTest.cs
> refactor(Table): set ShowExportPdfButton default value to false

- src/BootstrapBlazor.Shared/Components/CustomerFilter.razor
- src/BootstrapBlazor.Shared/Samples/EditorForms.razor.cs
- src/BootstrapBlazor.Shared/Samples/Table/TablesFilter.razor.cs
- src/BootstrapBlazor/Components/Filters/BoolFilter.razor.cs
- src/BootstrapBlazor/Components/Filters/DateTimeFilter.razor.cs
- src/BootstrapBlazor/Components/Filters/EnumFilter.razor.cs
- src/BootstrapBlazor/Components/Filters/FilterBase.cs
- src/BootstrapBlazor/Components/Filters/FilterKeyValueAction.cs
- src/BootstrapBlazor/Components/Filters/IFilterAction.cs
- src/BootstrapBlazor/Components/Filters/LookupFilter.razor.cs
- src/BootstrapBlazor/Components/Filters/NumberFilter.razor.cs
- src/BootstrapBlazor/Components/Filters/SearchFilterAction.cs
- src/BootstrapBlazor/Components/Filters/StringFilter.razor.cs
- src/BootstrapBlazor/Components/Filters/TableFilter.razor.cs
- src/BootstrapBlazor/Components/Table/Table.razor.Search.cs
- src/BootstrapBlazor/Extensions/ITableColumnExtensions.cs
- src/BootstrapBlazor/Extensions/LambdaExtensions.cs
- test/UnitTest/Components/TableBoolFilterTest.cs
- test/UnitTest/Components/TableDateTimeFilterTest.cs
- test/UnitTest/Components/TableEnumFilterTest.cs
- test/UnitTest/Components/TableLookupFilterTest.cs
- test/UnitTest/Components/TableNumberFilterTest.cs
- test/UnitTest/Components/TableStringFilterTest.cs
- test/UnitTest/Components/TableTest.cs
- test/UnitTest/Extensions/ITableColumnExtensionsTest.cs
- test/UnitTest/Extensions/LambadaExtensionsTest.cs
> refactor(Filter): add Filters parameter on FilterKeyValueAction

- src/BootstrapBlazor.Server/wwwroot/css/site.css
- src/BootstrapBlazor.Shared/Samples/LayoutPages.razor
- src/BootstrapBlazor.Shared/Shared/PageLayout.razor.cs
> doc(PageLayout): fix tab not work

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Extensions/IQueryableExtensions.cs
- src/BootstrapBlazor/Extensions/LambdaExtensions.cs
> refactor(Extensions): add enumerable IFilterAction extensions method

- src/BootstrapBlazor/Components/DateTimePicker/DateTimePicker.razor.scss
> refactor(DateTimePicker) : add mixin function

- src/BootstrapBlazor.Server/wwwroot/lib/highlight/cshtml-razor.min.js
- src/BootstrapBlazor.Server/wwwroot/lib/highlight/highlight.min.js
- src/BootstrapBlazor.Shared/Components/Pre.razor
- src/BootstrapBlazor.Shared/Components/Pre.razor.cs
- src/BootstrapBlazor.Shared/Components/Pre.razor.css
- src/BootstrapBlazor.Shared/Components/Pre.razor.js
- test/UnitTest/Components/TableTest.cs
> doc(Pre): update Pre component script

- src/BootstrapBlazor/Services/Internal/HtmlRenderer.cs
- src/BootstrapBlazor/Services/Internal/HtmlRootComponent.cs
- src/BootstrapBlazor/Services/Internal/StaticHtmlRenderer.HtmlWriting.cs
- src/BootstrapBlazor/Services/Internal/StaticHtmlRenderer.cs
> refactor(HtmlRender): add conditional compilation

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Directory.Build.props
- src/Frameworks.props
- src/Version.targets
- src/bundleconfig.props
> chore(NET8): add net8 dependence config

- src/BootstrapBlazor/Components/Tab/Tab.razor.cs
- src/BootstrapBlazor/Extensions/MenuItemExtensions.cs
- test/UnitTest/Components/LayoutTest.cs
- test/UnitTest/Components/TabTest.cs
- test/UnitTest/Extensions/MenuItemExtensionsTest.cs
> feat(Tab): add Menus parameter 

- src/BootstrapBlazor.Shared/Shared/NavMenu.razor
- src/BootstrapBlazor.Shared/Shared/NavMenu.razor.css
- src/BootstrapBlazor.Shared/Shared/NavMenu.razor.js
- test/UnitTest/Components/LayoutTest.cs
- test/UnitTest/Components/TabTest.cs
> doc(Sidebar): add drag adjust width function

- src/Version.targets
- src/bundleconfig.props
> chore(Sass): update sass/bundle/minifier config file

- test/UnitTest/Components/TableTest.cs
- test/UnitTest/Components/TreeViewTest.cs
> chore(Bump): bump version 7.10.0

- .editorconfig
- .github/workflows/auto-pull-request-checks.yml
- .github/workflows/build.yml
- .github/workflows/docker.yml
- .github/workflows/pack.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
- exclusion.dic
- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Select/Select.razor
- src/BootstrapBlazor/Components/Select/Select.razor.cs
> refactor(Select): revert CurrentValueAsString assign

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Table/Table.razor.Edit.cs
- test/UnitTest/Components/TableTest.cs
> feat(Table): support update PageIndex/PageItems in query process

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Table/Table.razor.Search.cs
> feat(Table): custom search support IsDraggable/ShowMaximizeButton

- src/BootstrapBlazor/Components/FullScreen/FullScreen.razor.scss
- src/BootstrapBlazor/wwwroot/scss/bootstrap.blazor.css
> refactor(FullScreen): update scss file

- src/BootstrapBlazor/Components/GroupBox/GroupBox.razor.scss
- src/BootstrapBlazor/wwwroot/scss/bootstrap.blazor.css
> refactor(GroupBox): update scss file

- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/ListViews.razor
- src/BootstrapBlazor.Shared/Samples/ListViews.razor.cs
- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/ListView/ListView.razor
- src/BootstrapBlazor/Components/ListView/ListView.razor.cs
- test/UnitTest/Components/ListViewTest.cs
> feat(ListView): add GroupOrderCallback parameter

- exclusion.dic
- src/BootstrapBlazor.Shared/Samples/Table/TablesFilter.razor.cs
- src/BootstrapBlazor.Shared/Samples/Table/TablesSearch.razor.cs
- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Extensions/LambdaExtensions.cs
- src/BootstrapBlazor/Extensions/QueryPageOptionsExtensions.cs
- src/BootstrapBlazor/Options/QueryPageOptions.cs
- test/UnitTest/Extensions/QueryPageOptionsExtensionsTest.cs
> feat(QueryPageOptions): add ToFilterFunc/ToFilterLambda extensions method

- src/BootstrapBlazor.Shared/Samples/Cameras.razor.cs
- src/BootstrapBlazor/Components/Camera/Camera.razor.js
> refactor(Camera): support switch device by call update

- exclusion.dic
- src/BootstrapBlazor.Shared/Data/Foo.cs
- src/BootstrapBlazor/Attributes/AutoGenerateBaseAttribute.cs
- src/BootstrapBlazor/Attributes/AutoGenerateColumnAttribute.cs
- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Table/Table.razor.Sort.cs
- src/BootstrapBlazor/Components/Table/Table.razor.cs
- src/BootstrapBlazor/Extensions/ITableColumnExtensions.cs
- src/BootstrapBlazor/Extensions/ObjectExtensions.cs
- src/BootstrapBlazor/Utils/Utility.cs
- test/UnitTest/Components/TableTest.cs
- test/UnitTest/Extensions/ITableColumnExtensionsTest.cs
> chore(Table): refactor code improve readability

- src/BootstrapBlazor.Shared/Samples/Table/TablesColumn.razor.cs
- src/BootstrapBlazor/Attributes/AutoGenerateBaseAttribute.cs
- src/BootstrapBlazor/Attributes/AutoGenerateColumnAttribute.cs
- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Switch/NullSwitch.razor.cs
- src/BootstrapBlazor/Extensions/ITableColumnExtensions.cs
- src/BootstrapBlazor/Utils/Utility.cs
- test/UnitTest/Components/LogoutTest.cs
- test/UnitTest/Components/MenuTest.cs
- test/UnitTest/Components/ModalDialogTest.cs
- test/UnitTest/Components/TableTest.cs
- test/UnitTest/Components/TreeViewTest.cs
- test/UnitTest/Components/ValidateTest.cs
- test/UnitTest/Extensions/ITableColumnExtensionsTest.cs
> chore(Table): revert add visible on AutoGenerateBaseAttribute

- README.md
- README.zh-CN.md
- src/BootstrapBlazor.Shared/Pages/Localization.razor
- src/BootstrapBlazor/Components/Checkbox/Checkbox.razor.cs
- src/BootstrapBlazor/Components/Input/BootstrapInputGroup.razor.scss
- src/BootstrapBlazor/Components/Speech/SpeechWave.razor.cs
- src/BootstrapBlazor/Components/Validate/ValidateBase.cs
- src/BootstrapBlazor/Extensions/ObjectExtensions.cs
- src/BootstrapBlazor/Utils/Utility.cs
- test/UniTest.Sass/VariableTest.cs
- test/UnitTest/Components/CheckboxListTest.cs
- test/UnitTest/Components/IPLocatorTest.cs
- test/UnitTest/Components/ValidateTest.cs
> chore(test): update Test

- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/ContextMenus.razor
- src/BootstrapBlazor.Shared/Samples/ContextMenus.razor.cs
- src/BootstrapBlazor/Localization/Json/JsonStringLocalizer.cs
> doc(ContextMenu): add sample code for ContextMenu

- src/BootstrapBlazor/Components/Table/Table.razor.Toolbar.cs
- src/Extensions/DataServices/BootstrapBlazor.DataAccess.PetaPoco/BootstrapBlazor.DataAccess.PetaPoco.csproj
- src/Extensions/DataServices/BootstrapBlazor.DataAccess.PetaPoco/DatabaseExtensions.cs
> feat(PetaPoco): update PetaPoco support OrElse expression

- src/BootstrapBlazor/Components/Filters/EnumFilter.razor
- src/BootstrapBlazor/Components/Filters/EnumFilter.razor.cs
- src/BootstrapBlazor/Components/Filters/TableFilter.razor
- test/UnitTest/Components/TableEnumFilterTest.cs
> feat(EnumFilter): support more then one filter

- src/BootstrapBlazor.Shared/Samples/Table/TablesFixedHeader.razor
- src/BootstrapBlazor/Components/Filters/EnumFilter.razor.cs
- src/BootstrapBlazor/Components/Filters/FilterKeyValueAction.cs
- src/BootstrapBlazor/Components/Filters/TableFilter.razor
- src/BootstrapBlazor/Components/Filters/TableFilter.razor.cs
- src/BootstrapBlazor/Components/Table/Table.razor.cs
- src/Frameworks.props
- test/UnitTest/Components/TableEnumFilterTest.cs
> feat(TableFilter): set multiple filters not work

- src/BootstrapBlazor/Components/Input/FloatingLabel.razor.cs
- test/UnitTest/Components/InputTest.cs
> fix(FloatingLabel): update PlaceHolder parameter

- src/BootstrapBlazor/Components/InputNumber/BootstrapInputNumber.razor.cs
- test/UnitTest/Components/InputNumberTest.cs
> refactor(InputNumber): update step parameter

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/ListGroup/ListGroup.razor
- src/BootstrapBlazor/Components/ListGroup/ListGroup.razor.cs
- test/UnitTest/Components/TableTest.cs
- test/UnitTest/Components/UploadTest.cs
> feat(ListGroup): add ListGroup component

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Select/MultiSelect.razor
> refactor(MultiSelect): remove the label for display text

- test/UnitTest/Components/ListGroupTest.cs
> test(ListGroup): add unit test for ListGroup

- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/Steps.razor
- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Step/Step.razor
- src/BootstrapBlazor/Components/Step/Step.razor.cs
- test/UnitTest/Components/StepTest.cs
> feat(Step): add FinishedTemplate parameter

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Table/Table.razor.Edit.cs
- src/BootstrapBlazor/Components/Table/Table.razor.Toolbar.cs
- test/UnitTest/Components/TableTest.cs
> feat(table): add OnAfterDeleteAsync/OnAfterModifyAsync parameter

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Utils/Utility.cs
- test/UnitTest/Components/TableTest.cs
- test/UnitTest/Utils/UtilityTest.cs
> fix(Table): edit dialog display component support FormatString parameter

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Table/Table.razor.Edit.cs
- src/BootstrapBlazor/Components/Table/Table.razor.cs
- src/BootstrapBlazor/Options/QueryPageOptions.cs
- test/UnitTest/Components/TableTest.cs
> feat(Table): add IsFirstQuery parameter on Table

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Table/Table.razor.Edit.cs
- src/BootstrapBlazor/Components/Table/Table.razor.cs
- test/UnitTest/Components/TableTest.cs
> feat(Table): add IsAutoQueryFirstRender parameter

- src/BootstrapBlazor/Components/ListView/ListView.razor.cs
> fix(ListView): GroupOrderCallback not work

- src/BootstrapBlazor.Shared/Locales/zh.json
修复pop-confirm文档中的 Popover 链接错误
> doc(Popover): update document

- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/Table/Tables.razor.cs
- src/BootstrapBlazor/Attributes/AutoGenerateColumnAttribute.cs
- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Table/ITableColumn.cs
- src/BootstrapBlazor/Components/Table/InternalTableColumn.cs
- src/BootstrapBlazor/Components/Table/TableColumn.cs
- src/BootstrapBlazor/Extensions/ITableColumnExtensions.cs
- test/UnitTest/Attributes/AutoGenerateClassTest.cs
- test/UnitTest/Components/TableColumnTest.cs
- test/UnitTest/Components/TableTest.cs
- test/UnitTest/Extensions/ITableColumnExtensionsTest.cs
- test/UnitTest/Misc/MockTableColumn.cs
> feat(TableColumn): add IsMarkupString parameter

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Table/Table.razor
> fix(Table): filter incorrect after update column visible

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Select/Select.razor.cs
- test/UnitTest/Components/SelectTest.cs
> feat(Select): add DisableItemChangedWhenFirstRender parameter

- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/MultiSelects.razor.cs
- src/BootstrapBlazor.Shared/Samples/Selects.razor.cs
> doc(Select): update document

- src/BootstrapBlazor.Shared/BootstrapBlazor.Shared.csproj
- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/Extensions/Components/BootstrapBlazor.TableExport/BootstrapBlazor.TableExport.csproj
- src/Extensions/Components/BootstrapBlazor.TableExport/ExcelExport.cs
> fix(TableExport): default file extension always csv

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Table/Table.razor.Edit.cs
- src/BootstrapBlazor/Options/QueryPageOptions.cs
> feat(QueryPageOptions): add IsVirtualScroll parameter

- src/BootstrapBlazor/Components/Table/Table.razor.Toolbar.cs
> doc(Table): update ShowEditButton/ShowDeleteButton document

- CHANGELOG.md
- CHANGELOG.zh-CN.md
- src/BootstrapBlazor.Shared/BootstrapBlazor.Shared.csproj
- src/Extensions/Components/BootstrapBlazor.MaterialDesign.Extensions/BootstrapBlazor.MaterialDesign.Extensions.csproj
> doc(ChangeLog): update changelog doc

- src/BootstrapBlazor/Services/DefaultZipArchiveService.cs
- src/BootstrapBlazor/Services/IZipArchiveService.cs
- test/UnitTest/Services/ZipArchiveServiceTest.cs
> feat(IZipArchiveService): add ArchiveDirectory method

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/ValidateForm/ValidateForm.razor.cs
- src/BootstrapBlazor/Extensions/JSModuleExtensions.cs
- src/BootstrapBlazor/Utils/Utility.cs
- test/UnitTest/Components/TableTest.cs
- test/UnitTest/Components/ValidateFormTest.cs
> refactor(JSRuntime): update OpenBlackUrl method

- src/BootstrapBlazor.Shared/Locales/en.json
- src/BootstrapBlazor.Shared/Locales/zh.json
- src/BootstrapBlazor.Shared/Samples/Table/TablesExport.razor
- src/BootstrapBlazor.Shared/Samples/Table/TablesExport.razor.cs
Add an export item that supports exporting data to the clipboard and can be directly pasted into Excel
close #2293
> doc(Table): export data to clipboard

- src/BootstrapBlazor/Components/InputNumber/BootstrapInputNumber.razor.cs
- test/UnitTest/Components/TableTest.cs
> bug(BootstrapInputNumber):  missing Step attribute when TValue is nullable

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Select/Select.razor.cs
- test/UnitTest/Components/SelectTest.cs
> feat(Select): add ClearSearchText method

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Extensions/ITableColumnExtensions.cs
> fix(Table): shown tooltip not in the table cell center

- src/BootstrapBlazor/Components/AnchorLink/AnchorLink.razor.scss
- src/BootstrapBlazor/wwwroot/scss/bootstrap.blazor.css
- src/BootstrapBlazor/wwwroot/scss/bootstrap.blazor.scss
- test/UnitTest/UnitTest.csproj
> refactor(AnchorLink): use scss style

- src/BootstrapBlazor/Components/Avatar/Avatar.razor.scss
- src/BootstrapBlazor/wwwroot/scss/bootstrap.blazor.css
- src/BootstrapBlazor/wwwroot/scss/bootstrap.blazor.scss
> refactor(Avatar): use scss style

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Tab/Tab.razor.cs
> refactor(Tab): revert Items property to IEnumerable

- src/BootstrapBlazor.Shared/BootstrapBlazor.Shared.csproj
- src/Extensions/Components/BootstrapBlazor.Topology/BootstrapBlazor.Topology.csproj
- src/Extensions/Components/BootstrapBlazor.Topology/Components/Topology/Topology.razor
- src/Extensions/Components/BootstrapBlazor.Topology/Components/Topology/Topology.razor.cs
- src/Extensions/Components/BootstrapBlazor.Topology/Components/Topology/Topology.razor.css
> refactor(Topology): update style code

- BootstrapBlazor.sln
- NuGet.Config
- global.json
> chore(Nuget): remove nuget.blazor.zone source

- src/BootstrapBlazor/Components/ValidateForm/ValidateForm.razor.cs
> fix(ValidateForm): async validate failed

- src/BootstrapBlazor/Components/FullScreen/FullScreen.razor.scss
- src/BootstrapBlazor/wwwroot/scss/bootstrap.blazor.css
> refactor(GoTop): update scss use variable

- src/BootstrapBlazor.Shared/Samples/Ips.razor.cs
- src/BootstrapBlazor/Components/IpAddress/IpAddress.razor
- src/BootstrapBlazor/Components/IpAddress/IpAddress.razor.js
> refactor(IpAddress): redesign interaction

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Table/Table.razor.js
- test/UnitTest/Components/PaginationTest.cs
> fix(table): missing drag event when use dynamic data

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/Bundle.props
> refactor(Sass): update Sass pacakge reference

- src/BootstrapBlazor/Components/Layout/Layout.razor.scss
- src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
> refactor(Layout): update scss file use variable

- BootstrapBlazor.sln
- src/BootstrapBlazor.Server/Components/Samples/Lights.razor
- src/BootstrapBlazor/Components/Light/Light.razor.scss
- src/BootstrapBlazor/Components/Table/Table.razor.scss
- src/BootstrapBlazor/Components/ValidateForm/ValidateForm.razor.scss
> refactor(Light): update scss use variable

- src/BootstrapBlazor.Server/Locales/en.json
- src/BootstrapBlazor.Server/Locales/zh.json
- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/AutoComplete/AutoComplete.razor.scss
- src/BootstrapBlazor/Components/Select/Select.razor.scss
- src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
> refactor(AutoComplete): update auto-complete style

- exclusion.dic
- src/BootstrapBlazor.Server/AIChat/Chats.razor
- src/BootstrapBlazor.Server/AIChat/Chats.razor.cs
- src/BootstrapBlazor.Server/AIChat/OAuth/AzureOpenAIUser.cs
- src/BootstrapBlazor.Server/AIChat/OAuth/OAuthHelper.cs
- src/BootstrapBlazor.Server/Extensions/ServicesExtensions.cs
- src/BootstrapBlazor.Server/docs.json
- test/UniTest.Sass/UniTest.Sass.csproj
- test/UniTest.Sass/VariableTest.cs
- test/UnitTest.Localization/Locales/en.json
- test/UnitTest.Localization/Locales/zh.json
- test/UnitTest.Localization/LocalizerEnTest.cs
- test/UnitTest.Localization/LocalizerZhTest.cs
- test/UnitTest.Localization/UnitTest.Localization.csproj
- test/UnitTestDocs/MenuTest.cs
- test/UnitTestDocs/UnitTestDocs.csproj
- test/UnitTestEditor/EditorTest.cs
- test/UnitTestEditor/UnitTestEditor.csproj
> chore(Solution): update project dependence of unit test

- src/BootstrapBlazor.Server/Components/Layout/HomeLayout.razor
- src/BootstrapBlazor.Server/Services/PackageVersionService.cs
- src/BootstrapBlazor.Server/docs.json
> doc(Version): update version string trim suffix

- src/BootstrapBlazor.Server/Components/Samples/Table/TablesColumnResizing.razor
- src/BootstrapBlazor/Components/Table/Table.razor.cs
> refactor: update table resize support fix header

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Captcha/Captcha.razor.js
- test/UnitTest/Components/QueryBuilderTest.cs
> refactor(Captcha): update javascript

- src/BootstrapBlazor/Components/ImageViewer/ImageViewer.razor.cs
- src/BootstrapBlazor/Components/ImageViewer/ImageViewer.razor.js
当前ImageViewer支持点击弹出ImagePreviewer预览，但是只支持图片索引从0开始，较多的场景下需要从指定索引预览，viewer.js支持从指定索引显示，添加相关功能。
> feat(ImageViewer): support display by index

- src/BootstrapBlazor.Server/Locales/en.json
- src/BootstrapBlazor.Server/Locales/zh.json
- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Select/MultiSelect.razor.cs
> fix(Multiple): can't close item when set IsPopover to true

- src/BootstrapBlazor/Components/Filters/TableFilter.razor.cs
- test/UnitTest/Components/ImageTest.cs
- test/UnitTest/Components/TableFilterTest.cs
- test/UnitTest/Components/TableLookupFilterTest.cs
- test/UnitTest/Components/TableTest.cs
> test(Table): add unit test improve code coverage

- src/BootstrapBlazor/Components/ListGroup/ListGroup.razor.scss
- src/BootstrapBlazor/Components/ListView/ListView.razor.scss
- src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
> refactor(ListGrup): use variable in sass file

- src/BootstrapBlazor/Components/Logout/Logout.razor.scss
- src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
> refactor(Logout): use variable in Logout sass file

- src/BootstrapBlazor/Components/Menu/Menu.razor.scss
- src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
> refactor(Menu): use variable in sass file

- src/BootstrapBlazor.Server/Components/Samples/Blocks.razor
- src/BootstrapBlazor.Server/Extensions/ServicesExtensions.cs
> doc(Block): update Block component sample code

- src/BootstrapBlazor.Server/Components/Pages/Coms.razor
- src/BootstrapBlazor.Server/Components/Samples/PdfReaders.razor
- src/BootstrapBlazor.Server/Components/Samples/PdfReaders.razor.cs
1. 修复组件页面链接
2. 修复演示文档实例错误
close #2465
> doc(PdfReader): update search function for Pdf reader 

- src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj
- src/BootstrapBlazor.Server/Components/Components/DataDialogComponent.razor
- src/BootstrapBlazor.Server/Components/Components/InstallContent.razor
- src/BootstrapBlazor.Server/Components/Pages/Install_Server.razor
- src/BootstrapBlazor.Server/Components/Pages/Install_WebApp.razor
- src/BootstrapBlazor.Server/Components/Routes.razor
- src/BootstrapBlazor.Server/Components/_Imports.razor
- src/BootstrapBlazor.Server/Extensions/MenusLocalizerExtensions.cs
- src/BootstrapBlazor.Server/Locales/en.json
- src/BootstrapBlazor.Server/Locales/zh.json
- src/BootstrapBlazor.Server/Program.cs
- src/BootstrapBlazor/Components/BaseComponents/BootstrapBlazorRoot.razor.cs
- src/BootstrapBlazor/Components/Button/DialButton.razor.cs
- src/BootstrapBlazor/Services/BootstrapServiceBase.cs
- test/UnitTest/Components/BootstrapBlazorRootTest.cs
> doc(WebApp): update WebApp document

- src/BootstrapBlazor.Server/Components/Samples/ImageViewers.razor
- src/BootstrapBlazor.Server/Components/Samples/ImageViewers.razor.cs
- src/BootstrapBlazor.Server/Locales/en.json
- src/BootstrapBlazor.Server/Locales/zh.json
- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/ImagePreviewer/ImagePreviewer.razor.cs
- src/BootstrapBlazor/Components/ImagePreviewer/ImagePreviewer.razor.js
- test/UnitTest/Components/ImageTest.cs
给ImagePreiviewer增加了一个Show方法，可以直接显示对应的图片
close #2474
> feat(ImagePreviewer): detach image component

- src/BootstrapBlazor.Server/Components/Pages/Install_WebApp.razor
- src/BootstrapBlazor/Components/QueryBuilder/QueryBuilder.razor.scss
- src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
> refactor(QueryBuilder): use variable in sass file

- src/BootstrapBlazor.Server/Components/Components/BlazorReconnector.razor
- src/BootstrapBlazor.Server/Components/Components/Header.razor
- src/BootstrapBlazor.Server/Components/Components/Header.razor.cs
- src/BootstrapBlazor.Server/Components/Components/UpdateIntro.razor
- src/BootstrapBlazor.Server/Components/Components/UpdateIntro.razor.cs
- src/BootstrapBlazor.Server/Components/Layout/ComponentLayout.razor.cs
- src/BootstrapBlazor.Server/Components/Layout/HomeLayout.razor
- src/BootstrapBlazor.Server/Components/Pages/Install.razor
- src/BootstrapBlazor.Server/Components/Pages/Template.razor.cs
- src/BootstrapBlazor.Server/Components/Samples/Reconnectors.razor
- src/BootstrapBlazor.Server/Components/Samples/Reconnectors.razor.cs
- src/BootstrapBlazor.Server/Components/Samples/Table/TablesColumnTemplate.razor
- src/BootstrapBlazor.Server/Components/Samples/Table/TablesEdit.razor.cs
- src/BootstrapBlazor.Server/Components/Samples/Table/TablesFilter.razor.cs
- src/BootstrapBlazor.Server/Data/WebsiteOptions.cs
- src/BootstrapBlazor.Server/Locales/zh.json
- src/BootstrapBlazor.Server/appsettings.json
- src/BootstrapBlazor/Components/Radio/RadioList.razor.scss
- src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
> refactor(RadioList): update sass style use variable

- src/BootstrapBlazor.Server/Components/Samples/Table/TablesSelection.razor
- src/BootstrapBlazor.Server/Components/Samples/Table/TablesSelection.razor.css
- src/BootstrapBlazor.Server/Locales/en.json
- src/BootstrapBlazor.Server/Locales/zh.json
- src/BootstrapBlazor/Components/Table/Table.razor.Checkbox.cs
> doc(Table): update selection sample code

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Table/Table.razor
- src/BootstrapBlazor/Components/Table/Table.razor.Pagination.cs
- test/UnitTest/Components/TableTest.cs
> feat(Table): add PageInfoBodyTemplate parameter

- src/BootstrapBlazor/Components/Table/Table.razor.Pagination.cs
- src/BootstrapBlazor/Components/Table/Table.razor.js
- src/BootstrapBlazor/Components/Table/Table.razor.scss
> feat(Table): sticky footer on virtulization mode

- src/BootstrapBlazor/Components/Radio/RadioList.razor
> refactor(Radio): add radio-list-group class for button mode

- src/BootstrapBlazor/Components/Button/DialButton.razor.scss
> fix(DialButton): incorrect direction when set Placement to bottom

- .editorconfig
- BootstrapBlazor.sln
- exclusion.dic
- src/BootstrapBlazor.Server/Components/Samples/DialButtons.razor
- src/BootstrapBlazor.Server/Components/Samples/SlideButtons.razor.css
- src/BootstrapBlazor.Server/Components/Samples/Table/TablesVirtualization.razor
- src/BootstrapBlazor/Components/Button/DialButton.razor.scss
> doc(SlideButton): update sampe code for SlideButton

- src/BootstrapBlazor/Components/Console/Console.razor
- src/BootstrapBlazor/Components/Console/Console.razor.cs
- src/BootstrapBlazor/Components/Console/ConsoleMessageItem.cs
- test/UnitTest/Components/ConsoleTest.cs
> feat(Console): add CssClass parameter on ConsoleMessageItem

- src/BootstrapBlazor.Server/Components/Samples/Clipboards.razor
- src/BootstrapBlazor.Server/Components/Samples/Translators.razor
- src/BootstrapBlazor.Server/Extensions/MenusLocalizerExtensions.cs
- src/BootstrapBlazor.Server/Locales/en.json
- src/BootstrapBlazor.Server/Locales/zh.json
> doc(ClipboardService): update sample code

- src/BootstrapBlazor/Components/RibbonTab/RibbonTab.razor.scss
- src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
> refactor(RibbonTab): update sass file use virable

- src/BootstrapBlazor/Components/Row/Row.razor.scss
- src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
> refactor(Row): update sass file use variable

- src/BootstrapBlazor/Components/Scroll/Scroll.razor.scss
- src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
> refactor(Scroll): update sass file use variable

- src/BootstrapBlazor/Components/Select/Select.razor.scss
- src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
> refactor(Select): update sass file use variable

- exclusion.dic
- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Slider/Slider.razor.scss
- src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
> refactor(Slider): update sass file use variable

- src/BootstrapBlazor.Server/Components/Samples/Table/TablesSearch.razor.cs
- src/BootstrapBlazor/Components/Table/Table.razor.Edit.cs
> doc(Table): update search of Table sample code

- src/BootstrapBlazor/Components/Speech/SpeechWave.razor.scss
- src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
> refactor(Speech): update sass file use variable

- src/BootstrapBlazor/Components/Spinner/Spinner.razor.scss
- src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
> refactor(Spinner): update sass file use variable

- src/BootstrapBlazor/Components/Split/Split.razor.scss
- src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
> refactor(Split): update sass file use variable

- src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj
- src/BootstrapBlazor.Server/Components/Samples/MindMaps/MindMaps.razor
- src/BootstrapBlazor.Server/Components/Samples/MindMaps/MindMaps.razor.cs
- src/BootstrapBlazor.Server/Locales/en.json
- src/BootstrapBlazor.Server/Locales/zh.json
> feat(MindMap): add MindMapOptionparameter

- src/BootstrapBlazor.Server/Components/Samples/PdfReaders.razor.cs
- src/BootstrapBlazor.Server/Locales/en.json
- src/BootstrapBlazor.Server/Locales/zh.json
> feat(PdfReader): add LocalFileName parameter

- src/BootstrapBlazor.Server/Components/Samples/Table/TablesFooter.razor
- src/BootstrapBlazor.Server/Components/Samples/Table/TablesVirtualization.razor
- src/BootstrapBlazor.Server/Components/Samples/Table/TablesVirtualization.razor.cs
- src/BootstrapBlazor.Server/Locales/en.json
- src/BootstrapBlazor.Server/Locales/zh.json
- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Input/BootstrapInputGroup.razor.scss
- src/BootstrapBlazor/Components/Table/Table.razor
- src/BootstrapBlazor/Components/Table/Table.razor.cs
- src/BootstrapBlazor/Components/Table/Table.razor.scss
- test/UnitTest/Components/TableTest.cs
> feat(Table): add IsFixedFooter parameter

- src/BootstrapBlazor.Server/Components/Samples/Tabs.razor
- src/BootstrapBlazor/Components/Tab/Tab.razor.scss
- src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
> refactor(Tab): update sass file use variable

- src/BootstrapBlazor.Server/Components/Samples/Tags.razor
- src/BootstrapBlazor/Components/Tag/Tag.razor.scss
- src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
> refactor(Tag): update sass file use variable

- src/BootstrapBlazor/Extensions/BootstrapBlazorServiceCollectionExtensions.cs
- src/BootstrapBlazor/Services/DefaultExportPdf.cs
- src/BootstrapBlazor/Services/IExportPdf.cs
> feat(IExportPdf): rename ITableExportPdf to IExportPdf

- .editorconfig
- src/BootstrapBlazor.Server/Extensions/ServicesExtensions.cs
- src/BootstrapBlazor.Server/Services/ExportPdfService.cs
> refactor(ExporPdf): update ExportPdfService

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Services/IExportPdf.cs
> doc(IExportPdf): update doc for IExportPdf

- exclusion.dic
- src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj
- src/BootstrapBlazor.Server/Components/Samples/Html2Pdfs.razor.cs
- src/Extensions/Components/BootstrapBlazor.MaterialDesign.Extensions/BootstrapBlazor.MaterialDesign.Extensions.csproj
- src/Extensions/Components/BootstrapBlazor.TableExport/BootstrapBlazor.TableExport.csproj
- src/Extensions/Components/BootstrapBlazor.TableExport/Services/DefaultTableExport.cs
> doc(TableExport): update package

- src/BootstrapBlazor.Server/Services/ExportPdfService.cs
- src/Extensions/Components/BootstrapBlazor.Html2Pdf/BootstrapBlazor.Html2Pdf.csproj
- src/Extensions/Components/BootstrapBlazor.Html2Pdf/Extensions/ServiceCollectionExtensions.cs
> refactor(Html2Pdf): use TryAddSingleton inject

- src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj
- src/BootstrapBlazor.Server/Components/Samples/Topologies.razor
- src/BootstrapBlazor.Server/Components/Samples/Topologies.razor.cs
- src/Extensions/Components/BootstrapBlazor.Topology/BootstrapBlazor.Topology.csproj
- src/Extensions/Components/BootstrapBlazor.Topology/Components/Topology/Topology.razor.js
> refactor(Topology): update Resize method

- src/BootstrapBlazor.Server/Components/Components/GlobalSearch.razor.cs
- src/BootstrapBlazor.Server/Extensions/MenusLocalizerExtensions.cs
- src/BootstrapBlazor/Components/Menu/Menu.razor.cs
- src/BootstrapBlazor/Components/Menu/Menu.razor.js
> doc(SideMenu): add auto scroll to view function

- src/BootstrapBlazor.Server/Components/Samples/Charts/Line.razor
- src/BootstrapBlazor/Components/Timer/Timer.razor.scss
- src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
> doc(Timer): update sass file use variable

- src/BootstrapBlazor.Server/Components/Samples/Dialogs.razor
- src/BootstrapBlazor/Components/Dialog/Dialog.razor.cs
- src/BootstrapBlazor/Components/Drawer/Drawer.razor.scss
- src/BootstrapBlazor/Components/Modal/Modal.razor.cs
- src/BootstrapBlazor/Components/Toggle/Toggle.razor.scss
- src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
> doc(Toggle): update sass file use variable

- src/BootstrapBlazor.Server/Components/Samples/Transfers.razor
- src/BootstrapBlazor/Components/Transfer/Transfer.razor.scss
- src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
> doc(Transfer): update sass file use variable

- src/BootstrapBlazor.Server/Components/Samples/TreeViews.razor
- src/BootstrapBlazor.Server/Locales/en.json
- src/BootstrapBlazor.Server/Locales/zh.json
- src/BootstrapBlazor/Components/TreeView/TreeView.razor.scss
- src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
> doc(TreeView): update sass file use variable

- src/BootstrapBlazor.Server/Components/Samples/Uploads.razor
- src/BootstrapBlazor/Components/Upload/ButtonUpload.razor
- src/BootstrapBlazor/Components/Upload/UploadBase.razor.scss
- src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
- test/UnitTest/Components/ToastTest.cs
> doc(Upload): update sass file use variable

- src/BootstrapBlazor.Server/Program.cs
- src/BootstrapBlazor/Components/IPLocator/DefaultIPLocator.cs
> doc(Locator): add CodePagesEncodingProvider support gbk

- src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj
> doc(Logging): upgrade to net8

- src/BootstrapBlazor.Server/Components/Samples/GlobalException.razor
- src/BootstrapBlazor.Server/Components/Samples/Table/TablesFilter.razor.cs
- test/UnitTest/Performance/StringExtensionsTest.cs
> doc(CustomFilter): update sample code link

- exclusion.dic
- src/BootstrapBlazor.Server/Components/Components/Header.razor
- src/BootstrapBlazor.Server/Components/Components/Header.razor.cs
- src/BootstrapBlazor.Server/Components/Components/Header.razor.css
- src/BootstrapBlazor.Server/Components/Components/ThemeChooser.razor.cs
- src/BootstrapBlazor.Server/Components/Layout/HomeLayout.razor
- src/BootstrapBlazor.Server/Services/PackageVersionService.cs
> doc(Header): hide version on mobile mode

- src/BootstrapBlazor.Server/Components/Layout/HomeLayout.razor
> doc(Lang): update switch lang in footer

- src/BootstrapBlazor/Components/ListGroup/ListGroup.razor.scss
- src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
> refactor(ListGroup): support dark theme

- src/BootstrapBlazor/Components/Segmented/Segmented.razor.scss
- src/BootstrapBlazor/wwwroot/scss/bootstrap.blazor-dark.scss
- src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
> refactor(Segmented): support dark theme

- src/BootstrapBlazor/Components/Button/DialButton.razor.scss
- src/BootstrapBlazor/wwwroot/scss/bootstrap.blazor-dark.scss
- src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
> refactor(dial-button): suppor dark theme

- src/BootstrapBlazor/Components/ContextMenu/ContextMenu.razor.scss
> fix(ContextMenu): not shown in Modal/Dialog

- src/BootstrapBlazor/Attributes/AutoGenerateColumnAttribute.cs
- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/EditorForm/EditorItem.cs
- src/BootstrapBlazor/Components/EditorForm/IEditorItem.cs
- src/BootstrapBlazor/Components/Filters/TableFilter.razor.cs
- src/BootstrapBlazor/Components/InputNumber/BootstrapInputNumber.razor.cs
- src/BootstrapBlazor/Components/Table/InternalTableColumn.cs
- src/BootstrapBlazor/Components/Table/TableColumn.cs
- src/BootstrapBlazor/Utils/Utility.cs
- test/UnitTest/Attributes/AutoGenerateClassTest.cs
- test/UnitTest/Components/EditorFormTest.cs
- test/UnitTest/Components/InputNumberTest.cs
- test/UnitTest/Components/TableColumnTest.cs
- test/UnitTest/Components/TableFilterTest.cs
- test/UnitTest/Extensions/ITableColumnExtensionsTest.cs
- test/UnitTest/Misc/MockTableColumn.cs
> feat(InputNumber): step support any value

- src/BootstrapBlazor.Server/Components/Samples/ImageViewers.razor.css
- src/BootstrapBlazor.Server/Components/Samples/Practices/Waterfall.razor.cs
- src/BootstrapBlazor/Components/Skeleton/Skeleton.razor.scss
- src/BootstrapBlazor/Components/Skeleton/SkeletonEditor.razor
- src/BootstrapBlazor/Components/Skeleton/SkeletonTable.razor
- src/BootstrapBlazor/Components/Table/Table.razor.scss
- src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
- src/BootstrapBlazor/wwwroot/src/css/motronic.css
> doc(Skeleton): support dark theme

- src/BootstrapBlazor/Components/Split/Split.razor.scss
- src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
> refactor(Split): support dark theme

- src/BootstrapBlazor.Server/Components/Samples/GoTops.razor
- src/BootstrapBlazor.Server/Components/Samples/Stacks.razor.css
- src/BootstrapBlazor/Components/Split/Split.razor.scss
- src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
> doc(GoTop): update sample code support dark theme

- src/BootstrapBlazor/Components/Radio/RadioList.razor.scss
- src/BootstrapBlazor/Components/Select/MultiSelect.razor.scss
- src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
> refactor(MultiSelect): support dark theme

- src/BootstrapBlazor.Server/Components/Samples/Table/TablesDialog.razor
- src/BootstrapBlazor.Server/Components/Samples/Table/TablesFixedColumn.razor
- src/BootstrapBlazor.Server/Components/Samples/Table/TablesFooter.razor
- src/BootstrapBlazor.Server/Components/Samples/Table/TablesFooter.razor.css
- src/BootstrapBlazor.Server/Components/Samples/Table/TablesHeader.razor
- src/BootstrapBlazor.Server/Components/Samples/Table/TablesLoading.razor
- src/BootstrapBlazor.Server/Components/Samples/Table/TablesTree.razor
- src/BootstrapBlazor.Server/Locales/en.json
- src/BootstrapBlazor.Server/Locales/zh.json
- src/BootstrapBlazor.Server/wwwroot/css/site.css
- src/BootstrapBlazor/Components/Scroll/Scroll.razor.scss
- src/BootstrapBlazor/Components/Segmented/Segmented.razor.scss
- src/BootstrapBlazor/Components/Table/Table.razor.scss
- src/BootstrapBlazor/Components/Transfer/Transfer.razor.scss
- src/BootstrapBlazor/wwwroot/scss/bootstrap.blazor-dark.scss
- src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
> doc(Table): update sample code support dark theme

- src/BootstrapBlazor/BootstrapBlazor.csproj
- src/BootstrapBlazor/Components/Table/Table.razor.cs
> fix(Table): append component parameters for edit template

- src/BootstrapBlazor/Components/Calendar/Calendar.razor.cs
- src/BootstrapBlazor/Components/Captcha/Captcha.razor.scss
- src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
> refactor(Captcha): update sass file support dark theme

- src/BootstrapBlazor.Server/Components/Samples/Carousels.razor.css
- src/BootstrapBlazor/Components/Carousel/Carousel.razor.scss
- src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
> doc(Carousel): support dark theme

- src/BootstrapBlazor/Components/Circle/Circle.razor
- src/BootstrapBlazor/Components/Circle/Circle.razor.scss
- src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
> refactor(Circle): update sass file support dark theme

- src/Extensions/Components/BootstrapBlazor.TableExport/BootstrapBlazor.TableExport.csproj
- src/Extensions/Components/BootstrapBlazor.TableExport/Extensions/TableExportServiceCollectionExtensions.cs
> fix(TableExport): not register table export service

- src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj
- src/BootstrapBlazor.Server/Components/Samples/Table/TablesExport.razor
- src/BootstrapBlazor.Server/Extensions/ServicesExtensions.cs
- src/Extensions/Components/BootstrapBlazor.TableExport/BootstrapBlazor.TableExport.csproj
- src/Extensions/Components/BootstrapBlazor.TableExport/Extensions/TableExportServiceCollectionExtensions.cs
> chore(TableExport): rename AddBootstrapBlazorTableExcelExport

- src/BootstrapBlazor/Components/Collapse/Collapse.razor.scss
- src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
- src/BootstrapBlazor/wwwroot/src/css/motronic.css
> refactor(Collapse): update sass file support dark mode

- src/BootstrapBlazor.Server/Components/Samples/DropdownWidgets.razor.css
- src/BootstrapBlazor/Components/DropdownWidget/DropdownWidget.razor.scss
- src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
> chore(Widget): update sass file support dark theme

- src/BootstrapBlazor.Server/Data/TreeFoo.cs
- src/BootstrapBlazor/Components/TreeView/TreeView.razor.cs
- src/BootstrapBlazor/Components/TreeView/TreeViewItem.cs
- src/BootstrapBlazor/Extensions/IModelEqualityComparerExtensions.cs
- test/UnitTest/Components/TreeViewTest.cs
> test(TreeView): add SetActiveItem unit test

- src/BootstrapBlazor.Server/Components/Samples/FileViewers.razor
- src/BootstrapBlazor.Server/Components/Samples/Print.razor
- src/BootstrapBlazor.Server/Components/Samples/Print.razor.cs
- src/BootstrapBlazor.Server/Components/Samples/TreeViews.razor.cs
- src/BootstrapBlazor.Server/Data/TreeFoo.cs
- src/BootstrapBlazor.Server/Extensions/MenusLocalizerExtensions.cs
- src/BootstrapBlazor/Components/ImageViewer/ImageViewer.razor.scss
- src/BootstrapBlazor/Utils/JSModule.cs
> doc(Title): update sample code for dark theme

- src/BootstrapBlazor.Server/Extensions/MenusLocalizerExtensions.cs
- src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
> refactor(TreeView): update sass file support dark theme

- src/BootstrapBlazor.Server/Components/Samples/Reconnectors.razor
- src/BootstrapBlazor/Components/Drawer/Drawer.razor.scss
- src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
> refactor(Drawer): support dark theme

- src/BootstrapBlazor/Components/Toast/ToastContainer.razor.scss
> refactor(Toast): support dark theme

- src/BootstrapBlazor.Server/Components/Layout/BaseLayout.razor
- src/BootstrapBlazor.Server/Components/Layout/BaseLayout.razor.cs
- src/BootstrapBlazor.Server/Components/Layout/BaseLayout.razor.css
- src/BootstrapBlazor.Server/Locales/en.json
- src/BootstrapBlazor.Server/Locales/zh.json
> doc(Theme): add Theme mode button
