dotnetcore/BootstrapBlazor

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/BootstrapBlazor.Server/Services/ClearUploadFilesService.cs, src/BootstrapBlazor.Server/appsettings.Development.json, src/BootstrapBlazor.Server/appsettings.json
=> chore(Package): update Task/Logging version to 8.0

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Extensions/LocalizationOptionsExtensions.cs
=> feat(Localization): import localization logic auto load entry assembly

src/BootstrapBlazor.Server/Components/App.razor, src/BootstrapBlazor/Components/HtmlTag/Link.razor, src/BootstrapBlazor/Components/HtmlTag/Link.razor.cs, test/UnitTest/Components/LinkTest.cs
=> feat(Link): add Link component

src/BootstrapBlazor.Server/Components/Components/GlobalSearch.razor.cs, src/BootstrapBlazor.Server/Locales/en.json, src/BootstrapBlazor.Server/Locales/zh.json, src/BootstrapBlazor.Server/Services/MenuService.cs
=> doc(PopConfirmButton): update document for PopConfirmButton

src/BootstrapBlazor/Extensions/ITableColumnExtensions.cs
=> fix(ITableColumn): update check Step value

src/BootstrapBlazor.Server/Components/Samples/Toasts.razor, src/BootstrapBlazor/Components/Toast/ToastService.cs, src/BootstrapBlazor/Extensions/ToastServiceExtensions.cs
=> feat(Toast): update extensions method set Title nullable

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Table/Table.razor.Edit.cs, src/BootstrapBlazor/Components/Table/Table.razor.Toolbar.cs
=> fix(Table): throw exception when DynamicContext is null

exclusion.dic, src/BootstrapBlazor.Server/Components/Samples/CountUps.razor, src/BootstrapBlazor.Server/Components/Samples/Dialogs.razor, src/BootstrapBlazor.Server/Components/Samples/DockViews/Index.razor, src/BootstrapBlazor.Server/Components/Samples/Downloads.razor, src/BootstrapBlazor.Server/Components/Samples/GlobalException.razor, src/BootstrapBlazor.Server/Components/Samples/Html2Pdfs.razor, src/BootstrapBlazor.Server/Components/Samples/JSRuntimeExtensions.razor, src/BootstrapBlazor.Server/Components/Samples/LayoutPages.razor, src/BootstrapBlazor.Server/Components/Samples/Live2DDisplays.razor, src/BootstrapBlazor.Server/Components/Samples/Locators.razor, src/BootstrapBlazor.Server/Components/Samples/Reconnectors.razor, src/BootstrapBlazor.Server/Components/Samples/Speeches/Index.razor, src/BootstrapBlazor.Server/Components/Samples/Splittings.razor, src/BootstrapBlazor.Server/Components/Samples/Steps.razor, src/BootstrapBlazor.Server/Components/Samples/Table/TablesFilter.razor, src/BootstrapBlazor.Server/Components/Samples/Table/TablesFixedHeader.razor, src/BootstrapBlazor.Server/Components/Samples/Table/TablesRow.razor, src/BootstrapBlazor.Server/Components/Samples/Table/TablesSearch.razor, src/BootstrapBlazor.Server/Components/Samples/ZipArchives.razor, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json
=> doc(Web): update sample code

src/BootstrapBlazor.Server/Components/Samples/Table/TablesFooter.razor
=> doc(TableFooter): add key for update count value

src/.config/dotnet-tools.json, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Services/CacheManager.cs
=> refactor(CacheManager): update Clear function

src/.config/dotnet-tools.json, src/Version.targets
=> chore(JsVesion): bump javascript version tool 1.1.3

src/Extensions/DataServices/BootstrapBlazor.DataAccess.EntityFrameworkCore/BootstrapBlazor.DataAccess.EntityFrameworkCore.csproj, src/Extensions/DataServices/BootstrapBlazor.DataAccess.EntityFrameworkCore/DefaultDataService.cs, src/Extensions/DataServices/BootstrapBlazor.DataAccess.EntityFrameworkCore/IQueryableExtensions.cs, src/Extensions/DataServices/BootstrapBlazor.DataAccess.FreeSql/BootstrapBlazor.DataAccess.FreeSql.csproj, src/Extensions/DataServices/BootstrapBlazor.DataAccess.FreeSql/DefaultDataService.cs, src/Extensions/DataServices/BootstrapBlazor.DataAccess.PetaPoco/BootstrapBlazor.DataAccess.PetaPoco.csproj, src/Extensions/DataServices/BootstrapBlazor.DataAccess.PetaPoco/DefaultDataService.cs
=> fix(DefaltDataService): compatible pager/virtual-scroll mode

src/BootstrapBlazor.Server/Components/Samples/Table/TablesFooter.razor, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Table/Table.razor, src/BootstrapBlazor/Components/Table/TableFooterCell.razor, src/BootstrapBlazor/Components/Table/TableFooterCell.razor.cs, src/Extensions/DataServices/BootstrapBlazor.DataAccess.PetaPoco/BootstrapBlazor.DataAccess.PetaPoco.csproj
=> refactor(TableFooter): add Key on tfoot

src/BootstrapBlazor.Server/Components/Layout/PageLayout.razor.cs, src/BootstrapBlazor.Server/Components/Layout/PageLayout.razor.css, src/BootstrapBlazor.Server/wwwroot/css/site.css
=> doc(Layout): update Layout sample

src/BootstrapBlazor.Server/Components/Samples/Print.razor, src/BootstrapBlazor.Server/Components/Samples/PrintView.razor, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Modal/Modal.razor.scss, src/BootstrapBlazor/Components/Print/Print.cs
=> fix(Print): update Print compatible net8

src/BootstrapBlazor.Server/Components/Layout/TutorialsNavMenu.razor.cs, src/BootstrapBlazor.Server/Components/Samples/Tutorials/DrawingApp.razor, src/BootstrapBlazor.Server/Components/Samples/Tutorials/DrawingApp.razor.cs, src/BootstrapBlazor.Server/Components/Samples/Tutorials/DrawingApp.razor.css, src/BootstrapBlazor.Server/Components/Samples/Tutorials/DrawingApp.razor.js
This PR adds a simple drawing tutorial to the application, providing users with a clear starting point for exploring the drawing functionality. The tutorial includes step-by-step instructions for selecting colors, using the brush tool, and saving drawings. Visual aids such as screenshots and diagrams have been included to enhance the tutorial's accessibility and ease of use.
close #2758
=> doc(Tutorial): Add Drawing Tutorial

src/BootstrapBlazor.Server/Components/Samples/Table/TablesToolbar.razor, src/BootstrapBlazor.Server/Extensions/MenusLocalizerExtensions.cs, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Upload/UploadBase.razor.scss
=> feat(Table): toolbar compatible ButtonUpload component

src/BootstrapBlazor/Components/ListView/ListView.razor, src/BootstrapBlazor/Components/ListView/ListView.razor.cs, src/BootstrapBlazor/Components/Upload/ButtonUploadBase.cs, src/BootstrapBlazor/Extensions/LambdaExtensions.cs, src/BootstrapBlazor/Extensions/ObjectExtensions.cs, src/BootstrapBlazor/Utils/Utility.cs, test/UnitTest/Components/UploadTest.cs
=> test(Utility): improve code coverage

src/BootstrapBlazor.Server/Components/Samples/Ips.razor, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/IpAddress/IpAddress.razor.scss
=> fix(IpAddress): missing disabled sass variable

src/BootstrapBlazor.Server/Components/Pages/Coms.razor, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Extensions/ToastServiceExtensions.cs
=> chore(Toast): revert extensions method modify

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Pagination/Pagination.razor.scss, src/BootstrapBlazor/Components/Pagination/PaginationItem.razor
=> fix(Pagination): compatible wasm mode

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Table/Table.razor.Toolbar.cs, src/BootstrapBlazor/Dynamic/DynamicObjectContext.cs, src/BootstrapBlazor/Dynamic/IDynamicObjectContext.cs, test/UnitTest/Components/TableTest.cs
=> feat(IDynamicContext): add OnFilterCallback method

src/BootstrapBlazor.Server/Components/Samples/Cards.razor, src/BootstrapBlazor/Components/Card/Card.razor.scss
=> refactor(Card): update style of HeaderTemplate

src/BootstrapBlazor.Server/Components/Samples/Dialogs.razor, src/BootstrapBlazor.Server/Components/Samples/Displays.razor, src/BootstrapBlazor.Server/Components/Samples/Html2Pdfs.razor, src/BootstrapBlazor.Server/Components/Samples/Inputs.razor, src/BootstrapBlazor.Server/Components/Samples/MultiSelects.razor, src/BootstrapBlazor.Server/Components/Samples/RibbonTabs.razor, src/BootstrapBlazor.Server/Components/Samples/Stacks.razor, src/BootstrapBlazor.Server/Components/Samples/Steps.razor, src/BootstrapBlazor.Server/Components/Samples/Switches.razor, src/BootstrapBlazor.Server/Components/Samples/Table/TablesColumnResizing.razor, src/BootstrapBlazor.Server/Components/Samples/Table/TablesEdit.razor, src/BootstrapBlazor.Server/Components/Samples/Table/TablesFilter.razor, src/BootstrapBlazor.Server/Components/Samples/Table/TablesFooter.razor, src/BootstrapBlazor.Server/Components/Samples/Table/TablesRow.razor, src/BootstrapBlazor.Server/Components/Samples/Table/TablesVirtualization.razor, src/BootstrapBlazor.Server/Components/Samples/Tabs.razor, src/BootstrapBlazor.Server/Components/Samples/Timelines.razor, src/BootstrapBlazor.Server/Components/Samples/Transfers.razor, src/BootstrapBlazor.Server/Components/Samples/TreeViews.razor, src/BootstrapBlazor.Server/Components/Samples/ValidateForms.razor, src/BootstrapBlazor.Server/wwwroot/css/site.css, src/BootstrapBlazor/Components/Table/Table.razor.cs
=> doc(Section): remove margin-top/bottom style

src/BootstrapBlazor.Server/Components/Samples/Toasts.razor, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json
=> doc(Toast): update Toast sample code

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Table/Table.razor.js, src/BootstrapBlazor/Utils/JSModule.cs
=> fix(Table): throw exception when click refresh button on browser

src/BootstrapBlazor/Components/Table/Table.razor.js, src/BootstrapBlazor/wwwroot/modules/utility.js
=> fix(Table): setBodyHeight incorrect when invisible

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Input/BootstrapInputGroup.razor.scss, src/BootstrapBlazor/Components/Table/ITableToolbarButton.cs, src/BootstrapBlazor/Components/Table/IToolbarComponent.cs, src/BootstrapBlazor/Components/Table/TableToolbar.razor, src/BootstrapBlazor/Components/Table/TableToolbar.razor.cs, src/BootstrapBlazor/Components/Table/TableToolbarComponent.cs, src/BootstrapBlazor/Utils/JSModule.cs, src/BootstrapBlazor/wwwroot/scss/root.scss, test/UnitTest/Components/TableTest.cs, test/UnitTest/Utils/JSModuleTest.cs
=> feat(Table): add TableToolbarComponent

src/BootstrapBlazor.Server/Components/Samples/Table/TablesToolbar.razor, src/BootstrapBlazor.Server/Components/Samples/Table/TablesToolbar.razor.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Table/ITableToolbarButton.cs, src/BootstrapBlazor/Components/Table/IToolbarComponent.cs, src/BootstrapBlazor/Components/Table/TableToolbar.razor.cs, src/BootstrapBlazor/Components/Table/TableToolbarComponent.cs
=> doc(Table): add TableToolbarComponent sample code

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/ValidateForm/ValidateForm.razor.scss
=> fix(BootstrapInputGroupLabel): required attribute not work

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/ListGroup/ListGroup.razor.scss
=> fix(ListGroup): list-group-item background color incorrect

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Select/MultiSelect.razor, src/BootstrapBlazor/Components/Select/MultiSelect.razor.cs
=> perf(MultiSelect): reduce one rendering and improve performance

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Extensions/BootstrapBlazorServiceCollectionExtensions.cs
=> fix(Localization): set DefaultCultureInfo not work in code

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Menu/Menu.razor.scss
=> fix(Menu): missing color of nav-link

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Drawer/Drawer.razor.scss
=> fix(Drawer): body missing padding variable

src/BootstrapBlazor/Utils/JSModule.cs, test/UnitTest/Utils/JSModuleTest.cs
=> fix(JSModule): missing JSException

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Select/MultiSelect.razor.cs, src/BootstrapBlazor/Components/Select/Select.razor.cs, src/BootstrapBlazor/Components/Table/Table.razor.Edit.cs, src/BootstrapBlazor/Components/Table/Table.razor.cs
=> doc(Table): update comments #2820

src/BootstrapBlazor.Server/Components/Samples/SelectTables.razor, src/BootstrapBlazor.Server/Components/Samples/SelectTables.razor.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Filters/TableFilter.razor.cs, src/BootstrapBlazor/Components/Select/SelectTable.razor, src/BootstrapBlazor/Components/Select/SelectTable.razor.cs, src/BootstrapBlazor/Components/Select/SelectTable.razor.js, src/BootstrapBlazor/Components/Table/Table.razor.cs, src/BootstrapBlazor/Components/Transfer/Transfer.razor.cs, src/BootstrapBlazor/Validators/RequiredValidator.cs
=> refactor(SelectTable): add resize observer table width

src/BootstrapBlazor.Server/Components/Samples/Table/TablesFilter.razor, src/BootstrapBlazor.Server/Components/Samples/Table/TablesFilter.razor.cs, src/BootstrapBlazor.Server/Components/Samples/Table/TablesSelection.razor, src/BootstrapBlazor.Server/Components/Samples/Table/TablesSelection.razor.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Table/Table.razor.Edit.cs, src/BootstrapBlazor/Components/Table/Table.razor.Pagination.cs, src/BootstrapBlazor/Components/Table/Table.razor.cs
=> fix(Table): reset sort by default sort setting when set bind-SelectedRow

src/BootstrapBlazor.Server/Components/Samples/SelectTables.razor, src/BootstrapBlazor.Server/Components/Samples/SelectTables.razor.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Select/SelectTable.razor, src/BootstrapBlazor/Components/Select/SelectTable.razor.cs, src/BootstrapBlazor/Components/Select/SelectTable.razor.js, test/UnitTest/Components/SelectTableTest.cs
=> feat(SelectTable): add TableMinWidth parameter

src/BootstrapBlazor.Server/Components/Samples/Uploads.razor, src/BootstrapBlazor/Components/Upload/AvatarUpload.razor, src/BootstrapBlazor/Components/Upload/CardUpload.razor, src/BootstrapBlazor/Components/Upload/CardUpload.razor.cs, src/BootstrapBlazor/Components/Upload/SingleUploadBase.cs, test/UnitTest/Components/UploadTest.cs
=> feat(Upload): add Max parameter

src/BootstrapBlazor.Server/Components/Samples/SelectTables.razor, src/BootstrapBlazor.Server/Components/Samples/SelectTables.razor.cs, src/BootstrapBlazor/Components/QueryBuilder/QueryGroup.cs, src/BootstrapBlazor/Components/Rate/Rate.razor.cs, src/BootstrapBlazor/Components/Select/SelectTable.razor, src/BootstrapBlazor/Components/Select/SelectTable.razor.cs, src/BootstrapBlazor/Components/Select/SelectTree.razor.js, src/BootstrapBlazor/Components/Table/IColumnCollection.cs, src/BootstrapBlazor/Components/Table/ITable.cs, src/BootstrapBlazor/Components/Table/TableColumn.cs, src/BootstrapBlazor/Extensions/DialogServiceExtensions.cs, test/UnitTest/Components/SelectTableTest.cs
=> feat(SelectTable): support Sort/Filter/Search function

src/BootstrapBlazor/Components/Card/Card.razor.scss, src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
=> bug(Card): arrow does not rotate on the header

src/BootstrapBlazor/Components/Button/PopConfirmButton.razor, src/BootstrapBlazor/Components/Button/PopConfirmButton.razor.cs
=> fix(DynamicElement): rename Name to TagName

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/ResizeNotification/ResizeNotification.cs, test/UnitTest/Components/ResponsiveTest.cs, test/UnitTest/Components/TableTest.cs
=> refactor(BreakPoint): update BreakPoint parse function

src/BootstrapBlazor/Components/Button/SlideButton.razor, src/BootstrapBlazor/Components/Button/SlideButton.razor.cs, test/UnitTest/Components/SlideButtonTest.cs
=> feat(SlideButton): add ButtonItemTemplate parameter

src/BootstrapBlazor/Components/Button/SlideButton.razor, src/BootstrapBlazor/Components/Button/SlideButton.razor.cs, test/UnitTest/Components/SlideButtonTest.cs
=> feat(SlideButton): add HeaderTemplate parameter

src/BootstrapBlazor/BootstrapBlazor.csproj, test/UnitTest/Components/SelectTableTest.cs
=> test(SelectTable): add unit test improve code coverage

src/BootstrapBlazor.Server/Components/Samples/Table/Tables.razor, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Button/SlideButton.razor.cs, src/BootstrapBlazor/Components/ResizeNotification/ResizeNotification.cs
=> fix(Responsive): add IgnoreCase parameter

src/BootstrapBlazor.Server/Components/Components/ValueCounter.razor, src/BootstrapBlazor.Server/Components/Samples/SelectObjects.razor, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Table/Table.razor.Edit.cs, src/BootstrapBlazor/Components/Table/Table.razor.Search.cs, src/BootstrapBlazor/Components/Table/Table.razor.Toolbar.cs, src/BootstrapBlazor/Dynamic/DynamicObjectContext.cs, src/BootstrapBlazor/Dynamic/IDynamicObjectContext.cs, src/BootstrapBlazor/Extensions/QueryPageOptionsExtensions.cs, test/UnitTest/Components/TableTest.cs
=> feat(Table): dynamic table support filter

.github/workflows/build.yml, .github/workflows/docker.yml, .github/workflows/pack.yml, .github/workflows/publish.yml, .github/workflows/release.yml, src/BootstrapBlazor.Server/Components/Samples/TreeViews.razor, src/BootstrapBlazor.Server/Components/Samples/TreeViews.razor.cs, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/TreeView/TreeView.razor, src/BootstrapBlazor/Components/TreeView/TreeView.razor.cs, src/BootstrapBlazor/Components/TreeView/TreeView.razor.scss, test/UnitTest/Components/TreeViewTest.cs
=> test(TreeView): add unit test improve code coverage

src/BootstrapBlazor.Server/Components/Pages/Chats.razor, src/BootstrapBlazor.Server/Components/Pages/Chats.razor.cs, src/BootstrapBlazor.Server/Components/Pages/Chats.razor.css, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/Components/BrowserFinger/BrowserFinger.razor, src/BootstrapBlazor/Components/BrowserFinger/BrowserFinger.razor.cs, src/BootstrapBlazor/Components/BrowserFinger/BrowserFinger.razor.js, src/BootstrapBlazor/Components/ResizeNotification/Responsive.cs, src/BootstrapBlazor/Extensions/BootstrapBlazorServiceCollectionExtensions.cs, src/BootstrapBlazor/Services/DefaultBrowserFingerService.cs, src/BootstrapBlazor/Services/IBrowserFingerService.cs, test/UnitTest/Services/BrowserFingerServiceTest.cs
=> feat(BrowserFinger): add IBrowserFingerService

src/BootstrapBlazor.Server/Components/Pages/Chats.razor, src/BootstrapBlazor.Server/Components/Samples/BrowserFingers.razor, src/BootstrapBlazor.Server/Components/Samples/BrowserFingers.razor.cs, src/BootstrapBlazor.Server/Extensions/MenusLocalizerExtensions.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor.Server/docs.json, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/BaseComponents/BootstrapBlazorRoot.razor, src/BootstrapBlazor/Components/BrowserFinger/BrowserFinger.razor.cs, src/BootstrapBlazor/Components/BrowserFinger/BrowserFinger.razor.js
=> doc(BrowserFinger): add BrowserFinger service sample code

src/Extensions/Components/BootstrapBlazor.Topology/BootstrapBlazor.Topology.csproj, src/Extensions/Components/BootstrapBlazor.Topology/Components/Topology/Topology.razor.cs
=> refactor(Topology): bump version 8.0.3

src/BootstrapBlazor.Server/Components/Samples/BrowserFingers.razor.cs, src/BootstrapBlazor.Server/docs.json, src/BootstrapBlazor/Components/BrowserFinger/BrowserFinger.razor.cs
=> refactor(BrowserFinger): support Initialized life cycle

src/BootstrapBlazor/Components/Select/SelectTable.razor.scss
=> refactor(SelectTable): update style for SelectTable

src/BootstrapBlazor.Server/Components/Layout/BaseLayout.razor.css
=> doc(Dock): adjust z-index prevent being blocked

localization/de.json, localization/es.json, localization/pt.json, localization/th-TH.json, localization/zh-TW.json, src/BootstrapBlazor/Locales/en.json, src/BootstrapBlazor/Locales/zh.json
=> doc(TreeView): missing localization NotSetOnTreeExpandErrorMessage

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Button/PopConfirmButton.razor, src/BootstrapBlazor/Components/Button/PopConfirmButton.razor.cs, src/BootstrapBlazor/Components/Button/PopConfirmButton.razor.js, src/BootstrapBlazor/Components/Button/PopConfirmButtonBase.cs
=> fix(Popover): OnBeforeClick does not take effect

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Drawer/Drawer.razor.scss
=> feat(Drawer): update bar style

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Table/Table.razor.js, src/BootstrapBlazor/Utils/JSModule.cs
=> fix(Table): fix bindResizeColumn throw exception

src/BootstrapBlazor/Utils/JSModule.cs, src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss
=> feat(RibbonTab): reset ribbon-tab item min-width to 58px

src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json
=> doc(MindMap): update localizer namespace

src/BootstrapBlazor/Utils/JSModule.cs, test/UnitTest/Utils/JSModuleTest.cs
=> test(JSModule): add unit test for JSModule

.github/workflows/auto-pull-request-checks.yml, .github/workflows/build.yml
=> chore(action): bump codecov-action vertion to 4

src/BootstrapBlazor.Server/Components/Samples/Messages.razor.cs, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Message/Message.razor, src/BootstrapBlazor/Components/Message/Message.razor.cs, src/BootstrapBlazor/Components/Message/Message.razor.js, src/BootstrapBlazor/Components/Message/MessageService.cs, src/BootstrapBlazor/Components/Table/Table.razor.Toolbar.cs, test/UnitTest/Components/MessageTest.cs
=> feat(Message): support OnDismiss event callback

src/BootstrapBlazor.Server/Components/Samples/Messages.razor, src/BootstrapBlazor.Server/Components/Samples/Messages.razor.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/Components/Message/Message.razor, src/BootstrapBlazor/Components/Message/Message.razor.scss, src/BootstrapBlazor/Components/Message/MessageOption.cs, test/UnitTest/Components/MessageTest.cs
=> feat(Message): support ChildContent parameter

src/BootstrapBlazor.Server/Components/Samples/Table/TablesToolbar.razor.cs, src/BootstrapBlazor.Server/Components/Samples/Toasts.razor, src/BootstrapBlazor.Server/Components/Samples/Toasts.razor.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Toast/Toast.razor.cs, src/BootstrapBlazor/Components/Toast/ToastContainer.razor.cs, src/BootstrapBlazor/Components/Toast/ToastOption.cs, test/UnitTest/Components/ToastTest.cs
=> feat(Toast): add OnCloseAsync parameter on ToastOption

src/BootstrapBlazor.Server/Components/Layout/BaseLayout.razor.cs, src/BootstrapBlazor.Server/Controllers/Api/DispatchController.cs, src/BootstrapBlazor.Server/Controllers/Api/GiteeController.cs, src/BootstrapBlazor.Server/Data/RebootMessage.cs
=> doc(Website): add reboot dispatch function

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Scroll/Scroll.razor.scss
=> feat(Scroll): to cater the new scroll style

src/BootstrapBlazor/Components/Scroll/Scroll.razor.cs, src/BootstrapBlazor/Components/Scroll/Scroll.razor.scss, src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss, test/UnitTest/Components/ScrollTest.cs
=> feat(Scroll): add ScrollWidth parameter

src/BootstrapBlazor.Server/Components/Layout/NavMenu.razor.css, src/BootstrapBlazor.Server/wwwroot/css/site.css
=> doc(Scroll): update sidebar style

src/BootstrapBlazor/Components/Logout/Logout.razor.scss
=> fix(Logout): logout text max width not working

src/BootstrapBlazor/Components/Input/BootstrapInputGroup.razor.scss, src/BootstrapBlazor/Components/Input/BootstrapInputGroupLabel.razor, src/BootstrapBlazor/Components/Input/BootstrapInputGroupLabel.razor.cs, test/UnitTest/Components/InputTest.cs
=> feat(BootstrapInputGroupLabel): add width parameter

src/BootstrapBlazor.Server/Components/Samples/InputGroups.razor, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/Components/Input/BootstrapInputGroupLabel.razor.cs, test/UnitTest/Components/InputTest.cs
=> feat(BootstrapInputGroupLabel): add alignment parameter

src/BootstrapBlazor.Server/Components/Samples/SelectTables.razor.cs, src/BootstrapBlazor.Server/Components/Samples/Table/TablesExport.razor.cs, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Transfer/Transfer.razor.scss, src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss, test/UnitTest/Components/SelectTableTest.cs, test/UnitTest/Extensions/QueryPageOptionsExtensionsTest.cs
=> refactor(TableFilter): using ToFilterFunc to simplify code

.gitattributes, src/BootstrapBlazor/Components/Layout/Layout.razor, src/BootstrapBlazor/Components/Layout/Layout.razor.cs, src/BootstrapBlazor/Extensions/ConfigurationExtensions.cs, test/UnitTest/Components/LayoutTest.cs
=> feat(Layout): add CollapseBarTemplate parameter

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Modal/Modal.razor.js
=> feat(Modal): use hidden event instead of hide event

src/BootstrapBlazor.Server/Components/Samples/DateTimePickers.razor, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/DateTimePicker/DateTimePicker.razor, src/BootstrapBlazor/Components/DateTimePicker/DateTimePicker.razor.cs, src/BootstrapBlazor/Components/DateTimePicker/DateTimePicker.razor.scss, src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss, test/UnitTest/Components/DateTimePickerTest.cs
=> feat(DateTimePicker): add ShowIcon parameter

src/BootstrapBlazor.Server/Components/Samples/Selects.razor, src/BootstrapBlazor/Components/Input/BootstrapInputGroup.razor.scss, src/BootstrapBlazor/Components/Table/Table.razor, src/BootstrapBlazor/Components/Table/Table.razor.scss
=> feat(Table): redesign search bar

src/BootstrapBlazor/Components/DateTimePicker/DatePickerBody.razor.cs, src/BootstrapBlazor/Components/InputNumber/BootstrapInputNumber.razor.cs, src/BootstrapBlazor/Extensions/BootstrapBlazorOptionsExtensions.cs, src/BootstrapBlazor/Extensions/DateTimeExtensions.cs, test/UnitTest/Components/DateTimePickerTest.cs, test/UnitTest/Options/BootstrapBlazorOptionsTest.cs
=> refactor(DateTime): add GetSafeMonthDateTime extension method

exclusion.dic, src/BootstrapBlazor.Server/Components/Samples/Badges.razor.cs, src/BootstrapBlazor.Server/Components/Samples/Cascaders.razor.cs, src/BootstrapBlazor.Server/Components/Samples/DialButtons.razor.cs
=> doc(Components): add example comments

src/BootstrapBlazor.Server/Components/Samples/Sliders.razor, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/Components/Slider/Slider.razor.scss, src/BootstrapBlazor/wwwroot/scss/root.scss
=> feat(Slider): update disabled style

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Utils/Utility.cs
=> feat(GenerateComponent): support custom css class

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Drawer/Drawer.razor.scss
=> fix(Drawer): drawer bar be covered

src/BootstrapBlazor.Server/Components/Samples/ClockPickers.razor, src/BootstrapBlazor.Server/Components/Samples/ClockPickers.razor.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor.Server/wwwroot/css/site.css, src/BootstrapBlazor/Components/ClockPicker/ClockPicker.razor, src/BootstrapBlazor/Components/ClockPicker/ClockPicker.razor.cs, src/BootstrapBlazor/Components/ClockPicker/ClockPicker.razor.scss, src/BootstrapBlazor/Components/DateTimePicker/DatePickerBody.razor, src/BootstrapBlazor/Components/DateTimePicker/DatePickerBody.razor.scss, src/BootstrapBlazor/Locales/en.json, src/BootstrapBlazor/Locales/zh.json, test/UnitTest/Components/ClockPickerTest.cs
=> feat(ClockPicker): add ClockPicker component

src/BootstrapBlazor/wwwroot/modules/utility.js
=> refactor(GetUID): redesign getUID logic

src/BootstrapBlazor.Server/Components/Samples/DateTimeRanges.razor, src/BootstrapBlazor/Components/DateTimePicker/DatePickerBody.razor.cs, src/BootstrapBlazor/Components/DateTimeRange/DateTimeRange.razor.cs, test/UnitTest/Components/DateTimeRangeTest.cs, test/UnitTest/Components/TimePickerSettingTest.cs
=> refactor(DateTimeRange): disable DateTime mode

src/BootstrapBlazor/Components/Pagination/Pagination.razor.cs, test/UnitTest/Components/PaginationTest.cs
=> test(Pagination): add unit test Pagination

src/BootstrapBlazor.Server/Components/Samples/Displays.razor, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Display/Display.razor, src/BootstrapBlazor/Components/Display/Display.razor.cs, src/BootstrapBlazor/Components/Display/DisplayBase.cs, src/BootstrapBlazor/Components/Label/BootstrapLabel.razor.cs, test/UnitTest/Components/DisplayTest.cs
=> feat(Display): add ShowTooltip parameter

src/BootstrapBlazor/Extensions/JSModuleExtensions.cs, src/BootstrapBlazor/wwwroot/modules/utility.js, test/UnitTest/Extensions/JSModuleExtensionsTest.cs
=> feat(JSModule): add GenerateId method

src/BootstrapBlazor.Server/Components/Samples/Table/TablesSearch.razor, src/BootstrapBlazor.Server/Data/TreeDataFoo.cs, src/BootstrapBlazor/Components/Console/Console.razor, src/BootstrapBlazor/Components/Console/Console.razor.cs, src/BootstrapBlazor/Components/Console/ConsoleMessageItem.cs, src/BootstrapBlazor/Extensions/ConsoleItemMessageExtensions.cs, src/BootstrapBlazor/Extensions/MenuItemExtensions.cs, test/UnitTest/Components/ConsoleTest.cs
=> feat(Console): add IsHtml parameter on ConsoleMessageItem

src/BootstrapBlazor.Server/Components/Samples/Consoles.razor.cs, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Console/Console.razor.cs, src/BootstrapBlazor/Components/Console/ConsoleMessageCollection.cs, test/UnitTest/Components/ConsoleTest.cs
=> feat(Console): add ConsoleMessageCollection class

src/BootstrapBlazor/Components/Select/Select.razor.cs
=> refactor(Select): update OnInputChangedCallback call before ValueChanged

src/BootstrapBlazor.Server/Components/Samples/Client.razor, src/BootstrapBlazor/Components/Tooltip/Tooltip.razor.scss
=> feat(Display): add overflow hidden style

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Table/TableAdvancedSortDialog.razor
=> doc(Table): update document

Directory.Build.props, src/BootstrapBlazor.Server/Components/Samples/DateTimeRanges.razor.cs, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/DateTimeRange/DateTimeRange.razor.cs
=> fix(DateTimeRange): start value timespan is not zero

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Display/Display.razor.cs, src/BootstrapBlazor/Utils/Utility.cs
=> bug(Display): parameter Lookup not work

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/BootstrapBlazor.Server/Components/Samples/Charts/Bar.razor, src/BootstrapBlazor.Server/Components/Samples/Charts/Bar.razor.cs, src/Extensions/Components/BootstrapBlazor.Chart/BootstrapBlazor.Chart.csproj, src/Extensions/Components/BootstrapBlazor.Chart/Components/Chart/Chart.razor.cs, src/Extensions/Components/BootstrapBlazor.Chart/Components/Chart/Chart.razor.js, src/Extensions/Components/BootstrapBlazor.Chart/Components/Chart/ChartDataSource.cs, src/Extensions/Components/BootstrapBlazor.Chart/Components/Chart/ChartDataset.cs, src/Extensions/Components/BootstrapBlazor.Chart/Components/Chart/ChartOptions.cs
close #add OnClickDataAsync parameter
=> feat(Chart): add OnClickDataAsync parameter

src/BootstrapBlazor.Server/Components/Samples/SweetAlerts.razor, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Select/MultiSelect.razor, src/BootstrapBlazor/Components/Select/MultiSelect.razor.cs, src/BootstrapBlazor/Components/Select/MultiSelect.razor.js
=> fix(MultiSelect): can't close popup window when in validate form

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Table/Table.razor.scss
=> fix(Table): no scroll on card view

src/BootstrapBlazor/Misc/ExpandableNodeCache.cs
=> chore(TreeView): revert change async child node state

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/EditorForm/EditorForm.razor.cs, test/UnitTest/Components/SelectTableTest.cs
=> bug(SelectTable): throw exception when in the table column's edit template

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Table/Table.razor
=> fix(SelectTable): search text wrap inside validate form

src/BootstrapBlazor/Components/Select/SelectTable.razor, src/BootstrapBlazor/Components/Select/SelectTable.razor.cs
=> feat(SelectTable): add CollapsedTopSearch parameter

src/BootstrapBlazor/Components/Upload/ButtonUploadBase.cs, test/UnitTest/Components/UploadTest.cs
=> feat(Upload): add OnAllFileUploaded parameter

src/BootstrapBlazor.Server/Components/Samples/Table/TablesSearch.razor.cs, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Extensions/LambdaExtensions.cs, src/BootstrapBlazor/Extensions/QueryPageOptionsExtensions.cs, test/UnitTest/Components/TableTestEFCore.cs, test/UnitTest/Extensions/QueryPageOptionsExtensionsTest.cs
=> revert(Contains): remove StringComparison parameter

src/BootstrapBlazor.Server/Components/Samples/FlipClocks.razor, src/BootstrapBlazor.Server/Extensions/MenusLocalizerExtensions.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor.Server/docs.json, src/BootstrapBlazor/Components/Captcha/Captcha.razor.js, src/BootstrapBlazor/Components/FlipClock/FlipClock.razor, src/BootstrapBlazor/Components/FlipClock/FlipClock.razor.cs, src/BootstrapBlazor/Components/FlipClock/FlipClock.razor.js, src/BootstrapBlazor/Components/FlipClock/FlipClock.razor.scss, src/BootstrapBlazor/wwwroot/scss/components.scss, test/UnitTest/Components/FlipClockTest.cs
=> feat(FlipClock): add FlipClock component

src/BootstrapBlazor.Server/Components/Layout/ComponentLayout.razor.css, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Layout/Layout.razor.scss, src/BootstrapBlazor/Components/Table/Table.razor.Sort.cs, test/UnitTest/Components/TableTestEFCore.cs, test/UnitTest/Services/IpLocatorTest.cs
=> fix(Table): incorrect display of fixed table columns when visible false

src/BootstrapBlazor/Attributes/AutoGenerateColumnAttribute.cs, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/EditorForm/EditorItem.cs, src/BootstrapBlazor/Components/EditorForm/IEditorItem.cs, src/BootstrapBlazor/Components/Table/InternalTableColumn.cs, src/BootstrapBlazor/Components/Table/TableColumn.cs, src/BootstrapBlazor/Extensions/ITableColumnExtensions.cs, src/BootstrapBlazor/Extensions/ObjectExtensions.cs, test/UnitTest/Attributes/AutoGenerateClassTest.cs
=> fix(Table): update IsReadonly/Visible logic

src/BootstrapBlazor.Server/Components/Samples/DateTimePickers.razor, src/BootstrapBlazor.Server/Components/Samples/DateTimePickers.razor.cs, src/BootstrapBlazor.Server/Components/Samples/DateTimePickers.razor.css, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/Components/DateTimePicker/DatePickerBody.razor, src/BootstrapBlazor/Components/DateTimePicker/DatePickerBody.razor.cs, src/BootstrapBlazor/Components/DateTimePicker/DatePickerBody.razor.scss, src/BootstrapBlazor/Components/DateTimePicker/DatePickerCell.razor, src/BootstrapBlazor/Components/DateTimePicker/DatePickerCell.razor.cs, src/BootstrapBlazor/Components/DateTimePicker/DateTimePicker.razor, src/BootstrapBlazor/Components/DateTimePicker/DateTimePicker.razor.cs, src/BootstrapBlazor/Extensions/DateTimeExtensions.cs, test/UnitTest/Components/DateTimePickerTest.cs, test/UnitTest/Extensions/DateTimeExtensionsTest.cs, test/UnitTest/UnitTest.csproj
=> feat(DateTimePicker): add ShowLunar parameter

src/BootstrapBlazor.Server/Components/Samples/DateTimePickers.razor, src/BootstrapBlazor/Components/DateTimePicker/DatePickerBody.razor, src/BootstrapBlazor/Components/DateTimePicker/DatePickerBody.razor.cs, src/BootstrapBlazor/Components/DateTimePicker/DatePickerBody.razor.scss, src/BootstrapBlazor/Components/DateTimePicker/DatePickerCell.razor.cs, src/BootstrapBlazor/Components/DateTimePicker/DateTimePicker.razor, src/BootstrapBlazor/Components/DateTimePicker/DateTimePicker.razor.cs, src/BootstrapBlazor/Extensions/BootstrapBlazorServiceCollectionExtensions.cs, src/BootstrapBlazor/Extensions/DateTimeExtensions.cs, src/BootstrapBlazor/Services/DefaultCalendarFestivals.cs, src/BootstrapBlazor/Services/ICalendarFestivals.cs, test/UnitTest/Components/DateTimePickerTest.cs, test/UnitTest/Extensions/DateTimeExtensionsTest.cs
=> feat(DateTimePicker): add ShowFestivals parameter

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Table/ColumnVisibleItem.cs, src/BootstrapBlazor/Components/Table/Table.razor, src/BootstrapBlazor/Components/Table/Table.razor.Sort.cs, src/BootstrapBlazor/Components/Table/Table.razor.Toolbar.cs, src/BootstrapBlazor/Components/Table/Table.razor.cs, test/UnitTest/Components/TableTest.cs
=> refactor(Table): redesign visible column list for Table

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/BootstrapBlazor/Components/Table/ColumnVisibleItem.cs, src/BootstrapBlazor/Components/Table/Table.razor.Sort.cs, src/BootstrapBlazor/Components/Table/Table.razor.cs, src/Extensions/Components/BootstrapBlazor.Holiday/BootstrapBlazor.Holiday.csproj, test/UnitTest/Components/TableTest.cs
=> test(Table): improve code coverage

src/Extensions/Components/BootstrapBlazor.SummerNote/BootstrapBlazor.SummerNote.csproj, src/Extensions/Components/BootstrapBlazor.SummerNote/Components/Editor/Editor.razor.cs, src/Extensions/Components/BootstrapBlazor.SummerNote/Components/Editor/Editor.razor.js
=> fix(Editor): load zh-CN lang failed when first render

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Menu/Menu.razor.cs, src/BootstrapBlazor/Components/Menu/Menu.razor.scss
=> fix(Menu): active status incorect when route changed

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Table/Table.razor, src/BootstrapBlazor/Components/Table/TableCellArgs.cs, test/UnitTest/Components/TableTest.cs
=> feat(TableCellArgs): add ValueTemplate parameter

src/BootstrapBlazor.Server/Components/Samples/SlideButtons.razor
=> doc(SlideButton): fixed demo attribute error

src/BootstrapBlazor.Server/Components/Samples/FlipClocks.razor, src/BootstrapBlazor.Server/Components/Samples/FlipClocks.razor.cs, src/BootstrapBlazor.Server/Extensions/MenusLocalizerExtensions.cs, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/FlipClock/FlipClock.razor, src/BootstrapBlazor/Components/FlipClock/FlipClock.razor.cs, test/UnitTest/Components/FlipClockTest.cs
=> refactor(FlipClock): add more parameter

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Table/Table.razor, test/UnitTest/Components/TableTest.cs
=> refactor(OnCellRender): fix value template not work on Table mode

src/BootstrapBlazor.Server/Components/Samples/InputNumbers.razor, src/BootstrapBlazor.Server/Components/Samples/InputNumbers.razor.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/InputNumber/BootstrapInputNumber.razor.cs, test/UnitTest/Components/InputNumberTest.cs
=> refactor(InputNumber): not nullable data unable to be cleared

src/BootstrapBlazor.Server/Components/Samples/Table/TablesDetailRow.razor, src/BootstrapBlazor.Server/Components/Samples/Table/TablesDetailRow.razor.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/Components/Table/Table.razor.cs, test/UnitTest/Components/TableTest.cs
auto-collapse other details when expanding a new row 
close #3102
=> feat(Table): add IsAccordion parameter

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/BootstrapBlazor.Server/Components/Samples/DateTimePickers.razor, src/BootstrapBlazor.Server/Components/Samples/DateTimePickers.razor.cs, src/BootstrapBlazor.Server/Components/Samples/Festivals.razor, src/BootstrapBlazor.Server/Components/Samples/Holidays.razor, src/BootstrapBlazor.Server/Extensions/MenusLocalizerExtensions.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor.Server/appsettings.json, src/BootstrapBlazor/Services/DefaultCalendarFestivals.cs, src/BootstrapBlazor/Services/ICalendarFestivals.cs, src/BootstrapBlazor/Services/ICalendarHolidays.cs
=> doc(Festival): add ICalendarFestival service document

src/BootstrapBlazor.Server/Components/Samples/InputNumbers.razor, src/BootstrapBlazor.Server/Components/Samples/InputNumbers.razor.cs, src/BootstrapBlazor.Server/Components/Samples/Lookup.razor, src/BootstrapBlazor.Server/Components/Samples/Table/TablesLookup.razor, src/BootstrapBlazor.Server/Components/Samples/Table/TablesLookup.razor.cs, src/BootstrapBlazor.Server/Extensions/MenusLocalizerExtensions.cs, src/BootstrapBlazor.Server/Extensions/ServicesExtensions.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor.Server/Program.cs, src/BootstrapBlazor/Services/ILookupService.cs, test/UnitTest/Performance/AlgorithmTest.cs
=> doc(ILookupService): add lookup documention

src/BootstrapBlazor.Server/Components/Components/Pre.razor, src/BootstrapBlazor.Server/Components/Samples/DialogServices.razor, src/BootstrapBlazor.Server/Components/Samples/DialogServices.razor.css, src/BootstrapBlazor.Server/Components/Samples/Dialogs.razor, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/Components/Dialog/ResultDialogOption.cs
=> doc(DialgService): update dialog service documentation

src/BootstrapBlazor/Services/WebClientService.cs, src/BootstrapBlazor/wwwroot/modules/client.js, test/UnitTest/Services/WebClientServiceTest.cs
=> refactor(WebClientService): use client info class

src/Extensions/Components/BootstrapBlazor.Gantt/Components/GanttOption.cs
…e language
Changed default language for the Gantt component. It was showing non-English month names instead of English. 
close #3114
=> feat(Gantt): support localization

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/Extensions/Components/BootstrapBlazor.Gantt/BootstrapBlazor.Gantt.csproj, src/Extensions/Components/BootstrapBlazor.Gantt/Components/GanttItem.cs, src/Extensions/Components/BootstrapBlazor.Gantt/Components/GanttOption.cs, src/Extensions/Components/BootstrapBlazor.Gantt/Components/GanttViewMode.cs
=> chore(Gantt): bump version 8.0.1

src/BootstrapBlazor.Server/Components/Layout/HomeLayout.razor, src/BootstrapBlazor.Server/Components/Layout/HomeLayout.razor.css, src/BootstrapBlazor/Options/CollectionHubOptions.cs, src/BootstrapBlazor/wwwroot/modules/ajax.js, src/BootstrapBlazor/wwwroot/modules/hub.js
=> refactor(ConnectionHub): add try catch for request failed

src/BootstrapBlazor.Server/Components/Samples/DialogServices.razor, src/BootstrapBlazor.Server/Components/Samples/Table/TablesColumnTemplate.razor, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json
=> doc(Table): add document for edit template

src/BootstrapBlazor/Options/BootstrapBlazorOptions.cs, src/BootstrapBlazor/Options/CollectionHubOptions.cs, src/BootstrapBlazor/Services/DefaultConnectionService.cs, test/UnitTest/Components/CountButtonTest.cs, test/UnitTest/Services/ConnectionHubTest.cs
=> refactor(IConnectionService): add await keyword

src/BootstrapBlazor.Server/Components/Components/Header.razor.css, src/BootstrapBlazor.Server/Components/Layout/HomeLayout.razor, src/BootstrapBlazor.Server/Components/Layout/HomeLayout.razor.cs, src/BootstrapBlazor.Server/Components/Pages/Online.razor, src/BootstrapBlazor.Server/Components/Pages/Online.razor.cs, src/BootstrapBlazor.Server/appsettings.json, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/ConnectionHub/ConnectionHub.cs, src/BootstrapBlazor/Components/ConnectionHub/ConnectionItem.cs, src/BootstrapBlazor/Options/BootstrapBlazorOptions.cs, src/BootstrapBlazor/Options/CollectionHubOptions.cs, src/BootstrapBlazor/Options/ConnectionHubOptions.cs, src/BootstrapBlazor/Services/DefaultConnectionService.cs, src/BootstrapBlazor/Services/IConnectionService.cs, src/BootstrapBlazor/wwwroot/modules/client.js, src/BootstrapBlazor/wwwroot/modules/hub.js, test/UnitTest/Services/ConnectionHubTest.cs, test/UnitTest/appsettings.json
=> refactor(IConnectionService): add Connections parameter

src/BootstrapBlazor/Components/ConnectionHub/ConnectionHub.cs, src/BootstrapBlazor/Services/IPLocator/DefaultIPLocatorProvider.cs
=> refactor(ConnectionHub): add locate ip cache

src/BootstrapBlazor.Server/Components/Layout/HomeLayout.razor.cs, src/BootstrapBlazor.Server/appsettings.json, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/ConnectionHub/ConnectionHub.cs, src/BootstrapBlazor/Options/BootstrapBlazorOptions.cs, src/BootstrapBlazor/Services/DefaultConnectionService.cs, src/BootstrapBlazor/Services/IPLocator/BaiduIpLocatorProvider.cs, src/BootstrapBlazor/Services/IPLocator/BaiduIpLocatorProviderV2.cs, src/BootstrapBlazor/Services/IPLocator/DefaultIPLocatorProvider.cs, src/BootstrapBlazor/Services/IPLocator/IpLocatorOptions.cs, test/UnitTest/Services/ConnectionHubTest.cs, test/UnitTest/Services/IpLocatorTest.cs
=> feat(IpLocatorOptions): add data cache logic

src/BootstrapBlazor.Server/Components/Samples/TreeViews.razor, src/BootstrapBlazor.Server/Components/Samples/TreeViews.razor.cs, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/TreeView/TreeView.razor, src/BootstrapBlazor/Components/TreeView/TreeView.razor.cs, src/BootstrapBlazor/Enums/ComponentIcons.cs, src/BootstrapBlazor/Options/IconThemeOptions.cs
=> feat(TreeView): add Search feature

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/ConnectionHub/ConnectionHub.cs, src/BootstrapBlazor/Extensions/BootstrapBlazorServiceCollectionExtensions.cs, src/BootstrapBlazor/Options/ConnectionHubOptions.cs, src/BootstrapBlazor/Options/ThrottleOptions.cs, src/BootstrapBlazor/Services/DefaultConnectionService.cs, src/BootstrapBlazor/Services/DefaultThrottleDispatcherFactory.cs, src/BootstrapBlazor/Services/IThrottleDispatcherFactory.cs, src/BootstrapBlazor/Services/ThrottleDispatcher.cs, src/BootstrapBlazor/wwwroot/modules/hub.js, test/UnitTest/Services/ThrottleTest.cs
=> feat(IThrottleDispatcherFactory): add throttle service

src/BootstrapBlazor.Server/appsettings.json, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/ConnectionHub/ConnectionHub.cs, src/BootstrapBlazor/Options/ConnectionHubOptions.cs, src/BootstrapBlazor/Options/ThrottleOptions.cs, src/BootstrapBlazor/Services/DefaultConnectionService.cs, src/BootstrapBlazor/Services/IThrottleDispatcherFactory.cs, src/BootstrapBlazor/Services/ThrottleDispatcher.cs, src/BootstrapBlazor/Services/WebClientService.cs, test/UnitTest/Services/ConnectionHubTest.cs, test/UnitTest/Services/ThrottleTest.cs, test/UnitTest/Services/WebClientServiceTest.cs, test/UnitTest/UnitTest.csproj
=> refactor(ConnectionService): add TimeoutInterval parameter

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/TreeView/TreeView.razor, src/BootstrapBlazor/Components/TreeView/TreeView.razor.scss
=> refactor(TreeView): update style for search box

src/BootstrapBlazor.Server/appsettings.json, src/BootstrapBlazor/Components/ConnectionHub/ConnectionHub.cs, src/BootstrapBlazor/wwwroot/modules/client.js, src/BootstrapBlazor/wwwroot/modules/hub.js, test/UnitTest/Services/ConnectionHubTest.cs
=> refactor(ConnectionHub): add client throttle

src/BootstrapBlazor/Components/Carousel/Carousel.razor, src/BootstrapBlazor/Components/Carousel/Carousel.razor.cs, src/BootstrapBlazor/Components/Carousel/Carousel.razor.js, test/UnitTest/Components/CarouselTest.cs
=> feat(Carousel): add OnSlideChanged parameter

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Dialog/Dialog.razor.cs, src/BootstrapBlazor/Components/Message/Message.razor.cs, src/BootstrapBlazor/Components/SweetAlert/SweetAlert.razor.cs
=> bug(Dialog): not popup when use DispatchService trigger

src/BootstrapBlazor/wwwroot/modules/hub.js
=> refactor(ConnectionHub): fix missing connection id issue

src/BootstrapBlazor.Server/Components/Pages/Online.razor.cs, src/BootstrapBlazor.Server/Extensions/MenusLocalizerExtensions.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor.Server/appsettings.json, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/wwwroot/modules/hub.js, test/UnitTest/Components/CalendarTest.cs, test/UnitTest/Components/DateTimeRangeTest.cs
=> doc(Online): add online sample

src/BootstrapBlazor.Server/Components/Samples/PrintServices.razor, src/BootstrapBlazor.Server/Extensions/MenusLocalizerExtensions.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json
=> doc(PrintService): add PrintService documentation

src/Extensions/Components/BootstrapBlazor.CodeEditor/BootstrapBlazor.CodeEditor.csproj, src/Extensions/Components/BootstrapBlazor.CodeEditor/Components/CodeEditor/CodeEditor.razor, src/Extensions/Components/BootstrapBlazor.CodeEditor/Components/CodeEditor/CodeEditor.razor.cs, src/Extensions/Components/BootstrapBlazor.CodeEditor/Components/CodeEditor/CodeEditor.razor.css, src/Extensions/Components/BootstrapBlazor.CodeEditor/Components/CodeEditor/CodeEditor.razor.js
=> fix(CodeEditor): do not show in Dialog on first render

src/BootstrapBlazor.Server/Components/Samples/DateTimeRanges.razor, src/BootstrapBlazor.Server/Components/Samples/DateTimeRanges.razor.cs, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/DateTimePicker/DatePickerBody.razor.cs, src/BootstrapBlazor/Components/DateTimePicker/DatePickerBody.razor.scss, src/BootstrapBlazor/Components/DateTimeRange/DateTimeRange.razor, src/BootstrapBlazor/Components/DateTimeRange/DateTimeRange.razor.cs, src/BootstrapBlazor/Components/DateTimeRange/DateTimeRange.razor.scss, src/BootstrapBlazor/Services/IPLocator/BaiduIpLocatorProviderV2.cs, test/UnitTest/Services/IpLocatorTest.cs
=> feat(DateTimeRange): support lunar festival holiday solar tearm feature

src/Extensions/Components/BootstrapBlazor.MaterialDesign.Extensions/BootstrapBlazor.MaterialDesign.Extensions.csproj, src/Extensions/Components/BootstrapBlazor.MaterialDesign.Extensions/DefaultIcon.cs
=> feat(MaterialDesign): add search icon of TreeView

src/BootstrapBlazor/Components/Upload/ButtonUploadBase.cs
=> fix(ButtonUpload): do not trigger ValueChanged callback

src/BootstrapBlazor.Server/Components/Pages/Online.razor.cs
=> doc(Online): add IP mask keep privace

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Dynamic/DataTableDynamicContext.cs
=> feat(table): support Caption of DataTable #3213

src/BootstrapBlazor.Server/Components/Layout/HomeLayout.razor, src/BootstrapBlazor.Server/Components/Pages/Online.razor.cs, src/BootstrapBlazor.Server/Extensions/IpExtensions.cs, test/UnitTest/UnitTest.csproj, test/UnitTest/Utils/UtilityTest.cs
=> doc(Online): add day information

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/Extensions/Components/BootstrapBlazor.FontAwesome/BootstrapBlazor.FontAwesome.csproj, src/Extensions/Components/BootstrapBlazor.FontAwesome/Components/FAIconList.razor, src/Extensions/Components/BootstrapBlazor.FontAwesome/Components/FAIconList.razor.cs, src/Extensions/Components/BootstrapBlazor.FontAwesome/Components/FAIconList.razor.js
=> refactor(FAIcon): use JSModule refactor javascript logic

src/BootstrapBlazor.Server/Components/Layout/HomeLayout.razor.css, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/InputNumber/BootstrapInputNumber.razor.cs
=> fix(BootstrapInput): can't set value

src/BootstrapBlazor/Components/DateTimePicker/DatePickerBody.razor.scss, src/BootstrapBlazor/Components/DateTimePicker/DatePickerCell.razor, src/BootstrapBlazor/Services/DefaultCalendarHolidayss.cs, src/BootstrapBlazor/Services/ICalendarHolidays.cs, src/Extensions/Components/BootstrapBlazor.Holiday/Services/DefaultCalendarHolidays.cs, test/UnitTest/Components/DateTimePickerTest.cs
=> feat(DateTimePicker): add working day feature

src/BootstrapBlazor/Components/Table/TableColumn.cs, src/BootstrapBlazor/Localization/NullLocalizationResolve.cs, src/BootstrapBlazor/Utils/Utility.cs, test/UnitTest/Components/TableTest.cs
close #3219 #3220 
close #3233
=> feat(TableColumn): support complex model

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Services/DefaultCalendarHolidayss.cs, src/BootstrapBlazor/Services/ICalendarHolidays.cs, src/Extensions/Components/BootstrapBlazor.Holiday/BootstrapBlazor.Holiday.csproj, src/Extensions/Components/BootstrapBlazor.Holiday/Services/DefaultCalendarHolidays.cs, test/UnitTest/Components/DateTimePickerTest.cs
=> refactor(DateTimePicker): format code for ICalendarHoliday

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/Extensions/Components/BootstrapBlazor.Dock/BootstrapBlazor.Dock.csproj, src/Extensions/Components/BootstrapBlazor.Dock/Components/DockView/DockView.razor.cs
=> feat(DockView): add Version parameter

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Options/BootstrapBlazorOptions.cs, src/BootstrapBlazor/Options/TableExportOptions.cs, src/BootstrapBlazor/Options/TableSettings.cs, src/BootstrapBlazor/Services/DefaultTableExport.cs, src/BootstrapBlazor/Services/ITableExport.cs, test/UnitTest/Options/BootstrapBlazorOptionsTest.cs
=> feat(TableExportOptions): add TableExportOptions class for Table export

src/BootstrapBlazor.Server/Components/Samples/LayoutDemo.razor, src/BootstrapBlazor.Server/Extensions/ServicesExtensions.cs, src/BootstrapBlazor/Components/Tab/Tab.razor.cs
=> doc(Layout): empty text when F5 refresh

src/BootstrapBlazor.Server/Components/Pages/Online.razor, src/BootstrapBlazor.Server/Components/Pages/Online.razor.cs, src/BootstrapBlazor.Server/Components/Pages/Online.razor.css, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json
Online population statistics increase in multiple languages
close #3250
=> doc(Online): add Online Localizer

src/BootstrapBlazor.Server/Components/Pages/Online.razor.cs, test/UnitTest/Components/WaterfallTest.cs
=> doc(Online): fix IP unshielded issue

src/BootstrapBlazor.Server/Components/Samples/Locators.razor, src/BootstrapBlazor.Server/Components/Samples/Locators.razor.cs, src/BootstrapBlazor.Server/appsettings.json, src/BootstrapBlazor/Extensions/BootstrapBlazorServiceCollectionExtensions.cs, src/BootstrapBlazor/Services/IPLocator/DefaultIPLocatorProvider.cs, src/BootstrapBlazor/Services/IPLocator/JuHeIpLocatorProvider.cs, test/UnitTest/Services/IpLocatorTest.cs, test/UnitTest/appsettings.json
=> feat(JuHeIpLocatorProvider): add JuHeIpLocatorProvider service

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Select/MultiSelect.razor.cs, src/BootstrapBlazor/Components/Select/Select.razor.cs, src/Extensions/Components/BootstrapBlazor.TableExport/BootstrapBlazor.TableExport.csproj
=> feat(Select): default value filter disabled item

src/BootstrapBlazor/Services/DefaultTableExport.cs, src/BootstrapBlazor/Services/ITableExport.cs
=> refactor(ITableExport): redesign ITableExport compatible with previous versions

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/BootstrapBlazor/BootstrapBlazor.csproj, src/Extensions/Components/BootstrapBlazor.TableExport/BootstrapBlazor.TableExport.csproj, src/Extensions/Components/BootstrapBlazor.TableExport/Services/DefaultTableExport.cs
=> feat(TableExport): redesign ExportAsync compatible previous version

src/BootstrapBlazor/Extensions/TypeExtensions.cs, src/BootstrapBlazor/Services/CacheManager.cs
Add Type handle condition to cache key
close #3280
=> fix(CacheManager): unable to dynamically load DLL multiple times

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Extensions/AssemblyExtensions.cs, src/BootstrapBlazor/Extensions/TypeExtensions.cs, src/BootstrapBlazor/Localization/Json/JsonStringLocalizer.cs, src/BootstrapBlazor/Services/CacheManager.cs
If it is an assembly in ALC, add a cache key condition
close #3286
=> refactor(ALC): add assembly extension method GetUniqueName

src/BootstrapBlazor/Localization/Json/JsonStringLocalizerFactory.cs, src/BootstrapBlazor/Services/CacheManager.cs
update GetJsonStringByTypeName support collectible assembly
close #3290
=> refactor(CacheManager): update GetJsonStringByTypeName support collectible assembly

src/Extensions/Components/BootstrapBlazor.Topology/BootstrapBlazor.Topology.csproj, src/Extensions/Components/BootstrapBlazor.Topology/Components/Topology/Topology.razor.cs, src/Extensions/Components/BootstrapBlazor.Topology/Components/Topology/Topology.razor.js
=> refactor(Topology): update init arguments

src/BootstrapBlazor.Server/Components/Samples/Client.razor, src/BootstrapBlazor.Server/Components/Samples/Client.razor.cs, src/BootstrapBlazor.Server/Components/Samples/ConnectionServices.razor, src/BootstrapBlazor.Server/Extensions/MenusLocalizerExtensions.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor.Server/wwwroot/css/site.css, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Checkbox/CheckboxList.razor.cs
=> doc(ConnectionService): add document for connection service

src/BootstrapBlazor.Server/Components/Samples/FlipClocks.razor, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json
=> doc(FlipClocks): add Localizer

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/BootstrapBlazor/Extensions/BootstrapBlazorServiceCollectionExtensions.cs, src/Extensions/Components/BootstrapBlazor.TableExport/BootstrapBlazor.TableExport.csproj, src/Extensions/Components/BootstrapBlazor.TableExport/Extensions/TableExportServiceCollectionExtensions.cs
=> refactor(TableExport): generate file failed

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/Extensions/Components/BootstrapBlazor.Dock/BootstrapBlazor.Dock.csproj, src/Extensions/Components/BootstrapBlazor.Dock/Components/DockView/DockContent.cs, src/Extensions/Components/BootstrapBlazor.Dock/wwwroot/css/goldenlayout-bb.css
=> feat(Dock): not show close button when any tab set ShowClose to false

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/Extensions/Components/BootstrapBlazor.Dock/BootstrapBlazor.Dock.csproj, src/Extensions/Components/BootstrapBlazor.Dock/Components/DockView/DockView.razor.js
=> feat(Dock): support push new component from server side

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj
=> doc(PdfReader): update dependency package

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Utils/JSModule.cs, test/UnitTest/Utils/JSModuleTest.cs
=> refactor(JSModule): catch ObjectDisposed exception

src/BootstrapBlazor.Server/appsettings.json, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Services/IPLocator/IpLocatorOptions.cs, src/BootstrapBlazor/Services/WebClientService.cs
=> feat(WebClient): add Enable parameter on IpLocatorOptions

src/Extensions/DataServices/BootstrapBlazor.DataAccess.PetaPoco/BootstrapBlazor.DataAccess.PetaPoco.csproj, src/Extensions/DataServices/BootstrapBlazor.DataAccess.PetaPoco/DefaultDataService.cs, src/Extensions/DataServices/BootstrapBlazor.DataAccess.PetaPoco/PetaPocoServiceCollectionExtensions.cs
=> feat(PetaPoco): use TryAddTransient method

src/BootstrapBlazor/Services/IPLocator/DefaultIPLocatorProvider.cs, test/UnitTest/Services/IpLocatorTest.cs, test/UnitTest/appsettings.json
=> feat(IpLocator): add Enable parameter logic

src/BootstrapBlazor/Components/Table/Table.razor.cs, test/UnitTest/Components/TableTest.cs, test/UnitTest/Services/WebClientServiceTest.cs
=> test(Table): add reload column order unit test

src/BootstrapBlazor.Server/Components/Samples/Table/TablesExport.razor.cs, src/Extensions/Components/BootstrapBlazor.SummerNote/BootstrapBlazor.SummerNote.csproj, src/Extensions/Components/BootstrapBlazor.SummerNote/Components/Editor/Editor.razor, src/Extensions/Components/BootstrapBlazor.SummerNote/Components/Editor/Editor.razor.cs, test/UnitTestEditor/EditorTest.cs
=> fix(Editor): throw exception in EditTemplate of Table

src/BootstrapBlazor/Components/FullScreen/FullScreenButton.razor.cs, src/BootstrapBlazor/wwwroot/modules/fullscreen.js
=> feat(FullScreenButton): add TargetId parameter

src/BootstrapBlazor.Server/Components/Layout/ComponentLayout.razor, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/FullScreen/FullScreenButton.razor.cs, src/BootstrapBlazor/Components/Tab/Tab.razor, src/BootstrapBlazor/Components/Tab/Tab.razor.cs, src/BootstrapBlazor/Components/Tab/Tab.razor.scss, src/BootstrapBlazor/Components/Tab/TabItem.cs, src/BootstrapBlazor/wwwroot/modules/fullscreen.js, test/UnitTest/Components/FullScreenTest.cs, test/UnitTest/Components/TabTest.cs
=> feat(TabItem): add ShowFullScreen parameter

src/BootstrapBlazor.Server/Components/Layout/ComponentLayout.razor, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Tab/Tab.razor, src/BootstrapBlazor/Components/Tab/Tab.razor.cs, src/BootstrapBlazor/Components/Tab/TabItem.cs, test/UnitTest/Components/TabTest.cs
=> feat(Tab): add ShowFullScreen parameter

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/Extensions/Components/BootstrapBlazor.Dock/BootstrapBlazor.Dock.csproj, src/Extensions/Components/BootstrapBlazor.Dock/Components/DockView/DockView.razor.js
=> feat(DockView): support stack layout

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/ClockPicker/ClockPicker.razor.cs, src/BootstrapBlazor/Components/ClockPicker/ClockPicker.razor.js
=> bug(DateTimePicker): can't drag clock in NET6

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/BootstrapBlazor.Server/Components/Samples/DockViews/DockViewCol.razor, src/BootstrapBlazor.Server/Components/Samples/DockViews/DockViewVisible.razor, src/Extensions/Components/BootstrapBlazor.Dock/BootstrapBlazor.Dock.csproj, src/Extensions/Components/BootstrapBlazor.Dock/Components/DockView/DockComponent.cs, src/Extensions/Components/BootstrapBlazor.Dock/Components/DockView/DockView.razor.js, src/Extensions/Components/BootstrapBlazor.Dock/Converters/DockComponentConverter.cs, src/Extensions/Components/BootstrapBlazor.Dock/wwwroot/css/goldenlayout-bb.css
=> feat(DockView): add TitleClass/TitleWidth parameter #3377

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Services/IHtml2Pdf.cs, src/Extensions/Components/BootstrapBlazor.Html2Pdf/BootstrapBlazor.Html2Pdf.csproj, src/Extensions/Components/BootstrapBlazor.Html2Pdf/Extensions/ServiceCollectionExtensions.cs, src/Extensions/Components/BootstrapBlazor.Html2Pdf/Services/DefaultPdfService.cs
=> feat(IHtml2Pdf): add PdfStreamFromHtmlAsync method

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Services/ITableExport.cs, test/UnitTest/Components/TableExportTest.cs
=> feat(ITableExport): add links parameter support dynamic load style sheet

src/Extensions/Components/BootstrapBlazor.Html2Pdf/Extensions/ServiceCollectionExtensions.cs, src/Extensions/Components/BootstrapBlazor.Html2Pdf/Services/DefaultPdfService.cs
=> refactor(IHtml2Pdf): remove bootstrapblazor default links

src/BootstrapBlazor.Server/Components/Samples/Html2Pdfs.razor, src/BootstrapBlazor.Server/Components/Samples/Html2Pdfs.razor.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/Extensions/BootstrapBlazorServiceCollectionExtensions.cs, src/BootstrapBlazor/Services/DefaultHtml2PdfService.cs, test/UnitTest/Services/Html2PdfServiceTest.cs
=> doc(IHtml2Pdf): update document for IHtml2Pdf

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Select/MultiSelect.razor.cs
=> feat(MultiSelect): make Clear/SelectAll/InvertSelect methods to public

src/BootstrapBlazor.Server/Components/Samples/Selects.razor, src/BootstrapBlazor.Server/Components/Samples/Selects.razor.cs, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/DateTimePicker/DatePickerBody.razor.scss, src/BootstrapBlazor/Components/Select/MultiSelect.razor.js, src/BootstrapBlazor/Components/Select/Select.razor.js, src/BootstrapBlazor/Components/Select/SelectBase.cs, src/BootstrapBlazor/wwwroot/modules/base-popover.js, test/UnitTest/Components/SelectTest.cs
=> feat(MultiSelect): provider Show/Hide methods for Dropdown components

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/Extensions/Components/BootstrapBlazor.Dock/BootstrapBlazor.Dock.csproj, src/Extensions/Components/BootstrapBlazor.Dock/Components/DockView/DockComponent.cs
=> refactor(DockView): update TitleClass type to string

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/BootstrapBlazor.Server/Components/Components/DataDialogComponent.razor, src/BootstrapBlazor.Server/Components/Samples/DockViews/DockViewCol.razor, src/BootstrapBlazor.Server/Components/Samples/DockViews/DockViewCol.razor.cs, src/BootstrapBlazor.Server/Components/Samples/Print.razor, src/Extensions/Components/BootstrapBlazor.Dock/BootstrapBlazor.Dock.csproj, src/Extensions/Components/BootstrapBlazor.Dock/Components/DockView/DockComponent.cs, src/Extensions/Components/BootstrapBlazor.Dock/Components/DockView/DockView.razor, src/Extensions/Components/BootstrapBlazor.Dock/Components/DockView/DockView.razor.cs, src/Extensions/Components/BootstrapBlazor.Dock/Components/DockView/DockView.razor.js, src/Extensions/Components/BootstrapBlazor.Dock/wwwroot/css/goldenlayout-bb.css
=> feat(DockView): add TitleTemplate parameter

exclusion.dic, src/BootstrapBlazor.Server/Components/Samples/Dialogs.razor, src/BootstrapBlazor.Server/Components/Samples/Dialogs.razor.cs, src/BootstrapBlazor.Server/Components/Samples/Html2Pdfs.razor, src/BootstrapBlazor.Server/Components/Samples/Html2Pdfs.razor.cs, src/BootstrapBlazor.Server/Components/Samples/Html2Pdfs.razor.js, src/BootstrapBlazor.Server/Components/Samples/Modals.razor, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Button/ExportPdfButton.cs, src/BootstrapBlazor/Components/Dialog/DialogOption.cs, src/BootstrapBlazor/Components/Modal/ModalDialog.razor, src/BootstrapBlazor/Components/Modal/ModalDialog.razor.cs, src/BootstrapBlazor/Locales/en.json, src/BootstrapBlazor/Locales/zh.json, src/BootstrapBlazor/Options/ExportPdfButtonOptions.cs, src/BootstrapBlazor/wwwroot/modules/utility.js, test/UnitTest/Components/DialogTest.cs, test/UnitTest/Components/ExportPdfButtonTest.cs, test/UnitTest/Components/ModalDialogTest.cs, test/UnitTest/Core/ExportPdfTestBase.cs
=> feat(ExportPdfButton): add ExportPdfButton component

src/BootstrapBlazor.Server/Components/Samples/ExportPdfButtons.razor, src/BootstrapBlazor.Server/Components/Samples/ExportPdfButtons.razor.cs, src/BootstrapBlazor.Server/Components/Samples/Html2Pdfs.razor, src/BootstrapBlazor.Server/Components/Samples/Html2Pdfs.razor.cs, src/BootstrapBlazor.Server/Extensions/MenusLocalizerExtensions.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor.Server/docs.json
=> doc(ExportPdfButton): add documentation for ExportPdfButton

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/BootstrapBlazor.Server/Components/Samples/VideoPlayers.razor.cs, src/Extensions/Components/BootstrapBlazor.BootstrapIcon.Extensions/BootstrapBlazor.BootstrapIcon.Extensions.csproj, src/Extensions/Components/BootstrapBlazor.BootstrapIcon.Extensions/DefaultIcon.cs, src/Extensions/Components/BootstrapBlazor.MaterialDesign.Extensions/BootstrapBlazor.MaterialDesign.Extensions.csproj, src/Extensions/Components/BootstrapBlazor.MaterialDesign.Extensions/DefaultIcon.cs
=> feat(IconTheme): add Theme icon for extensions

src/BootstrapBlazor.Server/Components/App.razor, src/BootstrapBlazor.Server/Components/Samples/ThemeProviders.razor, src/BootstrapBlazor.Server/Extensions/MenusLocalizerExtensions.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor.Server/docs.json, src/BootstrapBlazor.Server/wwwroot/lib/theme.js, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/ThemeProvider/ThemeLoader.razor, src/BootstrapBlazor/Extensions/JSModuleExtensions.cs, src/BootstrapBlazor/Services/DefaultThemeProvider.cs, src/BootstrapBlazor/wwwroot/modules/theme.js
=> doc(IThemeProvider): add documentation for Theme provider

src/Extensions/Components/BootstrapBlazor.Topology/BootstrapBlazor.Topology.csproj, src/Extensions/Components/BootstrapBlazor.Topology/Components/Topology/Topology.razor.cs, src/Extensions/Components/BootstrapBlazor.Topology/Components/Topology/Topology.razor.js
=> feat(Topology): add IsFitView/IsCenterView options on Scale/Reset method

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/BootstrapBlazor/Options/IconThemeOptions.cs, src/Extensions/Components/BootstrapBlazor.BootstrapIcon.Extensions/BootstrapBlazor.BootstrapIcon.Extensions.csproj, src/Extensions/Components/BootstrapBlazor.BootstrapIcon.Extensions/DefaultIcon.cs, src/Extensions/Components/BootstrapBlazor.MaterialDesign.Extensions/BootstrapBlazor.MaterialDesign.Extensions.csproj, src/Extensions/Components/BootstrapBlazor.MaterialDesign.Extensions/DefaultIcon.cs
=> feat(IconTheme): update fullscreen icon

exclusion.dic, src/BootstrapBlazor.Server/docs.json, src/BootstrapBlazor/Components/Scroll/Scroll.razor.cs, src/BootstrapBlazor/Components/Scroll/Scroll.razor.scss, src/BootstrapBlazor/Components/Table/Table.razor, src/BootstrapBlazor/Components/Table/Table.razor.cs, src/BootstrapBlazor/Options/BootstrapBlazorOptions.cs, src/BootstrapBlazor/Options/ScrollOptions.cs, test/UnitTest/Components/ScrollTest.cs, test/UnitTest/Components/TableTest.cs
=> feat(ScrollOptions): add ScrollOptions on BootstrapBlazorOptions

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Table/Table.razor.cs, src/BootstrapBlazor/Components/Table/Table.razor.js, src/BootstrapBlazor/Components/Table/TableColumnContext.cs, src/BootstrapBlazor/Options/TableSettings.cs, test/UnitTest/Components/TableTest.cs
=> feat(Table): add ColumnMinWidth parameter

src/Extensions/Components/BootstrapBlazor.Topology/BootstrapBlazor.Topology.csproj, src/Extensions/Components/BootstrapBlazor.Topology/Components/Topology/Topology.razor.js
=> refactor(Topology): update code fix reset not work

src/BootstrapBlazor.Server/Components/Components/GlobalSearch.razor, src/BootstrapBlazor.Server/Components/Components/GlobalSearch.razor.css, src/BootstrapBlazor.Server/Components/Components/GlobalSearch.razor.js, src/BootstrapBlazor.Server/Components/Components/Header.razor.css, src/BootstrapBlazor.Server/wwwroot/css/site.css
=> doc(GlobalSearch): update style for global-search

src/BootstrapBlazor.Server/Components/Components/GlobalSearch.razor.css, src/BootstrapBlazor.Server/Components/Components/GlobalSearch.razor.js
=> doc(GlobalSearch): add input event support

src/BootstrapBlazor.Server/Components/Components/GlobalSearch.razor.css, src/BootstrapBlazor.Server/Components/Components/GlobalSearch.razor.js
=> doc(GlobalSearch): adapt to mobile devices

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/BootstrapBlazor.Server/Components/Samples/Charts/Line.razor.cs, src/Extensions/Components/BootstrapBlazor.Chart/BootstrapBlazor.Chart.csproj, src/Extensions/Components/BootstrapBlazor.Chart/Components/Chart/Chart.razor.js, src/Extensions/Components/BootstrapBlazor.Chart/Components/Chart/ChartDataset.cs
=> fix(Chart): ShowPointStyle not work

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Button/Button.razor.cs, src/BootstrapBlazor/Components/Button/ButtonBase.cs
=> feat(Button): add IsKeepDisabled parameter

src/BootstrapBlazor.Server/Controllers/Api/SearchController.cs, src/BootstrapBlazor.Server/Data/GiteePushBody.cs
=> doc(SearchController): add push branch check

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/BootstrapBlazor.Server/Components/Components/GlobalSearch.razor.css, src/BootstrapBlazor.Server/Components/Components/GlobalSearch.razor.js, src/BootstrapBlazor.Server/Controllers/Api/SearchController.cs, src/BootstrapBlazor.Server/wwwroot/css/site.css
=> doc(GlobalSearch): add highlight key word

src/BootstrapBlazor.Server/Components/Components/GlobalSearch.razor.css, src/BootstrapBlazor.Server/Components/Components/Header.razor.js, src/BootstrapBlazor.Server/Components/Components/ThemeMode.razor, src/BootstrapBlazor.Server/Components/Components/ThemeMode.razor.cs, src/BootstrapBlazor.Server/Components/Layout/BaseLayout.razor.css, src/BootstrapBlazor.Server/wwwroot/css/site.css, src/BootstrapBlazor/Components/ThemeProvider/ThemeProvider.razor.js
=> doc(Theme): add switch theme transition

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Upload/CardUpload.razor, src/BootstrapBlazor/wwwroot/modules/upload.js, test/UnitTest/Components/UploadTest.cs
=> feat(CardUpload): auto zoom when click preview image

src/BootstrapBlazor/Components/Button/Button.razor.js, src/BootstrapBlazor/Components/Button/ShareButton.cs, src/BootstrapBlazor/Components/Filters/SearchFilterAction.cs, test/UnitTest/Components/ButtonTest.cs, test/UnitTest/Extensions/QueryPageOptionsExtensionsTest.cs
=> test(Button): improve code coverage

src/Extensions/Components/BootstrapBlazor.SVGEditor/BootstrapBlazor.SvgEditor.csproj, src/Extensions/Components/BootstrapBlazor.SVGEditor/Components/SvgEditor/SvgEditor.razor, src/Extensions/Components/BootstrapBlazor.SVGEditor/Components/SvgEditor/SvgEditor.razor.cs, src/Extensions/Components/BootstrapBlazor.SVGEditor/Components/SvgEditor/SvgEditor.razor.js
=> feat(SvgEdtior): add UpdateAsync method for the SvgEditor

src/BootstrapBlazor/Components/ClockPicker/ClockPicker.razor.js, src/BootstrapBlazor/Components/DateTimePicker/DatePickerBody.razor.cs, src/BootstrapBlazor/Components/DateTimePicker/DatePickerBody.razor.scss, src/BootstrapBlazor/Components/DateTimeRange/DateTimeRange.razor, src/BootstrapBlazor/Components/DateTimeRange/DateTimeRange.razor.cs, src/BootstrapBlazor/Enums/DateTimeRangeRenderMode.cs, test/UnitTest/Components/DateTimePickerTest.cs, test/UnitTest/Components/DateTimeRangeTest.cs
=> refactor(DateTimeRange): remove unused code and improve code coverage

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/BootstrapBlazor.Server/Components/Samples/Messages.razor, src/BootstrapBlazor.Server/Components/Samples/Messages.razor.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/Components/Message/Message.razor.cs, src/BootstrapBlazor/Components/Message/MessageOption.cs, src/BootstrapBlazor/Enums/MessageShowMode.cs, test/UnitTest/Components/MessageTest.cs
增加LastOnly选项，可以让Message仅显示一次
close #3530
=> feat(Message): add ShowMode parameter

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Services/TableMetadataTypeService.cs, test/UnitTest/Utils/UtilityTest.cs
=> feat(MetadataTypeService): update typo error

src/BootstrapBlazor.Server/Components/Samples/Table/TablesEdit.razor.cs
=> doc(Table): update sample code for MultipSelect in EditTemplate

src/BootstrapBlazor.Server/Components/Components/DemoTableEditTemplate.razor, src/BootstrapBlazor.Server/Components/Samples/Table/TablesEdit.razor, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Table/Table.razor.js
=> fix(Table): throw exception resize column when empty data

src/Extensions/Components/BootstrapBlazor.Dock/BootstrapBlazor.Dock.csproj, src/Extensions/Components/BootstrapBlazor.Dock/Components/DockView/DockView.razor.js
=> feat(Dock): keep tool button on header when drag tab

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/RibbonTab/RibbonTab.razor.cs, src/BootstrapBlazor/Components/RibbonTab/RibbonTab.razor.scss, src/Extensions/Components/BootstrapBlazor.BootstrapIcon.Extensions/BootstrapBlazor.BootstrapIcon.Extensions.csproj, src/Extensions/Components/BootstrapBlazor.BootstrapIcon.Extensions/DefaultIcon.cs, src/Extensions/Components/BootstrapBlazor.MaterialDesign.Extensions/BootstrapBlazor.MaterialDesign.Extensions.csproj, src/Extensions/Components/BootstrapBlazor.MaterialDesign.Extensions/DefaultIcon.cs
=> feat(RibbonTab): update style sheet use scss

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Collapse/Collapse.razor
=> fix(Collapse): collapsed status incorrect

src/BootstrapBlazor.Server/Components/Samples/Table/TablesExcel.razor, src/BootstrapBlazor/Attributes/AutoGenerateColumnAttribute.cs, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Table/ITableColumn.cs, src/BootstrapBlazor/Components/Table/InternalTableColumn.cs, src/BootstrapBlazor/Components/Table/TableColumn.cs, test/UnitTest/Attributes/AutoGenerateClassTest.cs
=> doc(Table): update OnSaveAsync documentation

src/BootstrapBlazor.Server/Components/Samples/Table/TablesWrap.razor, src/BootstrapBlazor.Server/Components/Samples/Table/TablesWrap.razor.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Extensions/ITableColumnExtensions.cs
=> refactor(Table): update GetTooltipTextCallback logic

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Localization/ILocalizationMissingItemHandler.cs, src/BootstrapBlazor/Localization/Json/JsonLocalizationServiceCollectionExtensions.cs, src/BootstrapBlazor/Localization/Json/JsonStringLocalizer.cs, src/BootstrapBlazor/Localization/Json/JsonStringLocalizerFactory.cs, src/BootstrapBlazor/Localization/NullLocalizationMissingItemHandler.cs, test/UnitTest/Localization/JsonStringLocalizerTest.cs, test/UnitTest/UnitTest.csproj
add ILocalizationMissingItemHandler for missing localization item
close #3585 
link #3580
=> feat(Localization): add ILocalizationMissingItemHandler

src/BootstrapBlazor.Server/Components/Components/ResultDialogDemo.razor.cs, src/BootstrapBlazor.Server/Components/Components/ResultDialogDemo2.razor.cs, src/BootstrapBlazor.Server/Components/Samples/Dialogs.razor, src/BootstrapBlazor.Server/Components/Samples/Dialogs.razor.cs, src/BootstrapBlazor/Components/Dialog/Dialog.razor.cs, src/BootstrapBlazor/Components/Dialog/DialogOption.cs, src/BootstrapBlazor/Components/Dialog/IResultDialog.cs, src/BootstrapBlazor/Components/Dialog/ResultDialogFooter.razor, src/BootstrapBlazor/Components/Dialog/ResultDialogFooter.razor.cs, src/BootstrapBlazor/Components/Dialog/ResultDialogOption.cs, src/BootstrapBlazor/Components/Dialog/SearchDialog.razor, src/BootstrapBlazor/Components/EditorForm/EditorItem.cs, src/BootstrapBlazor/Components/Modal/ModalDialog.razor, src/BootstrapBlazor/Components/Modal/ModalDialog.razor.cs, src/BootstrapBlazor/Components/Table/Table.razor.scss, src/BootstrapBlazor/Extensions/DialogServiceExtensions.cs, test/UnitTest/Components/ButtonTest.cs, test/UnitTest/Components/DialogTest.cs
=> feat(Dialog): redesign ShowModal extension method of DialogService

src/BootstrapBlazor.Server/Components/Samples/ColorPickers.razor, src/BootstrapBlazor.Server/Components/Samples/ColorPickers.razor.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/ColorPicker/ColorPicker.razor, src/BootstrapBlazor/Components/ColorPicker/ColorPicker.razor.cs, test/UnitTest/Components/ColorPickerTest.cs, test/UnitTest/Components/DialogTest.cs
=> feat(ColorPicker): add Formatter parameter

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Dialog/DialogSaveButton.cs, src/BootstrapBlazor/Enums/ComponentIcons.cs, test/UnitTest/Components/ButtonTest.cs
=> feat(DialogSaveButton): add OnSaveAsync parameter

src/BootstrapBlazor.Server/Components/Samples/ValidateForms.razor.cs, src/BootstrapBlazor/Attributes/FileValidationAttribute.cs, src/BootstrapBlazor/Components/Validate/ValidateBase.cs, src/BootstrapBlazor/Components/ValidateForm/ValidateForm.razor.cs, test/UnitTest/Components/ValidateTest.cs
=> feat(Validate): auto provider memeber name when custom validate rule

exclusion.dic, src/BootstrapBlazor.Server/Components/Components/ComponentCard.razor, src/BootstrapBlazor.Server/Components/Samples/ImageViewers.razor, src/BootstrapBlazor.Server/Components/Samples/ImageViewers.razor.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/Components/ImageViewer/ImageViewer.razor, src/BootstrapBlazor/Components/ImageViewer/ImageViewer.razor.cs, src/BootstrapBlazor/Components/ImageViewer/ImageViewer.razor.js, test/UnitTest/Components/ImageTest.cs
=> feat(ImageViewer): add IsIntersectionObserver parameter

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/ThemeProvider/ThemeProvider.razor, src/BootstrapBlazor/Components/ThemeProvider/ThemeProvider.razor.cs, test/UnitTest/Components/ThemeProviderTest.cs
=> feat(ThemeProvider): add ShowShadow/Alignment parameter

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Select/MultiSelect.razor, src/BootstrapBlazor/Components/Select/MultiSelect.razor.cs, src/BootstrapBlazor/Components/Select/MultiSelect.razor.scss, src/BootstrapBlazor/Components/Select/Select.razor.cs, src/BootstrapBlazor/Components/Select/SelectBase.cs, src/BootstrapBlazor/Enums/ComponentIcons.cs, src/BootstrapBlazor/Options/IconThemeOptions.cs, src/Extensions/Components/BootstrapBlazor.BootstrapIcon.Extensions/BootstrapBlazor.BootstrapIcon.Extensions.csproj, src/Extensions/Components/BootstrapBlazor.BootstrapIcon.Extensions/DefaultIcon.cs, src/Extensions/Components/BootstrapBlazor.MaterialDesign.Extensions/BootstrapBlazor.MaterialDesign.Extensions.csproj, src/Extensions/Components/BootstrapBlazor.MaterialDesign.Extensions/DefaultIcon.cs
=> feat(MultiSelect): add right icon like select

src/BootstrapBlazor.Server/Components/Components/Wwads.razor, src/BootstrapBlazor.Server/Components/Components/Wwads.razor.cs, src/BootstrapBlazor.Server/Components/Components/Wwads.razor.js, src/BootstrapBlazor.Server/Components/Layout/TutorialsLayout.razor, src/BootstrapBlazor.Server/wwwroot/css/site.css
=> doc(ad): add ccbmp ad component

src/BootstrapBlazor.Server/Components/Samples/Table/Tables.razor.cs, src/BootstrapBlazor.Server/Components/Samples/Table/TablesColumn.razor, src/BootstrapBlazor.Server/Components/Samples/Table/TablesSelection.razor, src/BootstrapBlazor.Server/Components/Samples/Table/TablesSelection.razor.cs, src/BootstrapBlazor.Server/Components/Samples/Table/TablesSelection.razor.css, src/BootstrapBlazor.Server/Components/Samples/Table/TablesSelection.razor.js, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Table/Table.razor.cs, src/BootstrapBlazor/Components/Table/Table.razor.js, src/BootstrapBlazor/Extensions/IEditorItemExtensions.cs, test/UnitTest/Components/TableTest.cs, test/UnitTest/Extensions/ObjectExtensionsTest.cs, test/UnitTest/Performance/TaskTest.cs
=> feat(Table): add OnAfterRenderCallback parameter

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Table/Table.razor.cs
when set IsDetailRow=true and ShownWithBreakPoint = BreakPoint.Large
close #3613
=> fix(Table): colspan incorrect 

src/BootstrapBlazor/Components/Select/Select.razor, src/BootstrapBlazor/Components/Select/Select.razor.cs, src/BootstrapBlazor/Components/Table/Table.razor.cs, test/UnitTest/Components/TableTest.cs
=> refactor(Select): update ICollection to List for performance

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/BaseComponents/BootstrapComponentBase.cs, src/BootstrapBlazor/Components/Table/Table.razor
=> feat(Table): add ShowSearchButton control search button

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Table/Table.razor, test/UnitTest/Components/TableTest.cs
=> refactor(Table): update ShowSearchButton function

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Layout/Layout.razor.cs
=> fix(Layout): block application when use async method in OnAuthorizing callback

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/Extensions/Components/BootstrapBlazor.Dock/BootstrapBlazor.Dock.csproj, src/Extensions/Components/BootstrapBlazor.Dock/Components/DockView/DockComponent.razor, src/Extensions/Components/BootstrapBlazor.Dock/Components/DockView/DockComponent.razor.cs, src/Extensions/Components/BootstrapBlazor.Dock/Components/DockView/DockView.razor, src/Extensions/Components/BootstrapBlazor.Dock/Components/DockView/DockView.razor.cs, src/Extensions/Components/BootstrapBlazor.Dock/Components/DockView/DockView.razor.js, src/Extensions/Components/BootstrapBlazor.Dock/Components/DockView/DockViewConfig.cs, src/Extensions/Components/BootstrapBlazor.Dock/wwwroot/css/goldenlayout-bb.css
=> refactor(Dock): streamline code and refactor logic

src/BootstrapBlazor.Server/Components/Samples/InputGroups.razor, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Input/BootstrapInputGroup.razor.scss, src/BootstrapBlazor/wwwroot/scss/root.scss
=> feat(RadioList): add style for in InputGroup

src/BootstrapBlazor.Server/Components/Components/GlobalSearch.razor.js
=> feat(GlobalSearch): auto close the search dialog

exclusion.dic, src/BootstrapBlazor.Server/Components/Components/Wwads.razor, src/BootstrapBlazor.Server/Components/Components/Wwads.razor.cs, src/BootstrapBlazor.Server/Components/Components/Wwads.razor.js, src/BootstrapBlazor.Server/Components/Layout/TutorialsLayout.razor, src/BootstrapBlazor.Server/Components/Layout/TutorialsNavMenu.razor.css, src/BootstrapBlazor.Server/wwwroot/css/wwads.css
=> doc(Ad): redesign wwads component

src/BootstrapBlazor.Server/Components/Pages/Index.razor, src/BootstrapBlazor.Server/Components/Pages/Index.razor.css
=> doc(Index): update style for target framework

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/BootstrapBlazor.Server/Components/Samples/DockViews2/DockViewComplex.razor, src/BootstrapBlazor.Server/Components/Samples/DockViews2/DockViewLayout.razor, src/BootstrapBlazor.Server/Components/Samples/DockViews2/DockViewNest.razor, src/BootstrapBlazor.Server/Components/Samples/DockViews2/DockViewRow.razor, src/BootstrapBlazor.Server/Components/Samples/DockViews2/DockViewVisible.razor, src/BootstrapBlazor.Server/Directory.Build.targets, src/Extensions/Components/BootstrapBlazor.DockView/BootstrapBlazor.DockView.csproj, src/Extensions/Components/BootstrapBlazor.DockView/Components/DockViewComponent.razor, src/Extensions/Components/BootstrapBlazor.DockView/Components/DockViewComponent.razor.cs, src/Extensions/Components/BootstrapBlazor.DockView/Components/DockViewConfig.cs, src/Extensions/Components/BootstrapBlazor.DockView/Components/DockViewDropdownIcon.razor, src/Extensions/Components/BootstrapBlazor.DockView/Components/DockViewDropdownIcon.razor.cs, src/Extensions/Components/BootstrapBlazor.DockView/Components/DockViewIcon.razor, src/Extensions/Components/BootstrapBlazor.DockView/Components/DockViewIcon.razor.cs, src/Extensions/Components/BootstrapBlazor.DockView/Components/DockViewV2.razor, src/Extensions/Components/BootstrapBlazor.DockView/Components/DockViewV2.razor.cs, src/Extensions/Components/BootstrapBlazor.DockView/wwwroot/css/dockview-bb.css, src/Extensions/Components/BootstrapBlazor.DockView/wwwroot/icon/dockview.svg, src/Extensions/Components/BootstrapBlazor.DockView/wwwroot/js/dockview-extensions.js, src/Extensions/Components/BootstrapBlazor.DockView/wwwroot/js/dockview-utils.js
=> refactor(DockViewV2): update render logic

src/Extensions/Components/BootstrapBlazor.Topology/BootstrapBlazor.Topology.csproj, src/Extensions/Components/BootstrapBlazor.Topology/Components/Topology/TopologyItem.cs
=> feat(Topology): add background paramer

src/BootstrapBlazor/Components/Table/Table.razor.js
=> fix(Table): setTableDefaultWidth not work

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/Extensions/Components/BootstrapBlazor.BootstrapIcon.Extensions/BootstrapBlazor.BootstrapIcon.Extensions.csproj, src/Extensions/Components/BootstrapBlazor.MaterialDesign.Extensions/BootstrapBlazor.MaterialDesign.Extensions.csproj
=> refactor(IconTheme): bump version 8.0.8

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Checkbox/CheckboxList.razor.cs
=> fix(Checkbox): check active state incorrect

src/BootstrapBlazor.Server/Components/Samples/ListViews.razor, src/BootstrapBlazor.Server/Components/Samples/ListViews.razor.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/ListView/ListView.razor, src/BootstrapBlazor/Components/ListView/ListView.razor.cs, test/UnitTest/Components/ListViewTest.cs
=> feat(ListView): add group order callback parameter

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Select/Select.razor.cs
=> fix(Select): DisableItemChangedWhenFirstRender not work

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Table/Table.razor.cs
=> fix(Table): ShowColumnList item incorrect if remove column by OnColumnCreating

src/BootstrapBlazor.Server/Components/Components/Header.razor, src/BootstrapBlazor.Server/wwwroot/css/site.css
=> doc(Themes): add themes website menu

src/Extensions/Components/BootstrapBlazor.Dock/BootstrapBlazor.Dock.csproj, src/Extensions/Components/BootstrapBlazor.Dock/Components/DockView/DockView.razor.js, src/Extensions/Components/BootstrapBlazor.Dock/wwwroot/js/golden-layout-config.js, src/Extensions/Components/BootstrapBlazor.Dock/wwwroot/js/golden-layout-extensions.js, src/Extensions/Components/BootstrapBlazor.Dock/wwwroot/js/golden-layout-utility.js
=> refactor(Dock): bump version 8.1.7

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/BootstrapBlazor.Server/Components/Samples/FlipClocks.razor, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/FlipClock/FlipClock.razor, src/BootstrapBlazor/Components/FlipClock/FlipClock.razor.cs, test/UnitTest/Components/FlipClockTest.cs
=> feat(FlipClock): add ShowSecond parameter

src/BootstrapBlazor.Server/Components/Samples/EditorForms.razor, src/BootstrapBlazor/Components/Table/Table.razor.js
=> fix(table): add Observer table width

src/BootstrapBlazor.Server/Components/Samples/Table/TablesEdit.razor, src/BootstrapBlazor.Server/Components/Samples/Table/TablesEdit.razor.cs, src/BootstrapBlazor.Server/Data/Foo.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/Components/ValidateForm/ValidateForm.razor.cs, src/BootstrapBlazor/Extensions/IEditorItemExtensions.cs, src/BootstrapBlazor/Extensions/ObjectExtensions.cs, src/BootstrapBlazor/Extensions/PropertyInfoExtensions.cs, src/BootstrapBlazor/Utils/Utility.cs, test/UnitTest/Components/TableFooterCellTest.cs, test/UnitTest/Core/FooContext.cs
=> doc(Table): add sample code for Table link readonly column

src/BootstrapBlazor.Server/Components/Samples/Icons.razor, src/BootstrapBlazor.Server/Components/Samples/Icons.razor.cs, src/BootstrapBlazor.Server/Components/Samples/Icons.razor.css, src/BootstrapBlazor.Server/Extensions/MenusLocalizerExtensions.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor.Server/docs.json, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Icon/BootstrapBlazorIcon.razor, src/BootstrapBlazor/Components/Icon/BootstrapBlazorIcon.razor.cs, src/BootstrapBlazor/Components/Icon/BootstrapBlazorIcon.razor.scss, src/BootstrapBlazor/wwwroot/scss/components.scss, src/Extensions/Components/BootstrapBlazor.IconPark/SvgIcon.razor.cs, test/UnitTest/Components/IconTest.cs
=> feat(Icon): add BootstrapBlazorIcon component

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/AutoComplete/AutoComplete.razor, src/BootstrapBlazor/Components/AutoComplete/PopoverCompleteBase.cs, src/BootstrapBlazor/Components/AutoFill/AutoFill.razor, src/BootstrapBlazor/Components/Search/Search.razor, test/UnitTest/Components/AutoCompleteTest.cs
=> feat(Search): add ShowNoDataTip parameter

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Button/PopConfirmButton.razor.js, src/BootstrapBlazor/Components/Button/PopConfirmButtonContent.razor, src/BootstrapBlazor/Components/Button/PopConfirmButtonContent.razor.cs, src/BootstrapBlazor/Components/Button/PopConfirmButtonContent.razor.js, test/UnitTest/Components/PopConfirmButtonTest.cs
=> refactor(PopConfirmButton): update javascript callback logic

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Filters/MultiFilter.razor, src/BootstrapBlazor/Components/Filters/MultiFilter.razor.cs
Update components after changes in the Items data source
close #3738
=> feat(MultiFilter): Update components after changes in the Items data source

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/Extensions/Components/BootstrapBlazor.Html2Pdf/BootstrapBlazor.Html2Pdf.csproj, src/Extensions/Components/BootstrapBlazor.Html2Pdf/Services/DefaultPdfService.cs
=> refactor(Html2Pdf): update PuppeteerSharp to 18.0.2

src/BootstrapBlazor.Server/Components/Samples/CheckboxLists.razor, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/Components/Checkbox/Checkbox.razor.cs, src/BootstrapBlazor/Components/Checkbox/CheckboxList.razor
=> fix(CheckboxList): ShowLabelTooltip not work

src/Extensions/DataServices/BootstrapBlazor.DataAccess.FreeSql/BootstrapBlazor.DataAccess.FreeSql.csproj, src/Extensions/DataServices/BootstrapBlazor.DataAccess.FreeSql/FreeSqlExtensions.cs
=> feat(FreeSqlExtensions): support MultiFilter component

src/BootstrapBlazor.Server/Components/Components/CustomPopConfirmContent.razor, src/BootstrapBlazor.Server/Components/Components/CustomPopConfirmContent.razor.cs, src/BootstrapBlazor.Server/Components/Samples/PopoverConfirms.razor, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/Components/Button/PopConfirmButtonContent.razor, src/BootstrapBlazor/Components/Button/PopConfirmButtonContent.razor.scss, src/BootstrapBlazor/wwwroot/scss/theme/bootstrap.blazor.scss, test/UnitTest/Components/PopConfirmButtonTest.cs
=> doc(PopConfirmButton): add sample code for custom button

src/BootstrapBlazor.Server/Components/Layout/MainLayout.razor.cs, src/BootstrapBlazor.Server/Components/Samples/Dispatches.razor, src/BootstrapBlazor.Server/Components/Samples/Dispatches.razor.cs, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Services/IPLocator/DefaultIpLocatorFactory.cs
=> doc(Dispatch): update sample code

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Select/Select.razor, src/BootstrapBlazor/Components/Select/Select.razor.cs, src/BootstrapBlazor/Components/Tab/Tab.razor.cs, test/UnitTest/Components/SelectTest.cs
=> fix(Tab): auto adjust position use in Layout

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Filters/MultiFilter.razor.cs
=> fix(MultiFilter): missing item selection status

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Table/Table.razor.js, src/BootstrapBlazor/wwwroot/modules/utility.js
=> fix(Table): column resize not work in mobile

src/BootstrapBlazor/Components/Filters/MultiFilter.razor.cs
MultiFilter 组件在第二次打开时会丢失已选择项的状态。
close #3776
=> fix(MultiFilter): not keep selected items open again

src/BootstrapBlazor.Server/Components/Samples/Clipboards.razor, src/BootstrapBlazor.Server/Components/Samples/Clipboards.razor.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/Components/Clipboard/Clipboard.cs, src/BootstrapBlazor/Components/Clipboard/ClipboardService.cs, src/BootstrapBlazor/Services/BootstrapServiceBase.cs, src/BootstrapBlazor/wwwroot/modules/utility.js, test/UnitTest/Services/ClipboardTest.cs
=> feat(ClipboardService): support getTextFromClipboard

src/BootstrapBlazor.Server/Components/Samples/Table/TablesSelection.razor.cs, src/BootstrapBlazor.Server/Components/Samples/Table/TablesSelection.razor.js, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/Components/Table/Table.razor.cs, src/BootstrapBlazor/Components/Table/Table.razor.js, src/BootstrapBlazor/Enums/ScrollToViewAlign.cs, test/UnitTest/Components/TableTest.cs
=> feat(Table): add AutoScrollVerticalAlign parameter

src/BootstrapBlazor/Components/Table/Table.razor.Localization.cs, src/BootstrapBlazor/Components/Table/Table.razor.cs, src/BootstrapBlazor/Components/Table/Table.razor.js, src/BootstrapBlazor/Locales/en.json, src/BootstrapBlazor/Locales/zh.json, test/UnitTest/Components/ButtonTest.cs, test/UnitTest/Components/TableTest.cs
=> feat(ShowColumnToolbox): add ShowColumnWidthTooltip parameter

src/BootstrapBlazor.Server/Components/Samples/Clipboards.razor, src/BootstrapBlazor.Server/Components/Samples/Clipboards.razor.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/Components/Clipboard/Clipboard.cs, src/BootstrapBlazor/Components/Clipboard/ClipboardItem.cs, src/BootstrapBlazor/Components/Clipboard/ClipboardService.cs, src/BootstrapBlazor/wwwroot/modules/utility.js, test/UnitTest/Services/ClipboardTest.cs
=> feat(ClipboardService): add Get method on service

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Filters/TableFilter.razor.cs, src/BootstrapBlazor/Components/Table/Table.razor.cs, test/UnitTest/Components/TableTest.cs
=> fix(Table): scroll to top when click row on VirtualScroll mode

src/BootstrapBlazor.Server/Components/Samples/Table/TablesAutoRefresh.razor.cs
=> doc(Table): update AutoRefresh sample code

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Filters/MultiFilter.razor.cs, src/BootstrapBlazor/Components/Filters/MultiFilter.razor.js, test/UnitTest/Components/TableFilterTest.cs
=> feat(MultiFilter): add AlwaysTriggerGetItems parameter

src/BootstrapBlazor/wwwroot/modules/base-popover.js
=> fix(Popover): fixed the flickering issue when closing pop-up windows

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Filters/MultiFilter.razor.cs, src/BootstrapBlazor/Components/Filters/MultiFilter.razor.js, test/UnitTest/Components/TableFilterTest.cs
=> feat(MultiFilter): keep selected item when AlwaysTriggerGetItems is true

src/BootstrapBlazor/Components/Tooltip/Tooltip.razor, src/BootstrapBlazor/Components/Tooltip/Tooltip.razor.cs, src/BootstrapBlazor/Components/Tooltip/Tooltip.razor.js, test/UnitTest/Components/TooltipTest.cs
=> feat(Tooltip): add FallbackPlacements parameter

src/BootstrapBlazor.Server/Components/Samples/Tooltips.razor.cs, src/BootstrapBlazor/Components/Tooltip/Tooltip.razor, src/BootstrapBlazor/Components/Tooltip/Tooltip.razor.cs, test/UnitTest/Components/TooltipTest.cs
=> feat(Tooltip): add Offset parameter

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Modal/Modal.razor.js
=> fix(Dialog): do not remove when browser go back/forward

src/BootstrapBlazor.Server/Components/Samples/Table/TablesAttribute.razor, src/BootstrapBlazor.Server/Components/Samples/Table/TablesAttribute.razor.cs, src/BootstrapBlazor.Server/Extensions/MenusLocalizerExtensions.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json
=> doc(AutoGenerateClassAttribute): add docmentation for auto class/column attribute

src/Extensions/Components/BootstrapBlazor.Topology/BootstrapBlazor.Topology.csproj, src/Extensions/Components/BootstrapBlazor.Topology/Components/Topology/TopologyItem.cs
=> fix(Topology): missing background cause value is null

src/BootstrapBlazor.Server/Components/Samples/DockViews2/DockViewGroup.razor, src/Extensions/Components/BootstrapBlazor.DockView/BootstrapBlazor.DockView.csproj, src/Extensions/Components/BootstrapBlazor.DockView/wwwroot/css/dockview.css, src/Extensions/Components/BootstrapBlazor.DockView/wwwroot/js/dockview-core.esm.js
=> fix(DockViewV2): re-layout issue after dragging panel

src/BootstrapBlazor.Server/Components/Samples/Table/TablesEdit.razor, src/BootstrapBlazor.Server/Components/Samples/Topologies.razor, src/Extensions/Components/BootstrapBlazor.Topology/Components/Topology/Topology.razor.cs, src/Extensions/Components/BootstrapBlazor.Topology/Components/Topology/Topology.razor.js
=> feat(Topology): add IsDisableHover parameter

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/Extensions/Components/BootstrapBlazor.BootstrapIcon.Extensions/BootstrapBlazor.BootstrapIcon.Extensions.csproj, src/Extensions/Components/BootstrapBlazor.BootstrapIcon.Extensions/DefaultIcon.cs, src/Extensions/Components/BootstrapBlazor.MaterialDesign.Extensions/BootstrapBlazor.MaterialDesign.Extensions.csproj, src/Extensions/Components/BootstrapBlazor.MaterialDesign.Extensions/DefaultIcon.cs, src/Extensions/Components/BootstrapBlazor.MaterialDesign.Extensions/ServiceCollectionExtensions.cs
=> doc(IconTheme): add TableColumnToolboxIcon

src/BootstrapBlazor/Components/Table/Table.razor.cs, test/UnitTest/Components/TableTest.cs, test/UnitTest/Dynamic/DataTableDynamicContextTest.cs, test/UnitTest/Localization/JsonStringLocalizerTest.cs, test/UnitTest/UnitTest.csproj
=> feat(Table): add ResetSortAsync method

src/BootstrapBlazor.Server/Components/Samples/Table/TablesToolbar.razor, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/Components/Table/Table.razor.Edit.cs
=> doc(Table): add documation for ShowRefresh

src/Extensions/Components/BootstrapBlazor.DockView/BootstrapBlazor.DockView.csproj, src/Extensions/Components/BootstrapBlazor.DockView/wwwroot/js/dockview-core.esm.js, src/Extensions/Components/BootstrapBlazor.DockView/wwwroot/js/dockview-group.js, src/Extensions/Components/BootstrapBlazor.DockView/wwwroot/js/dockview-panel.js, src/Extensions/Components/BootstrapBlazor.DockView/wwwroot/js/dockview-utils.js
=> feat(DockView): add keep position function

src/Extensions/Components/BootstrapBlazor.DockView/BootstrapBlazor.DockView.csproj, src/Extensions/Components/BootstrapBlazor.DockView/wwwroot/js/dockview-config.js
=> refactor(DockView): update dockview-config.js

src/BootstrapBlazor.Server/appsettings.Development.json, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Table/Table.razor, src/BootstrapBlazor/Components/Table/Table.razor.cs, src/BootstrapBlazor/Components/TreeView/TreeView.razor.cs, src/BootstrapBlazor/Options/BootstrapBlazorOptions.cs, src/BootstrapBlazor/Options/ContextMenuOptions.cs, test/UnitTest/Options/BootstrapBlazorOptionsTest.cs
=> feat(BootstrapBlazorOptions): add ContextMenuOptions class

src/BootstrapBlazor.Server/Components/Pages/GlobalOption.razor, src/BootstrapBlazor.Server/Components/Pages/Globalization.razor, src/BootstrapBlazor.Server/Extensions/MenusLocalizerExtensions.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json
=> doc(GlobalOptions): add GlobalOpton documentation

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Options/IconThemeOptions.cs
=> feat(TreeView): update ResetSearchButton icon

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/Extensions/Components/BootstrapBlazor.BootstrapIcon.Extensions/BootstrapBlazor.BootstrapIcon.Extensions.csproj, src/Extensions/Components/BootstrapBlazor.BootstrapIcon.Extensions/DefaultIcon.cs, src/Extensions/Components/BootstrapBlazor.MaterialDesign.Extensions/BootstrapBlazor.MaterialDesign.Extensions.csproj, src/Extensions/Components/BootstrapBlazor.MaterialDesign.Extensions/DefaultIcon.cs
=> feat(TreeView): update icon for clear search bar

src/BootstrapBlazor.Server/Components/Components/CustomTableRow.razor, src/BootstrapBlazor.Server/Components/Components/CustomTableRow.razor.cs, src/BootstrapBlazor.Server/Components/Samples/Table/TablesRow.razor, src/BootstrapBlazor.Server/Components/Samples/Table/TablesRow.razor.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/Components/Table/Table.razor, src/BootstrapBlazor/Components/Table/Table.razor.cs, src/BootstrapBlazor/Components/Table/TableColumnContext.cs, src/BootstrapBlazor/Components/Table/TableRowContext.cs, test/UnitTest/Attributes/AutoGenerateClassTest.cs, test/UnitTest/Components/ButtonTest.cs, test/UnitTest/Components/ContextMenuTest.cs, test/UnitTest/Components/TableColumnTest.cs, test/UnitTest/Components/TableTest.cs, test/UnitTest/Extensions/ITableColumnExtensionsTest.cs
=> feat(Table): add RowTemplate

src/Extensions/Components/BootstrapBlazor.DockView/BootstrapBlazor.DockView.csproj, src/Extensions/Components/BootstrapBlazor.DockView/wwwroot/js/dockview-config.js, src/Extensions/Components/BootstrapBlazor.DockView/wwwroot/js/dockview-extensions.js, src/Extensions/Components/BootstrapBlazor.DockView/wwwroot/js/dockview-group.js, src/Extensions/Components/BootstrapBlazor.DockView/wwwroot/js/dockview-panel.js, src/Extensions/Components/BootstrapBlazor.DockView/wwwroot/js/dockview-utils.js
=> refactor(DockView): update addPanel method

src/Extensions/Components/BootstrapBlazor.DockView/BootstrapBlazor.DockView.csproj, src/Extensions/Components/BootstrapBlazor.DockView/wwwroot/js/dockview-extensions.js, src/Extensions/Components/BootstrapBlazor.DockView/wwwroot/js/dockview-group.js, src/Extensions/Components/BootstrapBlazor.DockView/wwwroot/js/dockview-panel.js, src/Extensions/Components/BootstrapBlazor.DockView/wwwroot/js/dockview-utils.js
=> fix(DockView): update keep active panel logic

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Camera/Camera.razor.js
=> fix(Camera): videoWidth/videoHeight not work

src/BootstrapBlazor.Server/Components/Samples/Tabs.razor, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Table/TableColumn.cs, src/BootstrapBlazor/Components/Table/TableTemplateColumn.cs
=> feat(TableTemplateColumn): add TableTemplateColumn component

src/BootstrapBlazor.Server/Components/Samples/Table/TablesEdit.razor, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/EditorForm/EditorForm.razor.cs, src/BootstrapBlazor/Components/Table/Table.razor.Toolbar.cs, src/BootstrapBlazor/Components/Table/Table.razor.js, src/BootstrapBlazor/Extensions/IEditorItemExtensions.cs, test/UnitTest/Components/EditorFormTest.cs, test/UnitTest/Components/TableDialogTest.cs, test/UnitTest/Components/TableTemplateColumnTest.cs, test/UnitTest/Components/TableTest.cs
=> refactor(Table): support Add/Edit function

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Select/SelectTable.razor, src/BootstrapBlazor/Components/Select/SelectTable.razor.cs, test/UnitTest/Components/SelectTableTest.cs
=> feat(SelectTable): add AutoGenerateColumns parameter

src/BootstrapBlazor.Server/Components/Samples/Masks.razor, src/BootstrapBlazor.Server/Components/Samples/Masks.razor.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Mask/Mask.razor, src/BootstrapBlazor/Components/Mask/Mask.razor.cs, src/BootstrapBlazor/Components/Mask/Mask.razor.js, src/BootstrapBlazor/Components/Mask/Mask.razor.scss, src/BootstrapBlazor/Components/Mask/MaskOption.cs, src/BootstrapBlazor/Components/Mask/MaskService.cs, test/UnitTest/Services/MaskServiceTest.cs
=> feat(Mask): add ContainerId parameter

src/Extensions/Components/BootstrapBlazor.Chart/BootstrapBlazor.Chart.csproj, src/Extensions/Components/BootstrapBlazor.Chart/Components/Chart/Chart.razor.js, src/Extensions/Components/BootstrapBlazor.Chart/Components/Chart/ChartOptions.cs
=> feat(Chart): support min/max on Y axis

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Extensions/MaskServiceExtensions.cs, test/UnitTest/Services/MaskServiceTest.cs
=> feat(Mask): add Show extensions method

src/BootstrapBlazor.Server/Components/Samples/Table/TablesRow.razor, src/BootstrapBlazor/Components/Table/Table.razor, src/BootstrapBlazor/Components/Table/Table.razor.cs, test/UnitTest/Components/TableTest.cs
=> feat(Table): add RowContentTemplate parameter

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Display/DisplayBase.cs, src/BootstrapBlazor/Components/Table/Table.razor, test/UnitTest/Components/SelectTableTest.cs
=> fix(SelectTable): missing Label when inside InputGroup

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/BootstrapBlazor.Server/Components/Samples/Cameras.razor, src/BootstrapBlazor.Server/Components/Samples/Cameras.razor.cs, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Camera/Camera.razor, src/BootstrapBlazor/Components/Camera/Camera.razor.cs, src/BootstrapBlazor/Components/Camera/Camera.razor.js, src/BootstrapBlazor/Components/Camera/Camera.razor.scss
=> fix(Camera): resize method not working

src/BootstrapBlazor.Server/Components/Samples/Cameras.razor.cs, src/BootstrapBlazor/Components/Camera/Camera.razor.cs
=> doc(Camera): remove OnCapture documentation

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Drawer/Drawer.razor, src/BootstrapBlazor/Components/Drawer/Drawer.razor.cs, src/BootstrapBlazor/Components/Drawer/Drawer.razor.scss, test/UnitTest/Components/DrawerTest.cs
=> feat(Drawer): add Position parameter

src/BootstrapBlazor.Server/Components/Components/Video.razor, src/BootstrapBlazor.Server/Components/Pages/GlobalOption.razor, src/BootstrapBlazor.Server/Components/Samples/Drawers.razor, src/BootstrapBlazor.Server/Components/Samples/Drawers.razor.cs, src/BootstrapBlazor.Server/Components/Samples/Icons.razor, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor.Server/docs.json, src/BootstrapBlazor/Components/Dialog/DialogCloseButton.cs
=> doc(Video): add video link for components

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/Extensions/Components/BootstrapBlazor.BarCode/BootstrapBlazor.BarCode.csproj, src/Extensions/Components/BootstrapBlazor.BarCode/Components/BarcodeReader/BarcodeReader.razor, src/Extensions/Components/BootstrapBlazor.BarCode/Components/BarcodeReader/BarcodeReader.razor.cs, src/Extensions/Components/BootstrapBlazor.BarCode/Components/BarcodeReader/BarcodeReader.razor.js, src/Extensions/Components/BootstrapBlazor.BarCode/Components/QRCode/QRCode.razor, src/Extensions/Components/BootstrapBlazor.BarCode/Components/QRCode/QRCode.razor.cs, src/Extensions/Components/BootstrapBlazor.BarCode/Components/QRCode/QRCode.razor.js
=> refactor(BarCode): redesign BarCode package JavaScript logic

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/RibbonTab/RibbonTab.razor, src/BootstrapBlazor/Components/RibbonTab/RibbonTab.razor.cs, src/BootstrapBlazor/Components/RibbonTab/RibbonTab.razor.scss, src/BootstrapBlazor/Components/RibbonTab/RibbonTabHeader.razor, src/BootstrapBlazor/Components/RibbonTab/RibbonTabHeader.razor.cs
=> perf(RibbonTab): add RibbonTabHeader component improve performance

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/TreeView/TreeView.razor.cs
=> perf(TreeView): imporve render performance of TreeView ClearCheckedItems

localization/zh-TW.json
1. Update zh-TW.json from new version cn.json
2. Fix some wrong word in zh-TW.json
close #3937
=> doc(Localization): update zh-TW json

src/BootstrapBlazor.Server/Components/Samples/Table/TablesExport.razor, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json
=> doc(Table): add Pdf export documentation

src/BootstrapBlazor/Components/Table/Table.razor.Localization.cs, src/BootstrapBlazor/Components/Table/Table.razor.cs, src/BootstrapBlazor/Locales/en.json, src/BootstrapBlazor/Locales/zh.json
=> feat(Table): add AlignLeftText/AlignCenterText/AlignRightText parameter

src/BootstrapBlazor.Server/Components/Samples/Table/TablesColumnResizing.razor, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Table/Table.razor.js
=> fix(Table): can't close the context menu popover

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Layout/Layout.razor, src/BootstrapBlazor/Components/Layout/Layout.razor.cs, src/BootstrapBlazor/Utils/JSModule.cs, test/UnitTest/Components/ButtonTest.cs, test/UnitTest/Components/LayoutTest.cs
=> feat(Layout): do not render Header/Footer if template is null

src/BootstrapBlazor.Server/Components/Samples/EditorForms.razor, src/BootstrapBlazor.Server/Components/Samples/EditorForms.razor.cs, src/BootstrapBlazor/Attributes/AutoGenerateBaseAttribute.cs, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/EditorForm/EditorForm.razor.cs, src/BootstrapBlazor/Components/Table/TableColumn.cs
=> fix(EditorForm): update ItemsPerRow value is 1 logic

src/BootstrapBlazor/Components/Input/BootstrapInput.razor.cs, src/BootstrapBlazor/Components/Input/BootstrapInputBase.cs, test/UnitTest/Components/InputTest.cs
=> feat(BootstrapInput): add AutoSetDefaultWhenNull parameter

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Display/DisplayBase.cs, test/UnitTest/Components/CheckboxListTest.cs, test/UnitTest/Components/SliderTest.cs, test/UnitTest/Components/ValidateTest.cs
=> fix(InputGroup): compatible with InputGroup built-in ValidateForm

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Table/TableToolbar.razor.cs
=> fix(Table): IsDisabled parameter not work on TableToolbarButton

src/BootstrapBlazor.Server/Components/Components/ResultDialogDemo2.razor.cs, src/BootstrapBlazor.Server/Components/Samples/Modals.razor, src/BootstrapBlazor.Server/Components/Samples/Modals.razor.cs, src/BootstrapBlazor/Components/Input/BootstrapInputBase.cs, src/BootstrapBlazor/Components/Modal/Modal.razor.cs, test/UnitTest/Components/ButtonTest.cs, test/UnitTest/Components/ModalTest.cs, test/UnitTest/UnitTest.csproj
=> feat(Modal): add RegisterShownCallback method

src/BootstrapBlazor.Server/Components/Samples/TextAreas.razor, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Input/BootstrapInput.razor, src/BootstrapBlazor/Components/Input/BootstrapInputBase.cs, src/BootstrapBlazor/Components/Textarea/Textarea.razor, src/BootstrapBlazor/Components/Textarea/Textarea.razor.cs, src/BootstrapBlazor/Components/Textarea/Textarea.razor.js
=> feat(TextArea): support IsAutoFocus parameter

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Tab/Tab.razor.cs
=> fix(Tab): disable drag when set AllowDrag to false

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Table/Table.razor
=> fix(Table): ShownWithBreakpoint not work on CardView mode

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/TimePicker/TimePickerCell.razor.js
=> fix(TimePicker): can't update value in Dialog

src/BootstrapBlazor.Server/Components/Samples/IntersectionObservers.razor, src/BootstrapBlazor.Server/Components/Samples/IntersectionObservers.razor.cs, src/BootstrapBlazor.Server/Components/Samples/IntersectionObservers.razor.css, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/Components/IntersectionObserver/IntersectionObserver.razor.cs, src/BootstrapBlazor/Components/IntersectionObserver/IntersectionObserver.razor.js
=> feat(IntersectionObserver): add AutoUnobserve parameter

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/BootstrapBlazor.Server/Components/Samples/DriverDotnetJs.razor.cs, src/Extensions/Components/BootstrapBlazor.DriverJs/BootstrapBlazor.DriverJs.csproj, src/Extensions/Components/BootstrapBlazor.DriverJs/Components/DriverJs.razor.cs, src/Extensions/Components/BootstrapBlazor.DriverJs/Components/DriverJs.razor.js, src/Extensions/Components/BootstrapBlazor.DriverJs/Locales/zh.json
=> feat(DriverJs): add many instance method

src/BootstrapBlazor/Components/Table/Table.razor.js
=> fix(Table): throw exception when resize table

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Table/Table.razor.js
=> fix(Table): overflow container when toolbar or pages wrap

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/ValidateForm/ValidateForm.razor.cs, test/UnitTest/Components/DisplayTest.cs, test/UnitTest/Components/ValidateTest.cs
=> bug(ValidaetForm): do not show label when InputGroup inside ValidateForm

src/BootstrapBlazor/Components/TreeView/TreeView.razor, src/BootstrapBlazor/Components/TreeView/TreeView.razor.cs, test/UnitTest/Components/TreeViewTest.cs
=> feat(TreeView): MaxSelectedCount support collapsed node

src/BootstrapBlazor/Components/AutoFill/AutoFill.razor.cs
=> fix(AutoFill): support enter when set OnCustomeFilter callback

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Table/Table.razor.js
=> fix(Table): calc body height incorrect on CardView mode

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Icon/SvgIcon.razor, src/BootstrapBlazor/Components/Icon/SvgIcon.razor.cs, test/UnitTest/Components/SvgIconTest.cs
=> feat(SvgIcon): add SvgIcon component

src/BootstrapBlazor/Components/Table/Table.razor.Checkbox.cs
=> fix(Table): auto cancel edit when select multiple row on EditForm mode

src/BootstrapBlazor.Server/Components/Samples/Charts/Line.razor.cs, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Table/Table.razor.cs
=> fix(Table): fieldName incorrect when column set IsFixed=true

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/BootstrapBlazor.Server/Components/Samples/Table/TablesFooter.razor, src/BootstrapBlazor.Server/Components/Samples/Table/TablesFooter.razor.cs, src/BootstrapBlazor.Server/Components/Samples/Toasts.razor, src/BootstrapBlazor/Components/Table/Table.razor.scss
=> fix(Table): has gap when set IsFixedFooter to true

src/BootstrapBlazor.Server/Components/Samples/SortableLists.razor, src/BootstrapBlazor.Server/Components/Samples/SortableLists.razor.cs
=> doc(SortableList): update clone sample

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/BootstrapBlazor.Server/Components/Components/FooSortableListItem.razor, src/BootstrapBlazor.Server/Components/Components/FooSortableListItem.razor.cs, src/BootstrapBlazor.Server/Components/Components/FooSortableListItem.razor.css, src/BootstrapBlazor.Server/Components/Samples/SortableLists.razor, src/BootstrapBlazor.Server/Components/Samples/SortableLists.razor.cs, src/BootstrapBlazor.Server/Components/Samples/SortableLists.razor.css, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/Directory.Build.props, src/Extensions/Components/BootstrapBlazor.Sortable/BootstrapBlazor.Sortable.csproj, src/Extensions/Components/BootstrapBlazor.Sortable/Components/SortableEvent.cs, src/Extensions/Components/BootstrapBlazor.Sortable/Components/SortableList.razor.cs, src/Extensions/Components/BootstrapBlazor.Sortable/Components/SortableList.razor.css, src/Extensions/Components/BootstrapBlazor.Sortable/Components/SortableList.razor.js, src/Extensions/Components/BootstrapBlazor.Sortable/Components/SortableListItem.cs, src/Extensions/Components/BootstrapBlazor.Sortable/Components/SortableOption.cs, src/Extensions/Directory.Build.props
=> feat(SortableList): add MultiDrag parameter

src/Extensions/Components/BootstrapBlazor.TableExport/BootstrapBlazor.TableExport.csproj, src/Extensions/Components/BootstrapBlazor.TableExport/Services/ExportDataReader.cs
=> feat(TableExport): add DataReaderBase class

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Table/Table.razor.Edit.cs, src/BootstrapBlazor/Components/Table/Table.razor.Toolbar.cs
=> fix(Table): not callback SelectedRow when query data

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/BootstrapBlazor.Server/Components/Samples/Charts/Line.razor, src/BootstrapBlazor.Server/Components/Samples/Charts/Line.razor.cs, src/Extensions/Components/BootstrapBlazor.Chart/BootstrapBlazor.Chart.csproj, src/Extensions/Components/BootstrapBlazor.Chart/Components/Chart/Chart.razor.cs, src/Extensions/Components/BootstrapBlazor.Chart/Components/Chart/Chart.razor.js, src/Extensions/Components/BootstrapBlazor.Chart/Components/Chart/ChartDataSource.cs
=> refactor(Chart): move AppendData into ChartDataSource

src/BootstrapBlazor/Components/Upload/AvatarUpload.razor, src/BootstrapBlazor/Components/Upload/AvatarUpload.razor.cs, src/BootstrapBlazor/Components/Upload/CardUpload.razor, src/BootstrapBlazor/Components/Upload/CardUpload.razor.cs, src/BootstrapBlazor/wwwroot/modules/upload.js, test/UnitTest/Components/UploadTest.cs
=> feat(CardUpload): add IsUploadButtonAtFirst

src/BootstrapBlazor.Server/Components/Samples/Dispatches.razor, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Table/Table.razor.Edit.cs, src/BootstrapBlazor/Components/Table/Table.razor.Toolbar.cs, src/BootstrapBlazor/Services/IEntityFrameworkCoreDataService.cs, test/UnitTest/Components/ButtonTest.cs
=> refactor(Table): refactor logic for event callback selected row

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/Extensions/Components/BootstrapBlazor.Chart/BootstrapBlazor.Chart.csproj, src/Extensions/Components/BootstrapBlazor.Chart/Components/Chart/Chart.razor.cs, src/Extensions/Components/BootstrapBlazor.Chart/Components/Chart/Chart.razor.js
=> fix(Chart): reload method missong OnClickData callback

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/Extensions/Components/BootstrapBlazor.Chart/BootstrapBlazor.Chart.csproj, src/Extensions/Components/BootstrapBlazor.Chart/Components/Chart/Chart.razor.js
=> bug(Chart): update chart.js url

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Upload/ButtonUpload.razor, src/BootstrapBlazor/Components/Upload/ButtonUpload.razor.cs
=> feat(ButtonUpload): add ChildContent parameter

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/BootstrapBlazor.Server/Components/Samples/Translators.razor.cs, src/Extensions/Components/BootstrapBlazor.AzureTranslator/BootstrapBlazor.AzureTranslator.csproj, src/Extensions/Components/BootstrapBlazor.BaiduOcr/BootstrapBlazor.BaiduOcr.csproj, src/Extensions/Components/BootstrapBlazor.BaiduSpeech/BootstrapBlazor.BaiduSpeech.csproj, src/Extensions/Components/BootstrapBlazor.Html2Pdf.iText/BootstrapBlazor.Html2Pdf.iText.csproj, src/Extensions/Components/BootstrapBlazor.Html2Pdf/BootstrapBlazor.Html2Pdf.csproj, src/Extensions/Components/BootstrapBlazor.TableExport/BootstrapBlazor.TableExport.csproj, src/Extensions/Components/BootstrapBlazor.TableExport/MiniExcelDataReaderBase.cs, src/Extensions/DataServices/BootstrapBlazor.DataAccess.EntityFrameworkCore/BootstrapBlazor.DataAccess.EntityFrameworkCore.csproj, src/Extensions/DataServices/BootstrapBlazor.DataAccess.FreeSql/BootstrapBlazor.DataAccess.FreeSql.csproj, src/Extensions/DataServices/BootstrapBlazor.DataAccess.PetaPoco/BootstrapBlazor.DataAccess.PetaPoco.csproj, src/Extensions/DataServices/BootstrapBlazor.DataAccess.SqlSugar/BootstrapBlazor.DataAccess.SqlSugar.csproj, src/Extensions/DataServices/BootstrapBlazor.DataAccess.SqlSugar/DefaultDataService.cs, src/maui/BootstrapBlazor.Maui/BootstrapBlazor.Maui.csproj, test/UniTest.Sass/UniTest.Sass.csproj, test/UniTestSvgIcon/UniTestSvgIcon.csproj, test/UnitTest.Localization/BootstrapBlazorEnTestBase.cs, test/UnitTest.Localization/BootstrapBlazorZhTestBase .cs, test/UnitTest.Localization/UnitTest.Localization.csproj, test/UnitTest/Components/EditorFormTest.cs, test/UnitTest/Core/BootstrapEditorFormTestBase.cs, test/UnitTest/UnitTest.csproj, test/UnitTestDocs/UnitTestDocs.csproj, test/UnitTestEditor/EditorTest.cs, test/UnitTestEditor/UnitTestEditor.csproj, test/UnitTestHoliday/UnitTestHoliday.csproj
=> chore(Build): upgrade dependence to latest version

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Split/Split.razor.js, src/BootstrapBlazor/Components/Split/Split.razor.scss
=> fix(Split): iframe drags incorrectly

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/Extensions/Components/BootstrapBlazor.DockView/BootstrapBlazor.DockView.csproj, src/Extensions/Components/BootstrapBlazor.DockView/Components/DockViewComponent.razor.cs, src/Extensions/Components/BootstrapBlazor.DockView/Components/DockViewConfig.cs, src/Extensions/Components/BootstrapBlazor.DockView/Components/DockViewV2.razor.cs
=> feat(DockView): add Renderer parameter

src/BootstrapBlazor.Server/Components/Samples/Table/TablesColumn.razor, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Table/Table.razor.js
=> fix(Table): do not trigger sort when click copy column icon

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Split/Split.razor.js
=> fix(Split): mask not removed after drag

src/BootstrapBlazor.Server/Components/Samples/Speeches/WebSpeeches.razor, src/BootstrapBlazor.Server/Components/Samples/Speeches/WebSpeeches.razor.cs, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Speech/RecognizerService.cs, src/BootstrapBlazor/Components/Speech/SynthesizerService.cs, src/BootstrapBlazor/Components/Speech/WebSpeechService.cs, src/BootstrapBlazor/Components/Speech/WebSpeechSynthesizer.cs, src/BootstrapBlazor/Extensions/BootstrapBlazorServiceCollectionExtensions.cs, src/BootstrapBlazor/wwwroot/modules/speech.js
=> feat(WebSpeechSynthesizer): add WebSpeechSynthesizer service

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/Extensions/Components/BootstrapBlazor.TableExport/BootstrapBlazor.TableExport.csproj, src/Extensions/Components/BootstrapBlazor.TableExport/Services/ExportDataReader.cs
=> fix(TableExport): throw exception when exeport excel

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/Extensions/Components/BootstrapBlazor.WinBox/BootstrapBlazor.WinBox.csproj, src/Extensions/Components/BootstrapBlazor.WinBox/WinBox.razor.js
=> fix(WinBox): Title parameter not work

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/Extensions/Components/BootstrapBlazor.WinBox/BootstrapBlazor.WinBox.csproj, src/Extensions/Components/BootstrapBlazor.WinBox/wwwroot/css/winbox.bundle.css
=> feat(WinBox): add Mask background color function

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/AutoComplete/AutoComplete.razor.js
=> fix(AutoComplete): support Tab when set IsPopover to true

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Button/PopConfirmButtonBase.cs
=> fix(PopConfirmButton): auto reset palcement to Auto

src/BootstrapBlazor.Server/Components/Samples/Splits.razor, src/BootstrapBlazor.Server/Components/Samples/Splits.razor.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/Components/Split/Split.razor, src/BootstrapBlazor/Components/Split/Split.razor.cs, test/UnitTest/Components/PopConfirmButtonTest.cs, test/UnitTest/Components/SplitTest.cs
=> feat(Split): add ShowBarHandle parameter

src/BootstrapBlazor.Server/Components/Samples/Splits.razor, src/BootstrapBlazor.Server/Components/Samples/Splits.razor.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Split/Split.razor.cs, src/BootstrapBlazor/Components/Split/Split.razor.js, src/BootstrapBlazor/Components/Split/SplitterResizedEventArgs.cs, test/UnitTest/Components/SplitTest.cs
=> feat(Split): add OnResizeAsync parameter

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Split/Split.razor.js, src/BootstrapBlazor/Components/Split/Split.razor.scss, src/BootstrapBlazor/Components/Tooltip/Tooltip.razor.js
=> feat(Split): resolve minimum setting conflict

src/BootstrapBlazor.Server/Components/Samples/Splits.razor, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/Components/Split/Split.razor.js
=> refactor(Split): update javascript make min/max correct

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/BootstrapBlazor.Server/Components/Samples/Players.razor, src/BootstrapBlazor.Server/Components/Samples/Players.razor.cs, src/Extensions/Components/BootstrapBlazor.Player/BootstrapBlazor.Player.csproj, src/Extensions/Components/BootstrapBlazor.Player/Player.razor, src/Extensions/Components/BootstrapBlazor.Player/Player.razor.cs, src/Extensions/Components/BootstrapBlazor.Player/Player.razor.css, src/Extensions/Components/BootstrapBlazor.Player/Player.razor.js, src/Extensions/Components/BootstrapBlazor.Player/PlayerOption.cs, src/Extensions/Components/BootstrapBlazor.Player/PlayerSource.cs, src/Extensions/Components/BootstrapBlazor.Player/PlayerThumbnail.cs, src/Extensions/Components/BootstrapBlazor.Player/PlayerTracks.cs, src/Extensions/Components/BootstrapBlazor.Player/wwwroot/plyr-plugin-thumbnail.js
=> refactor(Player): redesign Player component use Callback

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/BootstrapBlazor.Server/Components/Samples/Players.razor, src/BootstrapBlazor.Server/Components/Samples/Players.razor.cs, src/BootstrapBlazor.Server/Extensions/MenusLocalizerExtensions.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor.Server/docs.json, src/Extensions/Components/BootstrapBlazor.Player/BootstrapBlazor.Player.csproj, src/Extensions/Components/BootstrapBlazor.Player/Player.razor, src/Extensions/Components/BootstrapBlazor.Player/Player.razor.css, src/Extensions/Components/BootstrapBlazor.Player/Player.razor.js, src/Extensions/Components/BootstrapBlazor.Player/PlayerMarker.cs, src/Extensions/Components/BootstrapBlazor.Player/PlayerOption.cs, src/Extensions/Components/BootstrapBlazor.Player/PlayerPoint.cs
=> feat(Player): add IsHls parameter

src/BootstrapBlazor.Server/Components/Samples/Players.razor, src/BootstrapBlazor.Server/Components/Samples/Players.razor.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/Extensions/Components/BootstrapBlazor.Player/Player.razor.cs, src/Extensions/Components/BootstrapBlazor.Player/Player.razor.js, src/Extensions/Components/BootstrapBlazor.Player/PlayerOptions.cs, src/Extensions/Components/BootstrapBlazor.Player/PlayerSource.cs
=> feat(Player): add Reload instance method

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/Extensions/Components/BootstrapBlazor.DockView/BootstrapBlazor.DockView.csproj, src/Extensions/Components/BootstrapBlazor.DockView/Components/DockViewConfig.cs, src/Extensions/Components/BootstrapBlazor.DockView/Components/DockViewV2.razor.cs, src/Extensions/Components/BootstrapBlazor.DockView/wwwroot/js/dockview-panel.js
=> feat(DockViewV2): update Renderer default value

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/BootstrapBlazor.Server/Components/Samples/Players.razor, src/BootstrapBlazor.Server/Components/Samples/Players.razor.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/Extensions/Components/BootstrapBlazor.Player/BootstrapBlazor.Player.csproj, src/Extensions/Components/BootstrapBlazor.Player/Player.razor, src/Extensions/Components/BootstrapBlazor.Player/Player.razor.cs, src/Extensions/Components/BootstrapBlazor.Player/PlayerMode.cs, src/Extensions/Components/BootstrapBlazor.Player/PlayerOptions.cs
=> feat(Player): add Mode parameter

src/BootstrapBlazor/Attributes/AutoGenerateColumnAttribute.cs, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/EditorForm/EditorItem.cs, src/BootstrapBlazor/Components/EditorForm/IEditorItem.cs, src/BootstrapBlazor/Components/Table/ITableColumn.cs, src/BootstrapBlazor/Components/Table/InternalTableColumn.cs, src/BootstrapBlazor/Components/Table/TableColumn.cs, src/BootstrapBlazor/Components/Validate/ValidateBase.cs, src/BootstrapBlazor/Extensions/ITableColumnExtensions.cs, src/BootstrapBlazor/Locales/en.json, src/BootstrapBlazor/Locales/zh.json, src/BootstrapBlazor/Utils/Utility.cs, src/BootstrapBlazor/Validators/FormItemValidator.cs, test/UnitTest/Attributes/AutoGenerateClassTest.cs, test/UnitTest/Components/EditorFormTest.cs, test/UnitTest/Components/TableColumnTest.cs, test/UnitTest/Components/TableDialogTest.cs, test/UnitTest/Extensions/ITableColumnExtensionsTest.cs
=> feat(Table): add Required parameter

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/Extensions/Components/BootstrapBlazor.CherryMarkdown/BootstrapBlazor.CherryMarkdown.csproj, src/Extensions/Components/BootstrapBlazor.CherryMarkdown/Components/CherryMarkdown/CherryMarkdown.razor, src/Extensions/Components/BootstrapBlazor.CherryMarkdown/Components/CherryMarkdown/CherryMarkdown.razor.cs, src/Extensions/Components/BootstrapBlazor.CherryMarkdown/Components/CherryMarkdown/CherryMarkdown.razor.js
=> feat(CherryMarkdown): inherits BootstrapModuleComponentBase

src/BootstrapBlazor.Server/Components/Samples/CodeEditors.razor, src/BootstrapBlazor.Server/Components/Samples/OnScreenKeyboards.razor, src/BootstrapBlazor.Server/Components/Samples/SweetAlerts.razor, src/BootstrapBlazor/Extensions/JSModuleExtensions.cs, test/UnitTest/Extensions/JSModuleExtensionsTest.cs
=> doc(CodeEditor): remove sample code for anlysis log

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Button/PopConfirmButton.razor.js
=> bug(PopConfirmButtom): throw exception cause dispose

src/BootstrapBlazor.Server/Components/Samples/ColorPickers.razor, src/BootstrapBlazor.Server/Components/Samples/ColorPickers.razor.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/ColorPicker/ColorPicker.razor.cs, src/BootstrapBlazor/Components/ColorPicker/ColorPicker.razor.js, src/BootstrapBlazor/Components/ColorPicker/ColorPicker.razor.scss, test/UnitTest/Components/ColorPickerTest.cs
=> feat(ColorPicker): support IsDiabled parameter

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/ColorPicker/ColorPicker.razor.js, src/BootstrapBlazor/Components/Radio/RadioList.razor.scss
=> fix(RadioList): update vertical button style

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Table/Table.razor.Toolbar.cs, src/BootstrapBlazor/Components/Table/Table.razor.js
=> fix(Table): not collapse edit form after save the new item

README.md, README.zh-CN.md, src/BootstrapBlazor.Server/Components/Layout/ComponentLayout.razor, src/BootstrapBlazor/readme.md
=> doc(Readme): remove oscs badge

exclusion.dic, src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/BootstrapBlazor.Server/Components/Samples/Players.razor, src/BootstrapBlazor.Server/Components/Samples/Players.razor.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/Converter/JsonEnumConverter.cs, src/Extensions/Components/BootstrapBlazor.Player/BootstrapBlazor.Player.csproj, src/Extensions/Components/BootstrapBlazor.Player/Player.razor, src/Extensions/Components/BootstrapBlazor.Player/Player.razor.cs, src/Extensions/Components/BootstrapBlazor.Player/Player.razor.js, src/Extensions/Components/BootstrapBlazor.Player/PlayerMarkers.cs, src/Extensions/Components/BootstrapBlazor.Player/PlayerMode.cs, src/Extensions/Components/BootstrapBlazor.Player/PlayerOptions.cs, src/Extensions/Components/BootstrapBlazor.Player/PlayerSource.cs, src/Extensions/Components/BootstrapBlazor.Player/PlayerSources.cs
=> feat(Player): support YouTube Vimeo video

src/BootstrapBlazor.Server/Components/Samples/ValidateForms.razor, src/BootstrapBlazor.Server/Locales/zh-CN.json
rename CustomerValidator to FormItemValidator
close #4248
=> doc(ValidateForm): rename CustomerValidator to FormItemValidator

src/BootstrapBlazor/Components/ValidateForm/ValidateForm.razor.cs, test/UnitTest/Components/ValidateFormTest.cs
close https://github.com/dotnetcore/BootstrapBlazor/issues/4243
=> fix(ValidateForm): ValidateAllProperties not work

src/Extensions/DataServices/BootstrapBlazor.DataAccess.EntityFrameworkCore/DefaultDataService.cs
重现步骤，编辑保存，多次编辑同一个，新增实体后后马上编辑。均可重现
close #4250
=> fix(EFCore): update EditAsync method

src/BootstrapBlazor/Components/Validate/ValidateBase.cs, test/UnitTest/Components/ValidateFormTest.cs
=> bug(ValidateBase): should Render UI after validate

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Cascader/Cascader.razor, src/BootstrapBlazor/Components/Cascader/Cascader.razor.cs
=> fix(Cascader): not pop dropdown menu after update IsDisable to false

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Filters/TableFilter.razor, test/UnitTest/Components/TableNumberFilterTest.cs
=> feat(NumberFilter): support nullable data type

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Table/Table.razor
=> feat(Table): add cascading value ChangeType to EditTemplate

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Layout/Layout.razor.scss, src/BootstrapBlazor/wwwroot/scss/theme/bootstrapblazor.scss
=> feat(Layout): support dark mode

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/Extensions/Components/BootstrapBlazor.BarCode/BootstrapBlazor.BarCode.csproj, src/Extensions/Components/BootstrapBlazor.BarCode/Components/BarcodeReader/BarcodeReader.razor, src/Extensions/Components/BootstrapBlazor.BarCode/Components/BarcodeReader/BarcodeReader.razor.cs
=> bug(BarCode): not work missing Id

README.md, README.zh-CN.md, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/readme.md
=> doc(readme): update readme documentation

src/BootstrapBlazor.Server/Components/Components/FooSortableListRightItem.razor, src/BootstrapBlazor.Server/Components/Components/FooSortableListRightItem.razor.cs, src/BootstrapBlazor.Server/Components/Components/FooSortableListRightItem.razor.css, src/BootstrapBlazor.Server/Components/Samples/SortableLists.razor
=> doc(SortableList): add custom template sample

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj
=> fix(SortableList): incorrect dom when set Clone to true

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/BootstrapBlazor.Server/Components/Samples/OnScreenKeyboards.razor, src/BootstrapBlazor.Server/Components/Samples/OnScreenKeyboards.razor.cs
=> feat(OnScreenKeyboard): update base class to fix script error

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/ValidateForm/ValidateForm.razor.js
close #4331 
link #4301 #4309
[是否影响老版本]
=> fix(ValidateForm): show first element tooltip when set ShowAllInvalidResult to false

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Checkbox/Checkbox.razor.cs, test/UnitTest/Components/CheckboxListTest.cs
=> feat(Checkbox): auto set DisplayText when set ShowAfterLabel to true

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/BootstrapBlazor.Server/Components/Samples/FileViewers.razor.cs
=> refactor(FileViewer): bump version 8.1.0

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/BootstrapBlazor.Server/Components/Samples/FileViewers.razor.cs
=> chore(VideoPlayer): upgrade package version

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/BaseComponents/BootstrapModuleComponentBase.cs, src/BootstrapBlazor/Components/Modal/Modal.razor.cs, src/BootstrapBlazor/Components/Table/TableToolbarButton.cs, src/BootstrapBlazor/Components/Table/TableToolbarPopConfirmButton.cs
=> feat(Dialog): support call show OnAfterRender lifecycle

src/BootstrapBlazor.Server/Components/Components/CustomerSelectDialog.razor.cs, src/BootstrapBlazor.Server/Components/Samples/TreeViews.razor, src/BootstrapBlazor.Server/Components/Samples/TreeViews.razor.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/TreeView/TreeView.razor, src/BootstrapBlazor/Components/TreeView/TreeView.razor.cs, src/BootstrapBlazor/Components/TreeView/TreeView.razor.js, src/BootstrapBlazor/Extensions/TreeItemExtensions.cs, test/UnitTest/Components/TreeViewTest.cs
#support keyboard shortcut
Fixes #4344 
[是否影响老版本]
=> feat(TreeView): support keyboard shortcut

src/BootstrapBlazor.Server/Components/Samples/TreeViews.razor, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/TreeView/TreeView.razor, src/BootstrapBlazor/Components/TreeView/TreeView.razor.cs, src/BootstrapBlazor/Components/TreeView/TreeView.razor.js, test/UnitTest/Components/TreeViewTest.cs
{Detail}
fixes #4350 
[是否影响老版本]
=> feat(TreeView): support toggle node by ArrowLeft/Right

src/BootstrapBlazor.Server/Components/Samples/TreeViews.razor, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/TreeView/TreeView.razor.js
{Detail}
Fixes #4352 
[是否影响老版本]
=> refactor(TreeView): prevent space key default action

.github/pull_request_template.md, src/BootstrapBlazor/BootstrapBlazor.csproj, src/Bundle.props, src/Frameworks.props, test/UniTest.Sass/UniTest.Sass.csproj, test/UniTestSvgIcon/UniTestSvgIcon.csproj, test/UnitTest.Localization/UnitTest.Localization.csproj, test/UnitTest/UnitTest.csproj, test/UnitTestDocs/UnitTestDocs.csproj
{Detail}
Fixes #4354 
[是否影响老版本]
=> chore(Dependence): update project configuration

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Table/Table.razor.cs
=> fix(Table): search model initialize twice

src/BootstrapBlazor.Server/Components/Pages/Online.razor.css, src/BootstrapBlazor.Server/Components/Samples/DockViews2/BaseDockView.cs, src/BootstrapBlazor.Server/Components/Samples/DockViews2/DockViewCol.razor, src/BootstrapBlazor.Server/Components/Samples/DockViews2/DockViewComplex.razor, src/BootstrapBlazor.Server/Components/Samples/DockViews2/DockViewGroup.razor, src/BootstrapBlazor.Server/Components/Samples/DockViews2/DockViewNest.razor, src/BootstrapBlazor.Server/Components/Samples/DockViews2/DockViewRow.razor, src/BootstrapBlazor.Server/Components/Samples/DockViews2/DockViewTitle.razor
=> doc(DockView): update dockview sample code

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj
=> feat(SignaturePad): remove css isolation

src/BootstrapBlazor/Components/Icon/BootstrapBlazorIcon.razor.scss, src/BootstrapBlazor/Components/Icon/SvgIcon.razor.scss, src/BootstrapBlazor/wwwroot/scss/components.scss, src/BootstrapBlazor/wwwroot/scss/theme/bootstrapblazor.scss
=> refactor(SvgIcon): add css variable

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj
=> feat(Topology): remove css isoloation

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj
=> chore(TableExport): bump version 8.3.0

src/BootstrapBlazor.Server/Components/Components/Pre.razor.cs, src/BootstrapBlazor/Components/AutoComplete/AutoComplete.razor.cs, test/UnitTest/Components/AutoCompleteTest.cs
=> feat(AutoComplete): add OnBlurAsync parameter

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Table/Table.razor
=> fix(Table): table footer cell not update in Card mode

README.md, README.zh-CN.md, src/BootstrapBlazor.Server/Components/Pages/Index.razor, src/BootstrapBlazor.Server/Components/Pages/Index.razor.css
=> doc(Readme): add .net foundation code of conduct

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj
=> doc(HtmlToPdf): bump version 8.2.1

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Directory.Build.props, src/Bundle.props, src/Directory.Build.props
=> chore(Props): update project configuration 

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/BootstrapBlazor.Server/Components/Pages/Chats.razor.cs
=> chore(deps): update dependence

src/BootstrapBlazor/Components/ColorPicker/ColorPicker.razor.js
=> fix(ColorPicker): throw exception when dispose

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Select/Select.razor.scss, src/BootstrapBlazor/wwwroot/scss/theme/bootstrapblazor.scss
=> fix(Select): update padding-right variable

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Tab/Tab.razor.cs
=> feat(Tab): support style attribute

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj
=> chore(Icon): bump version 8.1.0

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Services/DefaultZipArchiveService.cs, test/UnitTest/Services/ZipArchiveServiceTest.cs
=> feat(IZipArchiveService): auto create zip folder

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/BootstrapBlazor/Directory.Build.props
=> doc(Site): update dependencies to the latest

src/BootstrapBlazor/Directory.Build.props
=> chore(sdk): add net9 sdk support

src/BootstrapBlazor.Server/Components/App.razor, src/BootstrapBlazor/Components/Checkbox/CheckboxList.razor.scss, src/BootstrapBlazor/Directory.Build.props
=> feat(CheckboxList): update style of IsVertical

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/FileIcon/FileIcon.razor.scss, src/BootstrapBlazor/wwwroot/scss/theme/bootstrapblazor.scss
=> fix(FileIcon): missing svg widht/height

src/BootstrapBlazor/Components/Button/SlideButton.razor.cs
=> doc(SlideButton): update Offset annotate

.editorconfig, src/BootstrapBlazor.Server/Components/Samples/Bluetooth.razor, src/BootstrapBlazor.Server/Components/Samples/Bluetooth.razor.cs, src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json, src/BootstrapBlazor/Extensions/BluetoothExtensions.cs, src/BootstrapBlazor/Services/Bluetooth/BluetoothDevice.cs, src/BootstrapBlazor/Services/Bluetooth/BluetoothDeviceInfo.cs, src/BootstrapBlazor/Services/Bluetooth/BluetoothRequestOptions.cs, src/BootstrapBlazor/Services/Bluetooth/BluetoothServices.cs, src/BootstrapBlazor/Services/Bluetooth/DefaultBluetoothService.cs, src/BootstrapBlazor/Services/Bluetooth/IBluetoothDevice.cs, src/BootstrapBlazor/Services/Bluetooth/IBluetoothService.cs, src/BootstrapBlazor/wwwroot/modules/bt.js, test/UnitTest/Services/BluetoothServiceTest.cs
=> feat(BluetoothDevice): add GetCurrentTime method

src/BootstrapBlazor/Directory.Build.props, src/BootstrapBlazor/Directory.Build.targets
=> chore(Sass): move sass dept into targets

src/BootstrapBlazor.Shared/Components/Pages/GlobalOption.razor, src/BootstrapBlazor/Components/ValidateForm/ValidateForm.razor
=> doc(Global): update global option document

src/BootstrapBlazor.Server/Locales/en-US.json, src/BootstrapBlazor.Server/Locales/zh-CN.json
修改 TablesEdit 的使用描述，使用内置的编辑需要正确配置 [Key]
fixes #4871 
[是否影响老版本]
=> doc(Table): update bind-Items documentation

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/EditorForm/EditorForm.razor, src/BootstrapBlazor/Components/ValidateForm/ValidateForm.razor
=> refactor(EditForm): remove lookup service second render

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj, src/BootstrapBlazor.Server/Components/Components/Pre.razor.css, src/BootstrapBlazor.Server/Components/Samples/CodeEditors.razor, src/BootstrapBlazor.Server/Components/Samples/CodeEditors.razor.cs
=> doc(CodeEditor): remove dependence of CodeEditor

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Filters/TableFilter.razor
修复 `TableFilter` 组件中的子组件 `LookupFilter` 的属性 `LookupServiceKey` 赋值为字符串 `"Column.LookupServiceKey"` 问题。
fixes #{bug number} (in this specific format)
[是否影响老版本]
=> feat(TableFilter): add @ keyword

src/BootstrapBlazor/Components/Watermark/Watermark.razor.js
=> refactor(Watermark): update background size check logic

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj
=> refactor(DockViewV2): upgrade to 9.0.3

.github/pull_request_template.md, .github/workflows/docker.yml, .github/workflows/pack.yml
[请在下方 # 后面填写相关 Issue 编号，如 #42]
close #5533
This pull request includes changes to the GitHub workflow and pull request template files to improve clarity and functionality. The most important changes include modifications to the pull request template for better instructions and updates to the workflow files to include additional branches.
Improvements to pull request template:
* [`.github/pull_request_template.md`](diffhunk://#diff-b2496e80299b8c3150b1944450bd81c622e04e13d15c411d291db0927d75fd6bL3-R5): Updated the instructions for linking issues to be clearer and more user-friendly. [[1]](diffhunk://#diff-b2496e80299b8c3150b1944450bd81c622e04e13d15c411d291db0927d75fd6bL3-R5) [[2]](diffhunk://#diff-b2496e80299b8c3150b1944450bd81c622e04e13d15c411d291db0927d75fd6bL15)
Updates to workflow …
=> chore(Template): add release branch support

src/BootstrapBlazor/Components/DateTimePicker/DateTimePicker.razor.js, src/BootstrapBlazor/Components/Table/Table.razor.js, src/BootstrapBlazor/Components/Typed/Typed.razor.js, src/BootstrapBlazor/wwwroot/modules/fullscreen.js, src/BootstrapBlazor/wwwroot/modules/utility.js
fixes #5577 
This pull request includes various improvements and bug fixes across multiple JavaScript files in the `BootstrapBlazor` components. The changes focus on improving code readability, ensuring proper handling of nullish values, and enhancing functionality.
Improvements to code readability and functionality:
* [`src/BootstrapBlazor/Components/DateTimePicker/DateTimePicker.razor.js`](diffhunk://#diff-ba22e00263a788d75c70dc882584a726c3b4cbee395b52f7877a635f17f01d8bL16-R18): Modified the `hideCallback` function to use an explicit null check instead of optional chaining for better readability.
* [`src/BootstrapBlazor/Components/Table/Table.razor.js`](diffhunk://#diff-080c07c5811f2244328c36fb1122f2b89ddd853f4e5af00afd577cb0e1c87c40L428-R447): Improved the keyboard navigation logic by …
=> chore(Script): downgrade script syntax

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj
=> feat(Markdown): support default Language

src/BootstrapBlazor/BootstrapBlazor.csproj, src/BootstrapBlazor/Components/Checkbox/CheckboxListGeneric.razor.cs, test/UnitTest/Components/SelectTest.cs
=> fix(CheckbxoList): resolve mvvm not work

.github/workflows/build.yml
=> test(Localizer): update localizer test project folder path

.fork/custom-commands.json
=> chore(Fork): update branch variable in script

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj
=> chore(TableExport): bump version 9.2.5

src/BootstrapBlazor/Components/Input/BootstrapInputGroup.razor.scss, src/BootstrapBlazor/Components/Input/BootstrapInputGroupLabel.razor, src/BootstrapBlazor/Components/Input/BootstrapInputGroupLabel.razor.cs
=> refactor(BootstrapInputGroupLabel): use DynamicElement unified tag

src/BootstrapBlazor/Components/BaseComponents/BootstrapBlazorRoot.razor, src/BootstrapBlazor/Components/BaseComponents/BootstrapBlazorRoot.razor.cs, src/BootstrapBlazor/Services/BootstrapServiceBase.cs
=> feat(BootstrapServiceBase): update exception message

src/BootstrapBlazor/Icons/BootstrapIcons.cs, src/BootstrapBlazor/Icons/FontAwesomeIcons.cs, src/BootstrapBlazor/Icons/MaterialDesignIcons.cs
=> feat(Table): update TableResetSearchButtonIcon icon

src/BootstrapBlazor/Services/TcpSocket/TcpSocketClientBase.cs, test/UnitTest/Services/TcpSocketFactoryTest.cs
=> feat(ITcpSocketClient): add concurrency connectlogic

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj
=> feat(DockView): add shadow for float panel

src/BootstrapBlazor.Server/Components/Components/QQGroup.razor
=> doc(QQGroup): update the DOM layout

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj
=> fix(PdfViewer): no render when url is empty

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj
=> feat(IPRegion): use async increase load speed

src/BootstrapBlazor.Server/Components/Samples/SelectTables.razor.cs
=> doc(SelectTable): remove Items parameter doc

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj
=> feat(Plyr): bump version 9.0.2

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj
=> doc(Socket): update socket extension namespace

src/BootstrapBlazor.Server/BootstrapBlazor.Server.csproj
=> fix(DockView): component disappearing when moving from floating to new grid group

src/BootstrapBlazor.Server/Components/Samples/Modbus/ModbusFactories.razor
=> doc(Modbus): update IModbusClient documentation

localization/pt.json
=> doc(Localization): update PT localization documentation
